### ISSUE TITLE
Rich text editor not compatible with Internet Explorer 11

### ISSUE THREAD

**Issue by athulpraj** [thedevdojo/voyager#2741] opened 2018-02-28 07:34 UTC
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version:7.0

Rich text editor not visible in Internet Explorer

http://prntscr.com/ikrkjq

**Comment by fletch3555** [comment] 2018-02-28 14:18
1.0 is not a valid version, please include the patch version as well.

Also, showing that it's not there isn't enough.  Please show you've at least attempted the bare minimum of troubleshooting.  In your case, "bare minimum" would include checking the browser console for any errors (JS or otherwise), and provide those to us (assuming you don't answer your own question by seeing them), and checking the source markup for the page to make sure the field actually exists.

**Comment by fletch3555** [comment] 2018-03-20 19:15
Duplicate of #2858

**Closed as completed by fletch3555** 2018-03-20 19:15 UTC
Labels: duplicate
