### ISSUE TITLE
Maximum execution time of 30 seconds exceeded if table consists around 2000+ records

### ISSUE THREAD

**Issue by AndrewRadchenko** [thedevdojo/voyager#4344] opened 2019-08-18 08:14 UTC
## Version information
 - Laravel: v5.8.29
 - Voyager: v1.2.6
 - PHP: 7.1.30
 - Database: MySQL 5.7.27

## Description
Records list page of table with more than 2000-3000 records don't open because of timeout.
It seems like voyager tries to load data of all records with the first request and then just dynamically changes content of pagination. But if there is a large size of table (like 2000+ records) it takes too much time. Next, record list not opened (timeout exception) if size is much more (like 10K+ records). 

## Steps To Reproduce
1. Create table for more than 2K-10K records
2. Add BREAD for this table
3. Try to browse this table
4. After some time (1-5 minutes) you will get timeout exception

## Expected behavior
It's much better to load only records that shall be visible on current browse page + records for next two pages. (E.g. if 10 records on page, then to load just 30 records). If we go to next pages, then upload new records dynamically. 

## Screenshots
Before error page
![Снимок экрана 2019-08-18 в 11 09 52](https://user-images.githubusercontent.com/22329845/63221939-47d0a280-c1a9-11e9-9b7c-5c2340c2b122.jpg)

then:
![Снимок экрана 2019-08-18 в 11 10 32](https://user-images.githubusercontent.com/22329845/63221942-50c17400-c1a9-11e9-9562-0c5da4121718.jpg)

## Additional information
PS: Increasing of maximum execution time is not a good idea.

**Comment by emptynick** [comment] 2019-08-18 08:29
Please search before opening issues.
Duplicate of #2515 (and much more)

**Closed as completed by emptynick** 2019-08-18 08:29 UTC
Labels: duplicate
