### ISSUE TITLE
Permissions are not saved

### ISSUE THREAD

**Issue by devig** [thedevdojo/voyager#4776] opened 2020-02-22 02:01 UTC
- Laravel: v6.2
 - Voyager: v1.3.1
 - PHP: 7.4
 - Database: MySQL 8.0

## Description
Permissions are not saved after submit

## Steps To Reproduce
1. Go to '/admin/roles/1/edit'
2. Click on any checkbox (uncheck it)
3. Scroll down to Submit button
4. Click on Submit button

## Expected behavior
Permissions should be saved, but not

**Comment by MrCrayon** [comment] 2020-02-22 02:04
Please search before opening an issue. 

Duplicate of #4668

**Closed as completed by MrCrayon** 2020-02-22 02:04 UTC
Labels: duplicate
