### ISSUE TITLE
Database manager doesn't work

### ISSUE THREAD

**Issue by valkedev** [thedevdojo/voyager#4599] opened 2019-11-30 08:32 UTC
Laravel: 6.6.0
Voyager: 1.3.0
PHP: 7.3.6

Made a clear install of Laravel and then Voyager;
Navigated to Tools/Database and got this
![image](https://user-images.githubusercontent.com/1539181/69898050-1a2cf500-1365-11ea-84ed-d2843296178b.png)

**Comment by MrCrayon** [comment] 2019-11-30 08:35
Please search before opening an issue. 
Duplicate of #4586

**Closed as completed** 2019-11-30 08:36 UTC
Labels: duplicate
