### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TahereChegini** [thedevdojo/voyager#3308] opened 2018-06-14 07:12 UTC
- Laravel Version: Laravel Framework 5.6.25
- Voyager Version: #.#.#
- PHP Version: 7
- Database Driver & Version: mysql

hi. i have error with mysql in this commnad-> php artisan voyager:install
this is error text:
   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter ta
ble `users` add unique `users_email_unique`(`email`))

**Comment by emptynick** [comment] 2018-06-14 11:12
Please search before opening a new issue.
Duplicate of https://github.com/the-control-group/voyager/issues/3035, #1840, #901
There are a few other links and solutions here https://github.com/the-control-group/voyager/issues/2540#issuecomment-360172218

Also, the next time please provide all version informations.
The Voyager-version is the most important one.

**Closed as completed by emptynick** 2018-06-14 11:12 UTC
Labels: duplicate
