### ISSUE TITLE
The setting module not keeps Logo image

### ISSUE THREAD

**Issue by anbkit** [thedevdojo/voyager#3224] opened 2018-05-23 06:24 UTC
- Laravel Version: 5.5
- Voyager Version: 1.1.1
- PHP Version: 7.1
- Database Driver & Version:

### Description:
The setting module doesn't keep Logo image when i update another fields.

**Comment by emptynick** [comment] 2018-05-23 07:48
Please search before opening a issue.
Duplicate of #3158, #3059 and #2934
Fix in #3060

**Closed as completed by emptynick** 2018-05-23 07:48 UTC
Labels: duplicate
