### ISSUE TITLE
pivot table relation

### ISSUE THREAD

**Issue by michaelmano** [thedevdojo/voyager#1581] opened 2017-08-22 06:13 UTC
- Laravel Version:  5.4.9
- Voyager Version: latest
- PHP Version: 7.1.8
- Database Driver & Version: MySQL 5.7

### Description:

I've read through the documentation and played with voyager for a few days and it seems at the moment the only way to get a pivot belongsToMany relation to show up on the edit page is to create an empty database column with the exact same name as the pivot relation?

Will this always be the case? as this is not very good practice and can cause issues with existing projects and seeders.

**Comment by artifacts** [comment] 2017-08-28 14:27
👍  I'm wondering about this too. This pollutes the database schema :/

**Comment by johnmain** [comment] 2017-08-28 17:45
@michaelmano 
does your multiselect dropdown function?  can you share your config.  I can't get my option items to populate the option value attribute.

**Comment by artifacts** [comment] 2017-08-28 17:58
Here's mine:
I have an entity  named "Route" which has a relation to multiple "Location" entities via a pivot table.

This is the voyager BREAD json config:

```
{
    "relationship": {
        "key": "id",
        "label": "title",
        "page_slug": "admin/locations"
    }
}
```

Route.php:

    public function locations() {
      return $this->belongsToMany(Location::class);
    }

This works, but only because I added a column named "locations" in the route table, which is quite confusing. If I don't have the column, I could not figure out how to configure BREAD for this property.

Since it is stated explicitly in the docs, I assume that this is the current way to do it:

> Simply enough, inside of the pages BREAD we would choose a Multiple Select as the input type for a categories row (this row can be any type) and include the following Optional Details as we did above:

See https://laravelvoyager.com/docs/0.11/#core-concepts-bread-relationships

**Comment by johnmain** [comment] 2017-08-28 18:02
And you have a pivot table route_locations?

**Comment by artifacts** [comment] 2017-08-28 18:30
@johnmain

Actually it's called location_route:

> Name of the pivot table should consist of singular names of both tables, separated by undescore symbole and these names should be arranged in alphabetical order, so we have to have product_shop, not shop_product.

See: http://laraveldaily.com/pivot-tables-and-many-to-many-relationships/

Though I don't know if that's important ...

Here's the Schema for the pivot table:

```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class LocationRoutePivotTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
      Schema::create('location_route', function(Blueprint $table)
      {
          $table->integer('location_id')->unsigned()->index();
          $table->foreign('location_id')->references('id')->on('locations')->onDelete('cascade');
          $table->integer('route_id')->unsigned()->index();
          $table->foreign('route_id')->references('id')->on('routes')->onDelete('cascade');
      });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('location_route');
    }
}

```

**Comment by johnmain** [comment] 2017-08-28 19:02
Ahh yeah.  that fixed my issue.  I think it was my Pivot table config.  I used your migration and I now have ids in my options.
Thanks

**Comment by artifacts** [comment] 2017-08-29 13:53
Ok, after some fiddling I found a workaround:

- The table data_rows in the database holds the information about the BREAD config.
- It is sufficient to add a row, the forms will work

For BREAD editing:
It seems like the author has intended to add fields beyond existing columns in the db:

DataType.php gathers information about the entitie's database table definition/schema in a method called fieldOptions(). The result is a multidimensional array which is iterated through in vendor/tcg/voyager/resources/views/tools/database/edit-add-bread.blade.php to setup the BREAD config table.
There is a method named extraFields() in DataType.php, which checks the model for the existance of a method called adminFields().

I implemented adminFields() in my model class to return a twodimensional array holding some fake values:

```
class Route extends Model
{

...

  public function adminFields() {
    $fieldOptions = array();
    $fieldOptions['agenda']['type'] = 'relation'; // <- I've choosen an arbitrary name
    $fieldOptions['agenda']['default'] = null;
    $fieldOptions['agenda']['notnull'] = 1;
    $fieldOptions['agenda']['columnDefinition'] = null;
    $fieldOptions['agenda']['comment'] = null;
    $fieldOptions['agenda']['name'] = 'location';
    $fieldOptions['agenda']['oldName'] = 'location';
    $fieldOptions['agenda']['null'] = 'NO';
    $fieldOptions['agenda']['extra'] = null;
    $fieldOptions['agenda']['composite'] = 0;
    $fieldOptions['agenda']['field'] = 'location';
    $fieldOptions['agenda']['key'] = null;

    // $fieldOptions['id']['length'] = null;
    // $fieldOptions['id']['precision'] = 0;
    // $fieldOptions['id']['scale'] = 0;
    // $fieldOptions['id']['fixed'] = 0;
    // $fieldOptions['id']['unsigned'] = 0;
    // $fieldOptions['id']['autoincrement'] = 0;

    return $fieldOptions;
  }
```

I don't know which are necessary, but the ones I did not comment out seemed reasonable to me.

This basically would work, but unfortunately there is a cast to object in Voyager's fieldOptions method in DataType.php, which renders my array useless in the blade rendering template, which is throwing an exception trying to acces an object like an array. If i remove the cast everything works as expected and the BREAD config is showing my extra field 👍 

This would be a tiny patch, but I don't forsee the consequences removing the cast since I don't know the intentions of the adminFields() method. Any hints from the author?

**Comment by michaelmano** [comment] 2017-09-02 02:57
Yeah I'm in love with this project and can't wait for it to mature a bit more. Going to take a look through it more and see if I can contribute in any way.

**Comment by lancepioch** [comment] 2017-09-20 04:45
Labels: possible bug

**Comment by fletch3555** [comment] 2017-09-20 17:44
This is no longer an issue now that 1.0 has been released with a complete rewrite of how relationships are handled

**Closed as completed by fletch3555** 2017-09-20 17:44 UTC
Labels: possible bug
