### ISSUE TITLE
Problem in RTL mode

### ISSUE THREAD

**Issue by vahid-vahid** [thedevdojo/voyager#3242] opened 2018-05-27 15:08 UTC
- Laravel Version: 5.6.1
- Voyager Version: 1.1
- PHP Version:7.1

Hi @marktopper I have a problem
in RTL mode, the user drop down menu does not work
Thank you for your great package

**Comment by emptynick** [comment] 2018-05-27 15:13
This is a duplicate of https://github.com/the-control-group/voyager/issues/3084
There is even a PR: https://github.com/the-control-group/voyager/pull/3130

**Closed as completed by emptynick** 2018-05-27 15:13 UTC
Labels: duplicate

**Comment by vahid-vahid** [comment] 2018-05-27 15:19
Tnx, but why isn't the change applied yet?

**Comment by emptynick** [comment] 2018-05-27 15:29
Because no one approved the changes yet, and no one in the team uses RTL.
So we need someone to try it and confirm its working...you for example ;)

**Comment by vahid-vahid** [comment] 2018-05-28 13:14
It worked for the login drop down

**Comment by vahid-vahid** [comment] 2018-05-28 13:19
![image](https://user-images.githubusercontent.com/18301748/40616192-5a7fd06e-629f-11e8-87f1-95bf28530f45.png)
this is another problem...
I can fix it myself
But i think it's better to mention it in order to be fixed globally...

**Comment by ZaynapElaidy** [comment] 2019-02-04 11:15
@wp-src

**Comment by fnaysee** [comment] 2019-02-04 13:34
Hi, guys i don't use voyager anymore. 
I kept the fork of the pr for more than 2 month but since no one was caring about it I removed that fork and i don't have time to recreate that.
I don't have problem if someone else can reproduce the pr.

Just one thing that you guys must know (my opinion):
Things like voyager at first looks like are helping you alot but when you look at the project deeply you see most of the times you need to modify what is provided and it is hard to modify them, because some times there is no way and some times you must study how they have written it. So the question is why may i use it? Is it that hard to create migrations or altering tables or creating login pages  or even creating admin pages(specially times that you care to the admin ux)? I don't think so.
