### ISSUE TITLE
Image field required in Edit mode and Can't delete

### ISSUE THREAD

**Issue by ranjitWBS** [thedevdojo/voyager#3492] opened 2018-08-24 05:58 UTC
## Version information

 - Laravel: v5.6.3
 - Voyager: v1.1.3
 - PHP: 7.2
 - Database: Ver: 15.1 Distrib 10.1.29-MariaDB, for Win32 (AMD64)

## Description

Image field in edit mode still asking for image as a 'required' field.

## Steps To Reproduce
1.Making image fields as 'required' using below JSON 
`{
    "validation": {
        "rule": "required"
    }
}`
works well in add mode.
2. But in edit mode, it is still asking for an image and required field is not removed.

## Expected behavior
It should check if image is already existed and should remove the required field.
Also there should be option to delete the image if no more needed.  

## Screenshots
![issue](https://user-images.githubusercontent.com/19745434/44567501-56e86480-a790-11e8-82ec-e29a6fd51e77.JPG)

**Comment by emptynick** [comment] 2018-12-27 14:13
Closing as a duplicate of https://github.com/the-control-group/voyager/issues/3358

**Closed as completed by emptynick** 2018-12-27 14:13 UTC
Labels: duplicate
