### ISSUE TITLE
Cant edit database due to Enum Type

### ISSUE THREAD

**Issue by Taerarenai** [thedevdojo/voyager#3137] opened 2018-05-05 12:52 UTC
- Laravel Version: 5.6
- Voyager Version: 1.1.1
- PHP Version: 7.1
- Database Driver & Version: 10.1.31 MariaDB

### Description:
Well title pretty much sums it up. The Enum type not supported issue is rendering the whole database editing feature useless. You cant add anything to it or edit existing ones without changing the ENUM from status (cant update if its enum) which will probably break the publish,draft etc.

### Steps To Reproduce:

Tools -> Database -> edit posts -> edit whatever (excepting status enum) or add -> fail error. 

I know its been posted already, however the issue is rather old and i cant seem to find a workaround (new to laravel and voyager so bear with me).

**Comment by brazitech** [comment] 2018-06-10 18:42
same here... i whis this would be resolved... can status be anything else other than ENUM...?

**Comment by marijnz0r** [comment] 2018-06-11 10:19
The workaround is as follows:

- Go to the bread editor
- Go to the column you wish to edit
- Choose input type Select dropdown
- Pick your display name
- In the optional details column:
```
{
    "default": "key-<#>",
    "options": {
        "key-1": "value-1",
        "key-2": "value-2",
        "key-3": "value-3"
    }
}
```
Of course this isn't ideal. If you've got the time, please help out by creating a pull request to fix it.
If working with this issue in testing and acceptance environments as well. I would be grateful if someone finds time to fix this before I'm deploying my application to production.

**Comment by emptynick** [comment] 2018-12-03 17:38
Closing as a duplicate of https://github.com/the-control-group/voyager/issues/1923

**Closed as completed by emptynick** 2018-12-03 17:38 UTC
Labels: duplicate
