### ISSUE TITLE
posts table doesn't exist!

### ISSUE THREAD

**Issue by GaalexxC** [thedevdojo/voyager#3180] opened 2018-05-14 09:07 UTC
- Laravel Version: v5.6.21
- Voyager Version: v1.1.1
- PHP Version: 7.2.3
- Database Driver & Version: MySQL 5.7

### Description:
ErrorException (E_ERROR)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'esweb.posts' doesn't exist (SQL: select count(*) as aggregate from `posts`) (View: /.../public_html/vendor/tcg/voyager/resources/views/dimmers.blade.php) (View: /.../public_html/vendor/tcg/voyager/resources/views/dimmers.blade.php)

### Steps To Reproduce:
Fresh install, followed all steps in documentation, no errors in console everything installed perfectly. Logged into admin and got this error. Checked the repo and the package and there is no migration at all for a posts table even here at Github. Doesn't exist!

![migrate1](https://user-images.githubusercontent.com/28851458/39988059-68298b90-5734-11e8-885a-026ec872bb4d.PNG)
![migrate2](https://user-images.githubusercontent.com/28851458/39988060-683ac27a-5734-11e8-90ea-604539aaf7b6.PNG)

**Comment by GaalexxC** [comment] 2018-05-14 09:11
Ok I see the tables are in the dummy data installs which I passed on. That makes no sense if you choose to not do the dummy data those tables are not installed. That needs to be fixed, All tables should be installed/created whether dummy or no data is installed, IE Pages, Posts, Categories, Nullable fields migrations.

**Comment by emptynick** [comment] 2018-05-14 09:13
Can you show us your `config/voyager.php` contents?
Especially the `widgets` part?

**Comment by GaalexxC** [comment] 2018-05-14 09:16
As published on install, untouched

```
<?php

return [
    /*
    |--------------------------------------------------------------------------
    | User config
    |--------------------------------------------------------------------------
    |
    | Here you can specify voyager user configs
    |
    */

    'user' => [
        'add_default_role_on_register' => true,
        'default_role'                 => 'user',
        'namespace'                    => App\User::class,
        'default_avatar'               => 'users/default.png',
        'redirect'                     => '/admin',
    ],

    /*
    |--------------------------------------------------------------------------
    | Controllers config
    |--------------------------------------------------------------------------
    |
    | Here you can specify voyager controller settings
    |
    */

    'controllers' => [
        'namespace' => 'TCG\\Voyager\\Http\\Controllers',
    ],

    /*
    |--------------------------------------------------------------------------
    | Models config
    |--------------------------------------------------------------------------
    |
    | Here you can specify default model namespace when creating BREAD.
    | Must include trailing backslashes. If not defined the default application
    | namespace will be used.
    |
    */

    'models' => [
        //'namespace' => 'App\\',
    ],

    /*
    |--------------------------------------------------------------------------
    | Path to the Voyager Assets
    |--------------------------------------------------------------------------
    |
    | Here you can specify the location of the voyager assets path
    |
    */

    'assets_path' => '/vendor/tcg/voyager/assets',

    /*
    |--------------------------------------------------------------------------
    | Storage Config
    |--------------------------------------------------------------------------
    |
    | Here you can specify attributes related to your application file system
    |
    */

    'storage' => [
        'disk' => 'public',
    ],

    /*
    |--------------------------------------------------------------------------
    | Media Manager
    |--------------------------------------------------------------------------
    |
    | Here you can specify if media manager can show hidden files like(.gitignore)
    |
    */

    'hidden_files' => false,

    /*
    |--------------------------------------------------------------------------
    | Database Config
    |--------------------------------------------------------------------------
    |
    | Here you can specify voyager database settings
    |
    */

    'database' => [
        'tables' => [
            'hidden' => ['migrations', 'data_rows', 'data_types', 'menu_items', 'password_resets', 'permission_role', 'settings'],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Multilingual configuration
    |--------------------------------------------------------------------------
    |
    | Here you can specify if you want Voyager to ship with support for
    | multilingual and what locales are enabled.
    |
    */

    'multilingual' => [
        /*
         * Set whether or not the multilingual is supported by the BREAD input.
         */
        'enabled' => false,

        /*
         * Set whether or not the admin layout default is RTL.
         */
        'rtl' => false,

        /*
         * Select default language
         */
        'default' => 'en',

        /*
         * Select languages that are supported.
         */
        'locales' => [
            'en',
            //'pt',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Dashboard config
    |--------------------------------------------------------------------------
    |
    | Here you can modify some aspects of your dashboard
    |
    */

    'dashboard' => [
        // Add custom list items to navbar's dropdown
        'navbar_items' => [
            'Profile' => [
                'route'      => 'voyager.profile',
                'classes'    => 'class-full-of-rum',
                'icon_class' => 'voyager-person',
            ],
            'Home' => [
                'route'        => '/',
                'icon_class'   => 'voyager-home',
                'target_blank' => true,
            ],
            'Logout' => [
                'route'      => 'voyager.logout',
                'icon_class' => 'voyager-power',
            ],
        ],

        'widgets' => [

        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Automatic Procedures
    |--------------------------------------------------------------------------
    |
    | When a change happens on Voyager, we can automate some routines.
    |
    */

    'bread' => [
        // When a BREAD is added, create the Menu item using the BREAD properties.
        'add_menu_item' => true,

        // which menu add item to
        'default_menu' => 'admin',

        // When a BREAD is added, create the related Permission.
        'add_permission' => true,

        // which role add premissions to
        'default_role' => 'admin',
    ],

    /*
    |--------------------------------------------------------------------------
    | UI Generic Config
    |--------------------------------------------------------------------------
    |
    | Here you change some of the Voyager UI settings.
    |
    */

    'primary_color' => '#22A7F0',

    'show_dev_tips' => true, // Show development tip "How To Use:" in Menu and Settings

    // Here you can specify additional assets you would like to be included in the master.blade
    'additional_css' => [
        //'css/custom.css',
    ],

    'additional_js' => [
        //'js/custom.js',
    ],

    'googlemaps' => [
         'key'    => env('GOOGLE_MAPS_KEY', ''),
         'center' => [
             'lat' => env('GOOGLE_MAPS_DEFAULT_CENTER_LAT', '32.715738'),
             'lng' => env('GOOGLE_MAPS_DEFAULT_CENTER_LNG', '-117.161084'),
         ],
         'zoom' => env('GOOGLE_MAPS_DEFAULT_ZOOM', 11),
     ],

];
```

**Comment by GaalexxC** [comment] 2018-05-14 09:39
I manually migrated those missing 4 tables, they were successfully added to the database. Now I am getting this error which has already been reported.
[Route [voyager.posts.index] not defined. #3161  ](https://github.com/the-control-group/voyager/issues/3161)

**Comment by emptynick** [comment] 2018-05-14 09:47
I tried the following just now:
```
laravel new whatever
composer require tcg/voyager
php artisan voyager:install
php artisan voyager:admin your@email.com --create ...
```
And its working flawlessly.
When you say `fresh` does it mean you had never installed voyager in that server-environment, you dropped the whole `root` directory + database?
Or just "uninstalled" Voyager + dropped tables?
Because the Widgets only register when they are in the config, but configs _may_ be cached.

Migrating the tables is not enough, theres a lot more work done when installing dummy-data.

**Comment by GaalexxC** [comment] 2018-05-14 09:53
I used the exact same steps you just posted, after --create was prompted for user/pass, all went well. I tried accessing the admin panel thats when the error came. Yeah, I realize now just migrating the tables isn't enough. Fresh install meaning first time/clean environment - started with a fresh Laravel install. Laravel right to Voyager and nothing in between. I am going to try it again now and see what I get but I am pretty sure it was flawless first time.

**Comment by emptynick** [comment] 2018-05-14 09:58
I just had the same error.
I had a fresh installation with dummy data (few days old).
To duplicate your problem I created a new folder (steps above) changed my server-root there. (Working fine without dummy data)
Now I switched back to the old install which expects dummy-data and its tables.
Removing the widgets from `~root/config/voyager.php` solved it.

What I wanna say with it is that the config-file throws this error if there are dummy-widgets, nothing else will throw this exception.

It would be interesting to see what this:
`dd(config('voyager.dashboard.widgets'));`
will show when you still get this problem

**Comment by GaalexxC** [comment] 2018-05-14 10:29
Virgin install, empty directory except for composer.phar

![newinstall1](https://user-images.githubusercontent.com/28851458/39991840-d670f2b4-573e-11e8-81fb-0d3ba25ebb7b.PNG)

`php composer.phar create-project laravel/laravel esweb`

`php composer.phar require tcg/voyager`

Updated .env with DB info and App Url

No Dummy install

`php artisan voyager:install`

New Admin

`php artisan voyager:admin my@email.com --create`

Database with new admin I added, all good.

![newinstall3](https://user-images.githubusercontent.com/28851458/39992116-b9366804-573f-11e8-9249-a10170320227.PNG)

Access /admin
![newinstall2](https://user-images.githubusercontent.com/28851458/39991859-e5c94dd8-573e-11e8-9717-b7e7520a5013.PNG)

Same error, absolutely no exceptions during install from start to finish everything perfect. I have nothing under my widgets in config/voyager.php so that didn't make a difference. Lol, I hate when these things happen.

**Comment by GaalexxC** [comment] 2018-05-14 10:42
Hilarious! Did what you did and moved everything into a newly created directory, updated root path, and viola! it worked. Thats odd, anyway have a few errors to fix like the storage sym link as I have changed the directory. Maybe just doing the dummy data is best cause I want the install in my root directory.

**Comment by emptynick** [comment] 2018-05-14 10:48
Thats why it would be interesting to see what `dd(config('voyager.dashboard.widgets'));` prints.
Just place it in a route:
```
Route::get('/', function () {
    dd(config('voyager.dashboard.widgets'));
});
```
Of course on the installation which isnt working.
For the sake, run `php artisan cache:clear` and `php artisan config:clear`

**Comment by GaalexxC** [comment] 2018-05-14 10:51
I moved everything back to root and works fine now without doing anything else. I ran cache / config clear. Its all working now. Very strange behavior, moving it back and forth fixes it go figure. One for you guys to deal with I have wasted enough time, need to move on. Thanks so much for the help Nick. If I do come across the whys of it will let you guys know.

**Comment by emptynick** [comment] 2018-05-31 14:30
Closing this for now.
Let us know if you found out the reason.

**Closed as completed by emptynick** 2018-05-31 14:30 UTC

**Comment by Hiroki111** [comment] 2018-08-02 21:29
![posts](https://user-images.githubusercontent.com/9676341/43612130-b81a0efa-96ee-11e8-8b64-242d256a157c.png)
I'm reporting the same error.

With `php artisan voyager:install`, there won't be the `posts` table.
I've used Voyager 3 times before, but there wasn't such an issue.
(This means that just running 'php artisan voyager:install' produced all the tables properly)

**PS**
composer create-project --prefer-dist laravel/laravel test
cd test/
composer require tcg/voyager
sudo chmod -R 777 storage/ (I usually don't want to do this, but did it for experimentation)
php artisan voyager:install --with-dummy

Confirmed that this produced posts, pages and categories.

**Comment by emptynick** [comment] 2018-08-02 22:10
Thats not an error.
You didn't install `--with-dummy`.
Only with this flag you will get posts/pages and categories.
This has been like this for years now and is completely wanted behaviour.
Also this is mentioned in our readme

**Comment by Braindea7** [comment] 2018-09-12 11:56
Hey there,

I use Voyager for the first time. I installed it today and wondered about the missing posts/pages/categories.  There isn't any note in the docu that you have to install voyager with dummy-data to get this features from the beginning. Very frustrating, because I had to invest nearly an hour to find this issue and a solution for the missing "features". May you could add a note in your docu at the install part, please? 
But until now this is the only problem I had with this very nice project <3

**Comment by emptynick** [comment] 2018-09-12 18:23
Did you read thr Readme? In my eyes it's well described there
