### ISSUE TITLE
[BUG] User role is null sometimes

### ISSUE THREAD

**Issue by alkhachatryan** [thedevdojo/voyager#3962] opened 2019-02-20 18:14 UTC
## Version information
 - Laravel: v5.7.*
 - Voyager: v1.1.11
 - PHP: 7.2
 - Database: PostgreSQL 9

## Description
I installed the voyager on ready project where I have +800K records. The problem of the installation is: when I browse dashboard or users everything is ok. But when I go to Database I get the error.

Sometimes user role is null. When you open the Database page, this function works multiple times, as I understood - 2 times. When it's the first call, the user role is normal Role object, but when it's the second call, user role is null.

## Steps To Reproduce
1. Install the Voyager on ready project with multiple not empty tables (maybe this is the problem)
2. Go to Database
3. See error

## Expected behavior
I excepted to see the page of database. To do it, I wrote a code, which is checking, if $this-role is null - get the role of current logged in user.

## Screenshots
![image](https://user-images.githubusercontent.com/22774727/53113649-815a8500-355b-11e9-8963-987b97c10c0b.png)

## Additional context
Again. See the screenshot. If  you run this code, you will get an error, but if you uncomment the code everything will be ok. So I think you have to implement this code into your core and make a new release, or tell us how we can override this function, so we can do it in our source, not in vendor. 

Thanks

**Comment by emptynick** [comment] 2019-02-20 18:19
You use the Trait in your model, so you can just duplicate it to your namespace and include it instead of voyagers.

**Comment by alkhachatryan** [comment] 2019-02-20 18:34
Will it hurt the installation of the voyager on new machines?

**Comment by alkhachatryan** [comment] 2019-02-20 18:34
And as I understood, you will not fix it in new release?

**Comment by alkhachatryan** [comment] 2019-02-20 18:34
I'll do a PR now

**Comment by emptynick** [comment] 2019-02-20 18:36
I dont know what the issue is.
Effectively your workaround is the same as calling `$this->load('role')` again.
But to really fix this issue, we'd need to find out why its not loading the relationship at all, which is not easy because I can't replicate the issue (you are the first to report this)

**Comment by alkhachatryan** [comment] 2019-02-20 18:51
https://github.com/the-control-group/voyager/pull/3963

**Comment by emptynick** [comment] 2019-06-01 12:30
Closing as the PR was closed aswell.

**Closed as completed by emptynick** 2019-06-01 12:30 UTC
