### ISSUE TITLE
Calendar wont Show

### ISSUE THREAD

**Issue by nunomsh** [thedevdojo/voyager#1954] opened 2017-10-07 18:22 UTC
- Laravel Version: 5.5.14
- Voyager Version: 1.0.5
- PHP Version: 7.1.0
- Database Driver & Version:

### Description:
Calendar wont show. Not certain if the calendar was removed, but worked fine in previous voyager versions, and I'm using it since 0.11.2
Also a strange error apears in console, I'm not certain if as something to do with this:
```
Uncaught TypeError: Cannot read property 'addClass' of undefined
    at o.init (app.js:77)
    at new o (app.js:77)
    at HTMLInputElement.<anonymous> (app.js:77)
    at Function.each (app.js:14)
    at ye.fn.init.each (app.js:14)
    at ye.fn.init.e.fn.datetimepicker (app.js:77)
    at HTMLDocument.<anonymous> (app.js:24)
    at c (app.js:24)
    at u (app.js:24)
```
### Steps To Reproduce:
Create a table
Fields type as date, datetime or timestamp
When creating a new record or edit, the calendar wont show

**Comment by DODMax** [comment] 2017-10-10 14:55
Probably a duplicate of https://github.com/the-control-group/voyager/issues/1806

**Comment by fletch3555** [comment] 2017-10-11 01:35
Agreed @DODMax

**Closed as completed** 2017-10-11 01:36 UTC
Labels: duplicate
