### ISSUE TITLE
New voyager installation, database in admin page

### ISSUE THREAD

**Issue by FaizRA** [thedevdojo/voyager#4588] opened 2019-11-28 05:02 UTC
- Laravel: v6
 - Voyager: v1.3
 - PHP: 7.3.11
 - Database: [Mysql] [5.7] 

## Description

I just installed voyager on my new laravel project. i login. then i try to open database menu. then error occured

Missing required parameters for [Route: voyager.bread.delete] [URI: admin/bread/{id}]. (View: C:\xampp\htdocs\appbaru\vendor\tcg\voyager\resources\views\tools\database\index.blade.php)

## Steps To Reproduce
1. Install Laravel
2. Install Voyager
3. Login
4. Click on 'Database' menu
5. See error

## Expected behavior
I want to open Database Page to create new table

## Screenshots
![image](https://user-images.githubusercontent.com/24287589/69777433-dc986280-11d2-11ea-985f-64f61ec907a1.png)

**Comment by MrCrayon** [comment] 2019-11-28 05:11
Please search before opening an issue, you also have to provide full versions Laravel: v6.6.0
Duplicate of #4586

**Comment by pakistanimoon** [comment] 2019-11-28 06:27
Error and solution already  posted https://github.com/the-control-group/voyager/issues/4586

**Closed as completed** 2019-11-28 07:36 UTC
Labels: duplicate
