### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by abnorouzi** [thedevdojo/voyager#3932] opened 2019-02-02 22:19 UTC
## Version information

 - Laravel: v#.#.#
 - Voyager: v#.#.#
 - PHP: #.#
 - Database: [type] [version] (e.g. MySQL 8.0)

## Additional context
after set voyager to rtl my profile buttom including profile and home and log out dont work

**Comment by emptynick** [comment] 2019-02-02 23:16
Please search before opening new issues and use the issue-template.
Closing as a duplicate of #3084 which was fixed in #3754 and merged into 1.x

**Closed as completed** 2019-02-02 23:16 UTC
Labels: duplicate
