### ISSUE TITLE
Is it possible to make each admin have their own dashboard instead of having one dashboard shared across users

### ISSUE THREAD

**Issue by AlexFoster009** [thedevdojo/voyager#3062] opened 2018-04-25 03:57 UTC
- Laravel Version: #.#.#
- Voyager Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
I am curious if there is a way to make each admin have their own dashboard where they can add users instead of having one main admin managing all of the users. if so, how would this be implemented? if this isnt ok to put on here i apologies just didnt see support

**Comment by MrCrayon** [comment] 2018-04-25 04:44
There is a slack group for voyager related questions, I'm on mobile right now but if you do a search you can probably find the address. 

As per your question you can simply override dashboard view, that I think is index.

**Comment by Braiani** [comment] 2018-04-27 00:48
It looks like you want a CMS, right? If that's what you want, Voyager won't help you. Voyager is not a CMS.

**Comment by AlexFoster009** [comment] 2018-04-27 14:57
Not a cms I just want a back end area for each subscribed user to manage their own team members and their team members work.

A cms would entail exactly what I don't want to do that being have one admin managing every user in the app

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by emptynick** [comment] 2019-07-28 21:14
Duplicate of https://github.com/the-control-group/voyager/issues/1747

**Closed as completed by emptynick** 2019-07-28 21:14 UTC
Labels: duplicate
