### ISSUE TITLE
Sort / order by not working on relations

### ISSUE THREAD

**Issue by Stehos** [thedevdojo/voyager#5119] opened 2020-10-21 11:29 UTC
Hi guys, 
while the server side is ON and the user is in "browse" mode on the specific bread, sorting and ordering is working only for all static columns. It's not working for any of the relation columns. I tried it also with dummy users' data.

Do you have any idea?

```
        $dataRow = $this->dataRow($dataType, 'id');
        if (!$dataRow->exists) {
            $dataRow->fill([
                'type'         => 'number',
                'display_name' => __('voyager::seeders.data_rows.id'),
                'required'     => 1,
                'browse'       => 0,
                'read'         => 0,
                'edit'         => 0,
                'add'          => 0,
                'delete'       => 0,
                'order'        => 1,
            ])->save();
        }

        $dataRow = $this->dataRow($dataType, 'name');
        if (!$dataRow->exists) {
            $dataRow->fill([
                'type'         => 'text',
                'display_name' => __('voyager::seeders.data_rows.title'),
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'order'        => 2,
            ])->save();
        }

        $dataRow = $this->dataRow($dataType, 'parent_id');
        if (!$dataRow->exists) {
            $dataRow->fill([
                'type'         => 'number',
                'display_name' => __('voyager::seeders.data_rows.parent'),
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 1,
                'order'        => 3,
            ])->save();
        }

        $dataRow = $this->dataRow($dataType, 'category_belongsto_parent_relationship');
        if (!$dataRow->exists) {
            $dataRow->fill([
                'type'         => 'relationship',
                'display_name' => __('voyager::seeders.data_rows.parent'),
                'required'     => 1,
                'browse'       => 1,
                'read'         => 1,
                'edit'         => 1,
                'add'          => 1,
                'delete'       => 0,
                'details'      => [
                    'model'       => 'App\\Category',
                    'table'       => 'categories',
                    'type'        => 'belongsTo',
                    'column'      => 'parent_id',
                    'key'         => 'id',
                    'label'       => 'name',
                    'pivot_table' => 'categories',
                    'pivot'       => 0,
                ],
                'order'        => 4,
            ])->save();
        }
```

**Comment by emptynick** [comment] 2020-10-21 11:55
Please search before opening new issues.
Duplicate of https://github.com/the-control-group/voyager/issues/2661
Also, the issue template is not optional.

**Closed as completed by emptynick** 2020-10-21 11:55 UTC
Labels: duplicate
