### ISSUE TITLE
Rendered JSON after edit table

### ISSUE THREAD

**Issue by AdrianKuriata** [thedevdojo/voyager#1077] opened 2017-04-06 15:59 UTC
- Laravel Version: 5.4.15
- Voyager Version: 0.11.8
- PHP Version: PHP 7.1.0-2
- Database Driver & Version: MySQL 5.7.16-0ubuntu0.16.04.1

### Description:
Hi, i think it should not working like that. I mean if you get into Databases and you click EDIT on some table you have breadcrumb something like that: Dashboard  > Database  > Categories > Edit

If you click on Categories you can see all tables and his fields in JSON structure.

Here is a pic: [http://i.imgur.com/t8KrNFX.png](http://i.imgur.com/t8KrNFX.png)

**Comment by davodavodavo3** [comment] 2017-04-06 16:20
Yes there is an issue there. But i dont see JSON structure i get only http exeption that method not allowed

**Comment by fletch3555** [comment] 2017-08-31 19:28
I've been unable to reproduce this across multiple Voyager versions, so I'm going to close this for now.  If it's still an issue following the 1.0 release, please open a new issue

**Closed as completed by fletch3555** 2017-08-31 19:28 UTC
