### ISSUE TITLE
Post body shows the same value for different languages in Admin

### ISSUE THREAD

**Issue by sahibhuseyn** [thedevdojo/voyager#3228] opened 2018-05-24 10:29 UTC
- Laravel Version: 5.6
- Voyager Version: 1.1
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:
 I tried to use multi-language function of Voyager for my project. Everything went good till I wanted to change Post body for different languages.
I got "Undefined index 'en' (or other languages code)". But I tried to change my post body by hard way, and I have edited post body from database. And the result is unbelievable, because when I am in posts lists it shows me result what I changed on database, but when try to edit my post and try to change languages from selection, the post title changed when switched different languages but post body show the same result  
I added here my screencast
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17153730/40480198-ca5be63c-5f5e-11e8-83f2-cb2db71b3299.gif)

**Comment by emptynick** [comment] 2018-05-24 10:47
I just wanted to answer on Slack.
Please search before opening a new issue.
Duplicate of #3181, #3187, #3196 and #3089
Possible fix in #3115

**Closed as completed by emptynick** 2018-05-24 10:47 UTC
Labels: duplicate

**Comment by sahibhuseyn** [comment] 2018-05-24 10:54
I have read and checked all of them, but neither of them works for me
