### ISSUE TITLE
media browser in posts and pages

### ISSUE THREAD

**Issue by jouniikaheimo** [thedevdojo/voyager#2242] opened 2017-11-16 10:41 UTC
- Laravel Version: 5.5
- Voyager Version: 1.0.7
- PHP Version: 7
- Database Driver & Version: mysql

### Description:
How i can add media browser and crop tool in posts or if this is prossible

**Comment by emptynick** [comment] 2018-12-27 23:11
Closing as a duplicate of https://github.com/the-control-group/voyager/issues/1877

**Closed as completed by emptynick** 2018-12-27 23:11 UTC
Labels: duplicate
