### ISSUE TITLE
[BUG] belongsToMany "Allow Tagging" can't create new tags

### ISSUE THREAD

**Issue by wishbone-productions** [thedevdojo/voyager#4039] opened 2019-03-26 15:00 UTC
## Version information
 - Laravel: 5.8.*
 - Voyager: 1.2.*
 - PHP: 7.1.7
 - Database: Maria DB 10.1.25

## Description
When creating a new belongsToMany relationship with "allow taggable" option. Its not possible to create new tags and use them.  The tagging itself works if the tags are already created.

## Steps To Reproduce
1) Create belongsToMany relationships
2) Edit entity, go to tag field
3) Try create new tag.
4) The POST request is sent and the tag itself is created. 
5) The POST returns a list view but not the JSON data needed to create the tag
6) The ajax function is not properly designed to receive JSON data

## Expected behavior
Data is not returning json and is not handled properly

## Hacks to make it work:
Could use something more neat but i`m fairly new to laravel / voyager

JS vendor\tcg\voyager\resources\assets\js\app.js line 102
(insert json parse function)
```
$.post(route, {
	[label]: e.params.args.data.text,
}).done(function(data) {
	data = JSON.parse(data);
	var newOption = new Option(e.params.args.data.text, data.id, false, true);
	$el.append(newOption).trigger('change');
}).fail(function(error) {
	toastr.error(errorMessage);
});
```
PHP code in the Model of the tag
Let the model return the json data on creation
```
public static function boot()
{
	parent::boot();

	self::created(function($model){
		echo json_encode($model);
		exit;
	});
}
```

**Comment by G00sfraba** [comment] 2019-06-18 19:14
I can still reproduce this in 1.2.6.
Also when you start typing in "taggable" field it looses focus after typing 2 characters. No errors or 404 thrown in console.

If you still manage to click on the new tag it throws this error in the console:
![изображение](https://user-images.githubusercontent.com/1669800/59713678-a369c880-9218-11e9-8dd1-a87f42a933a0.png)

**Comment by gavinj1999** [comment] 2019-07-01 15:21
Any progress on this please?

**Comment by GnilitskyWeb** [comment] 2019-07-05 15:53
> Also when you start typing in "taggable" field it looses focus after typing 2 characters. No errors or 404 thrown in console.

This is a bug in select2 on 4.0.3 version
https://github.com/select2/select2/issues/4525#issuecomment-317741989

**Comment by shafiqkr18** [comment] 2019-07-07 05:50
I have added js code in line 102 & also added Model function, but it is still not working. Also i think it is not good idea to edit app.json. Does anyone fixed this issue?

**Comment by winex01** [comment] 2019-07-26 14:39
had the same issue

**Comment by ClaryPollack** [comment] 2019-07-26 23:07
Just installed Voyager for the first time and all I can say is wow! Am also curious about the tagging feature, however. Will work on it and will let you know what happens :)

**Comment by royercross** [comment] 2019-08-15 04:05
As @GnilitskyWeb said it seems to be a bug on Select 2, reverting to version 4.0.2 will probably fix this. any one got a temporal fix?

**Comment by shafiqkr18** [comment] 2019-08-15 09:36
Is anyone solved this issue? BTW, how to revert select2 to 4.0.2?

**Comment by G00sfraba** [comment] 2019-08-15 14:16
I had to revert the whole Laravel + Voyager version back one level. For me it was crucial to get the Tag working as the whole app revolved around it.

**Comment by royercross** [comment] 2019-08-15 14:45
I was trying to rebuild the Voyager project but it just keep getting this error... 

npm WARN bootstrap-switch@3.4.0 requires a peer of bootstrap@^4.3.1 but none is installed. You must install peer dependencies yourself.

any ideas?

**Comment by iamriajul** [comment] 2019-09-08 15:27
> I had to revert the whole Laravel + Voyager version back one level. For me it was crucial to get the Tag working as the whole app revolved around it.

How did you solve it? which versions are you using?

**Comment by G00sfraba** [comment] 2019-09-08 16:24
"laravel/framework": "5.7.*",
"tcg/voyager": "1.1.12",

For me it is not crucial to have all the latest, allthough it would be nice to be able to.

**Comment by emptynick** [comment] 2019-09-08 16:57
Did you guys test with 1.2.7?
Select2 was updated to 4.0.10, but I'm not really sure if they fixed it.
Version 4.0.8 says something about focusing behaviour introduced in 4.0.6.
And 4.0.4 says something about focus as well.

Edit: found the problem. Fixed it in my fork already.

**Comment by emptynick** [comment] 2019-09-08 21:44
Fixed in https://github.com/the-control-group/voyager/pull/4397 (merged into 1.x)

**Closed as completed by emptynick** 2019-09-08 21:44 UTC
Labels: possible bug
