### ISSUE TITLE
Error when click breadcrumb of BREAD edit page

### ISSUE THREAD

**Issue by overcome** [thedevdojo/voyager#3484] opened 2018-08-23 04:16 UTC
## Version information

 - Laravel: v5.5
 - Voyager: v1.1
 - PHP: 7.1.0
 - Database: [mysql] [5.7.16] 

## Description

Error will display when click "Pages" in breadcrumb of BREAD edit page.

## Steps To Reproduce
1. Login to admin backend.
2. Go to 'Tools' -> 'BREAD'.
3. Click on 'Pages' in breadcrumb of Edit 'Pages'
'Symfony \ Component \ HttpKernel \ Exception \ MethodNotAllowedHttpException
No message'

## Expected behavior
No error display

## Screenshots
1. Click here
![laravel-voyager-bug-01](https://user-images.githubusercontent.com/1227674/44504305-d8c38980-a6cd-11e8-96da-d71407b19160.jpg)

After click it will show error.

**Comment by emptynick** [comment] 2018-08-23 10:26
This looks like a duplicate of https://github.com/the-control-group/voyager/issues/3434

**Closed as completed by emptynick** 2018-08-23 10:26 UTC
Labels: duplicate
