### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by yogesh-jgu** [thedevdojo/voyager#5533] opened 2022-02-16 08:13 UTC
### Laravel version

Laravel 9

### PHP version

PHP 8

### Description of problem

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - tcg/voyager[v1.5.0, ..., 1.x-dev] require illuminate/support ~6.0|~7.0|~8.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires tcg/voyager ^1.5 -> satisfiable by tcg/voyager[v1.5.0, ..., 1.x-dev].

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### Proposed solution

Laravel 9 version support

**Comment by emptynick** [comment] 2022-02-16 08:15
Please search before opening new issues.
Duplicate of https://github.com/the-control-group/voyager/issues/5523

**Closed as completed by emptynick** 2022-02-16 08:15 UTC
Labels: duplicate
