### ISSUE TITLE
permissions not removed when table is removed

### ISSUE THREAD

**Issue by stevenhillsr** [thedevdojo/voyager#2657] opened 2018-02-13 14:24 UTC
- Laravel Version: 5.4
- Voyager Version: 1.0
- PHP Version: 7.1
- Database Driver & Version: mysql (current Homestead version)

Description: Basically just that. I have removed a table but when I go to Roles and edit permissions that table is still there to allow me to set permissions on.

Steps To Reproduce: Add a table and select the option to set permissions. The delete the table.

**Comment by fletch3555** [comment] 2018-02-13 15:18
This is being resolved in a newer release.  I can't promise it'll be resolved in 1.0.*, but will definitely be fixed for 1.1

**Comment by Braiani** [comment] 2018-06-19 05:42
Hey @fletch3555 I just tested and it seems to be solved on 1.1.*.
Maybe it should be marked as closed!

**Comment by emptynick** [comment] 2018-06-19 07:07
Are you sure?
The only thing happening when deleting is [this](https://github.com/the-control-group/voyager/blob/1.1/src/Http/Controllers/VoyagerDatabaseController.php#L270) and I dont think the SchemaManager will take care of roles?

**Comment by Braiani** [comment] 2018-06-21 02:54
Yeah.. I'm sure.. I just tested here (again).. See the picts.. (I took pic only on the DB)...
Before delete:
- Permissions table
![permissions table before delete](https://user-images.githubusercontent.com/29052343/41695274-5d9ebe32-74dc-11e8-8c15-1dabbae7628f.png)
- Permission_role table
![permission_role table before delete](https://user-images.githubusercontent.com/29052343/41695272-5cd33eba-74dc-11e8-98cc-d57012fc01b6.png)
After delete:
- Permissions table
![permissions table after delete](https://user-images.githubusercontent.com/29052343/41695273-5d30de62-74dc-11e8-862c-1505da5bd9fb.png)
- Permission_role table
![permission_role table after delete](https://user-images.githubusercontent.com/29052343/41695271-5c6f3c3a-74dc-11e8-9382-1cbb95a38402.png)

**Comment by emptynick** [comment] 2018-11-10 11:54
Just confirmed that deleting a BREAD (which generates the permissions) also deletes them.
https://github.com/the-control-group/voyager/blob/1e3e845745a1ec7406300c1632af56655361c0f7/src/Http/Controllers/VoyagerBreadController.php#L200-L202

**Closed as completed by emptynick** 2018-11-10 11:54 UTC
Labels: type:bug
