### ISSUE TITLE
Deprecation warning for json_decode() for MenutItem model

### ISSUE THREAD

**Issue by marcomertenslv** [thedevdojo/voyager#5737] opened 2023-02-16 12:46 UTC
### Laravel version

9.52.0

### PHP version

8.2.3

### Voyager version

1.6.0

### Database

MySQL 8.0

### Description

json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in ... vendor/tcg/voyager/src/Models/MenuItem.php on line 93

### Steps to reproduce

Setup voyager with Laravel 9, Valet and PHP 8.2. Have a look at tail -f storage/logs/php-deprecation-warnings.log 

### Expected behavior

The log file should contain deprecation warnings

**Comment by guilhermebillig** [comment] 2023-02-21 03:00
Same problem here

**Comment by u01jmg3** [comment] 2023-02-28 14:21
Dupe of #5603

**Closed as completed** 2023-03-01 08:04 UTC
Labels: duplicate
