### ISSUE TITLE
URL problem

### ISSUE THREAD

**Issue by benwood162** [thedevdojo/voyager#5250] opened 2021-03-03 22:17 UTC
Im having a problem with URLs of photos uploaded to the database 
they are uploading with both forward and back slashes 
example: ["pedidos\/03032021222605603ffeedd19e6.jpeg","pedidos\/03032021222605603ffeedd2d2d.jpeg"]
this not a problem when viewing in voyager backend, but when i try call the images on the site 

sorry if this is the wrong place or not enough information, im pretty new to all this, feel free to delete if so, mods

**Comment by MrCrayon** [comment] 2021-03-08 12:51
Please read the issue template when opening an issue an provide information requested.

It could be a duplicate of #5230

**Closed as completed by MrCrayon** 2021-03-08 12:51 UTC
