### ISSUE TITLE
voyager-assets?path=js%2Fapp.js:1 Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by maxillarious** [thedevdojo/voyager#5059] opened 2020-08-30 18:04 UTC
## Version information

 - Laravel: v7.0
 - Voyager: v1.4
 - PHP: 7.2.5
 - Database: [MySQL] [5.7]

## Description

I deployed my Laravel app with Voyager installed to cloudways, I tried accessing Voyager admin panel but it keeps loading and doesn't display any menu but my Laravel app works perfectly.

When i checked the console i saw this:
**LEFT SIDE:** Uncaught SyntaxError: Invalid or unexpected token
**RIGHT SIDE:** voyager-assets?path=js%2Fapp.js:1

**Comment by emptynick** [comment] 2020-08-30 18:08
That's actually the cause of your other issue.
Closing.

**Closed as completed by emptynick** 2020-08-30 18:08 UTC
