### ISSUE TITLE
Support Soft Delete

### ISSUE THREAD

**Issue by Pochwar** [thedevdojo/voyager#1533] opened 2017-08-03 14:22 UTC
- Laravel Version: 5.4
- Voyager Version: 0.11.14
- PHP Version: 7.1
- Database Driver & Version:

### Description:

I use Laravel soft delete for my user model.

So if I want to see all the users, I have to do a query with `->withTrashed()`.
To achieve that in Voyager, I had to override the default controller to add `->withTrashed()` to all the queries concerning users.

As Voyager is my administration panel, I think it would make sense to add `->withTrashed()` to queries by default.

Is there a smart way to do this ? (because overriding controllers for this is painful and it's easy to forget one query)

Or will it be add in Voyager next version ?

Thanks

**Comment by vitormicillo** [comment] 2017-08-28 10:39
We could suggest for the next version of Voyager to view the objects that were deleted with the status of removed with the possibility to activate  :-D

**Comment by lancepioch** [comment] 2017-09-20 02:40
Labels: feature, question

**Comment by karimsynergy** [comment] 2017-12-11 12:18
Hi, some news about that? Im waiting for the same

**Comment by mattrabe** [comment] 2018-11-21 18:21
This appears to be a older duplicate of #2165

**Comment by emptynick** [comment] 2018-11-21 18:35
Closing in favor of #2165

**Closed as completed by emptynick** 2018-11-21 18:36 UTC
Labels: type:question, feature
