### ISSUE TITLE
Menu Builder Broken

### ISSUE THREAD

**Issue by JoshuaBedford** [thedevdojo/voyager#4636] opened 2019-12-17 20:50 UTC
## Version information

 - Laravel: v6.8.0
 - Voyager: v1.3.0
 - PHP: 7.2
 - Database: MySQL 14.14

## Description

I just completed a fresh install of the most recent version of laravel, then did an install with the most recent version of voyager. When I go to the Menus admin panel (/admin/menus), and click on the green 'Builder' button, the following error occurs:

```
Facade\Ignition\Exceptions\ViewException
Missing required parameters for [Route: voyager.menus.item.destroy] [URI: admin/menus/{menu}/item/{id}]. (View: /app/vendor/tcg/voyager/resources/views/menus/builder.blade.php)
http://voyager.lndo.site/admin/menus/2/builder
```

## Steps To Reproduce
1. Go to /admin/menus
2. Click on 'Builder'

## Expected behavior
I expected to be able to see and edit the menu

## Screenshots
<img width="1227" alt="Screen Shot 2019-12-17 at 2 49 37 PM" src="https://user-images.githubusercontent.com/13459258/71033184-78373780-20dc-11ea-9f20-18f2c316f7f9.png">

**Comment by fletch3555** [comment] 2019-12-17 22:55
Please search before opening issues.  Duplicate of #4610 and #4611, same error for a different page on a number of other issues as well.

**Closed as completed by fletch3555** 2019-12-17 22:55 UTC
Labels: duplicate

**Comment by agustinmejia** [comment] 2019-12-20 20:19
in the file /vendor/tcg/voyager/routes/voyager.php at the line 73 write **?** after id like this {id?}

**Comment by fletch3555** [comment] 2019-12-20 20:22
@agustinmejia, please don't recommend that people change files under vendor.  They will be blown away during the next update, which gives the impression that our update broke it, leading to more complex troubleshooting.  This has been fixed and is currently pending the next release.
