### ISSUE TITLE
Remove multi image don't work

### ISSUE THREAD

**Issue by KoVaLsKy2010** [thedevdojo/voyager#4576] opened 2019-11-23 18:53 UTC
## Version information

 - Laravel: v5.8.35
 - Voyager: v1.3.0
 - PHP: 7.2
 - Database: PostgreSQL

## Description

Remove button of multi images don't work

## Steps To Reproduce
1. Create a multi_images field in posts table, type text or json or jsonb
2. In admin/bread/posts/edit select "multiple_images" type for multi_images
3. Add post and add any images in multiple
4. When I whan to delete some image, I see 400 Error

There no image name or some information of removed image in post request 

## Screenshots
![ScreenShsdfadafot](https://user-images.githubusercontent.com/9406736/69483683-61822580-0e3b-11ea-96d3-0c9c2dc039cd.png)

**Comment by MrCrayon** [comment] 2019-11-24 01:12
I think your problem is with CORS configuration, check in response or preview tab what full error says.

**Comment by KoVaLsKy2010** [comment] 2019-11-25 09:45
![ScreendafdsfadsfasdfShot](https://user-images.githubusercontent.com/9406736/69529499-710b8680-0f81-11ea-97e2-74a2aebf4cb3.png)

`File does not exist`

> I think your problem is with CORS configuration, check in response or preview tab what full error says.

**Comment by MrCrayon** [comment] 2019-11-25 10:47
What's the preview response if you put  `dd($fieldData);` after:
https://github.com/the-control-group/voyager/blob/0306d7348f3dd05a4ea19c66f18bc9986bbe0902/src/Http/Controllers/VoyagerBaseController.php#L566

Also what's the url of the image you are trying to remove?
`dd($filename)`

**Comment by KoVaLsKy2010** [comment] 2019-11-25 11:49
> What's the preview response if you put `dd($fieldData);` after:
> https://github.com/the-control-group/voyager/blob/0306d7348f3dd05a4ea19c66f18bc9986bbe0902/src/Http/Controllers/VoyagerBaseController.php#L566
> 
> Also what's the url of the image you are trying to remove?
> `dd($filename)`

The answer don't changed.
There POST method on click to cross

![Screenываываываhot](https://user-images.githubusercontent.com/9406736/69538095-994fb100-0f92-11ea-9f14-b0e977a50e3a.png)
![ScreenShoфафываыфва](https://user-images.githubusercontent.com/9406736/69538096-994fb100-0f92-11ea-9359-cd6fbf4a1009.png)

**Comment by MrCrayon** [comment] 2019-11-25 11:54
Then the problem is here:
https://github.com/the-control-group/voyager/blob/0306d7348f3dd05a4ea19c66f18bc9986bbe0902/src/Http/Controllers/VoyagerBaseController.php#L553

Try to put a `dd($data)` before that line

**Comment by KoVaLsKy2010** [comment] 2019-11-25 12:04
![ScreenSasdasdasdasdhot](https://user-images.githubusercontent.com/9406736/69539101-dae15b80-0f94-11ea-906e-2ce76390b8fa.png)

**Comment by KoVaLsKy2010** [comment] 2019-11-25 12:07
mb problem in no image name or image id in any POST field? 
There only
```
slug: posts
id: 4
field: multi_images
_token: UFSdKVRGmLPpSW7QrglbuRrBXY7mCg40m9WJ4rmT
```
in request

`$data->{$field}` is empty

**Comment by MrCrayon** [comment] 2019-11-25 12:47
Request for removing multi_image type should look like this:
```
slug: tests
filename: tests/November2019/fdrMuvjL7a5wl3FmK3JD.png
id: 1
field: image
multi: true
_token: s5SQLRgZLP5cfgOuS14NNu80dDV2QzpClt5xq3Ii
```
Did you customize the template?

**Comment by KoVaLsKy2010** [comment] 2019-11-25 13:00
> Request for removing multi_image type should look like this:
> 
> ```
> slug: tests
> filename: tests/November2019/fdrMuvjL7a5wl3FmK3JD.png
> id: 1
> field: image
> multi: true
> _token: s5SQLRgZLP5cfgOuS14NNu80dDV2QzpClt5xq3Ii
> ```
> 
> Did you customize the template?

don't touch

In what HTML element is 
`filename, id, image, multi ` ? 

Is it right
![ScreenShoasdfasdfsadft](https://user-images.githubusercontent.com/9406736/69542492-9bb70880-0f9c-11ea-82d5-19ce5b58a3ec.png)
 element type in bread?

**Comment by MrCrayon** [comment] 2019-11-26 03:12
BREAD Mutliple Images: correct
You can almost see html part in your screenshot:

https://user-images.githubusercontent.com/9406736/69538096-994fb100-0f92-11ea-9359-cd6fbf4a1009.png

HTML looks OK to me (the part I can see) so no idea why some values are not part of your request.

I can't reproduce your problem so 99% is something you changed, with 1% a browser/extension/something else conflict.

I would suggest:

- Try another browser
- Try a fresh Voyager install in another folder, add a multiple images field and check if it works.
- Debug js

https://github.com/the-control-group/voyager/blob/0306d7348f3dd05a4ea19c66f18bc9986bbe0902/resources/views/bread/edit-add.blade.php#L146

**Comment by MrCrayon** [comment] 2019-11-26 03:22
> > Did you customize the template?
>
> don't touch

My bet is you have a custom edit-add template that is older than Voyager v1.1.11 where removing multiple images was implemented #3240

**Comment by KoVaLsKy2010** [comment] 2019-11-26 09:31
> BREAD Mutliple Images: correct
> You can almost see html part in your screenshot:
> 
> https://user-images.githubusercontent.com/9406736/69538096-994fb100-0f92-11ea-9359-cd6fbf4a1009.png
> 
> HTML looks OK to me (the part I can see) so no idea why some values are not part of your request.
> 
> I can't reproduce your problem so 99% is something you changed, with 1% a browser/extension/something else conflict.
> 
> I would suggest:
> 
> * Try another browser
> * Try a fresh Voyager install in another folder, add a multiple images field and check if it works.
> * Debug js
> 
> https://github.com/the-control-group/voyager/blob/0306d7348f3dd05a4ea19c66f18bc9986bbe0902/resources/views/bread/edit-add.blade.php#L146

Problem in data-* field name
![ScreenShasdasdasdasdot](https://user-images.githubusercontent.com/9406736/69617002-98795680-1048-11ea-968c-fa1ccd39abb9.png)
![ScreeasdasdasdasdanShot](https://user-images.githubusercontent.com/9406736/69617004-98795680-1048-11ea-86f9-102a50fa477f.png)
![ScreendfasdfasdfaShot](https://user-images.githubusercontent.com/9406736/69617007-9911ed00-1048-11ea-8a8e-b9c49dac65d6.png)

in Javascript there $`image.data('image')` selector, but in HTML there is only `data-file-name` and post id

**Comment by MrCrayon** [comment] 2019-11-26 11:50
I see the problem, I thought you customized your template but you are using posts that by default use `posts/edit-add` not the usual `bread/edit-add `template.

That template was not updated with #3240.

Untill this is fixed in Voyager you should create:
`resources/views/vendor/voyager/posts/edit-add.blade.php`

Paste in content from:
https://github.com/the-control-group/voyager/blob/1.3/resources/views/posts/edit-add.blade.php

Update it checking:
https://github.com/the-control-group/voyager/blob/1.3/resources/views/bread/edit-add.blade.php

**Comment by KoVaLsKy2010** [comment] 2019-11-26 12:11
Works! Thanks!

**Closed as completed** 2019-12-05 12:00 UTC
Labels: possible bug, addressed
