### ISSUE TITLE
Insert Videos

### ISSUE THREAD

**Issue by bonucci** [thedevdojo/voyager#4018] opened 2019-03-20 11:54 UTC
Insert a video on rich text post from the media manager, i notice that is able to insert youtube videos, but not custom uploaded videos to the media manager.

**Comment by emptynick** [comment] 2019-03-20 12:00
Please use the issue template and search before opening new issues.
Closing as a duplicate of https://github.com/the-control-group/voyager/issues/2234

**Closed as completed by emptynick** 2019-03-20 12:00 UTC
Labels: duplicate
