### ISSUE TITLE
update version from 0.10 to 0.11

### ISSUE THREAD

**Issue by mohamedothman91** [thedevdojo/voyager#942] opened 2017-03-15 12:31 UTC
- Laravel Version: 5.3
- Voyager Version: 0.11.*
- PHP Version: 5.6.30
- Database Driver & Version: 5.6.33

### Description:
after update Version from 0.10 to 0.11
all website pages and admin area has error ErrorException in MenuItem.php line 66:
I followed the steps to update the correct way like docs

https://ibb.co/b2acwF

**Comment by abdgad** [comment] 2017-03-19 13:51
Sorry about the delay to reply. This is a duplicate of #958
Please follow the upgrade guide: https://the-control-group.github.io/voyager/docs/0.11/#getting-started-upgrading

**Closed as completed by abdgad** 2017-03-19 13:51 UTC
