### ISSUE TITLE
UnexpectedValueException Invalid route action: [AnyController].

### ISSUE THREAD

**Issue by Xmk** [thedevdojo/voyager#3623] opened 2018-10-11 18:57 UTC
## Version information

 - Laravel: v5.7.9
 - Voyager: v1.1.7
 - PHP: 7.1.7
 - Database:  Ver 14.14 Distrib 5.7.19, for Win64 (x86_64)

## Description

at the time of adding a new Bread menu item (after create Bread),
error occurs when have is a invoke controller (Single Action Controllers)
## Steps To Reproduce
1. Go to console
2. Create a invoke controller
example `php artisan make:controller IndexController --invokable`
3. Register you controller in router
example `Route::get('/', 'IndexController');`
4. Go to /admin/bread and create new bread for any table (maybe you need create a table),
fill data and press submit
5. Look error.

## Expected behavior
Standart behavior bread creating

## Screenshots
https://screenshots.firefox.com/M6IoFQwFGXF6wYMb/flame.raiders

## Additional context
While looking for what's the problem

**Comment by fletch3555** [comment] 2018-10-12 18:54
This doesn't really seem like a Voyager problem.  Can you provide the code for your `IndexController`? It sounds like it's missing the `__invoke` method

**Comment by Xmk** [comment] 2018-10-12 20:46
controller have base code after `php artisan make:controller IndexController --invokable`
this is test base on clear laravel + voyager

**Comment by Sylk** [comment] 2018-10-15 16:20
@Xmk more details required.

**Comment by shaunthegeek** [comment] 2018-11-19 03:05
I have the same problem. If I use invoke controller, voyager will crash when I create a bread.

code:

```
route/web.php

<?php
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

Route::get('/welcome', 'Welcome');
```

```
app\Http\Controllers\Welcome.php

<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class Welcome extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        return view('welcome');
    }
}
```

![2018-11-19 11-01-51](https://user-images.githubusercontent.com/4971414/48684046-e7491080-ebea-11e8-9572-156441c35aba.png)
![2018-11-19 11-00-51](https://user-images.githubusercontent.com/4971414/48684051-eb752e00-ebea-11e8-90a6-7566b2f86510.png)

**Comment by Xmk** [comment] 2018-11-24 06:11
**I discovered the cause of the problem**

https://github.com/the-control-group/voyager/blob/4b6b3a3f7cf30abc1220c503a12858d41c653486/src/Listeners/AddBreadMenuItem.php#L32
This is incorrect mrthod for require routes!

Just check RouteServiceProvider in Laravel:
https://github.com/laravel/laravel/blob/2a483bbf60566cab6fbd0340fb3877fc09889bc3/app/Providers/RouteServiceProvider.php#L54-L56

`Route::middleware('web')`  - **set group for routes**
`->namespace('App\Http\Controllers')` - **set namespaces for controllers!!!**
`->group(base_path('routes/web.php'));` - **require routes!**

**Comment by Sylk** [comment] 2018-11-30 16:26
@Xmk please close this ticket. Thanks for the updated response champ.

**Comment by mallardduck** [comment] 2019-06-07 15:17
@Sylk The issue is still active so I don't think this should be closed. I'm experiencing the same thing and it's really annoying.

@Xmk Pointed out the issue - but it doesn't seem like it was fixed or addressed yet. Honestly from my local testing it seems like line 32 should just be removed.

https://github.com/the-control-group/voyager/blob/4b6b3a3f7cf30abc1220c503a12858d41c653486/src/Listeners/AddBreadMenuItem.php#L32

It doesn't seem to do anything other than cause this error to be thrown. After removing that line, the Bread creation worked as expected and a Menu item was added.

**Closed as completed** 2019-07-20 07:40 UTC
