### ISSUE TITLE
Have to change field of name for showing menu item in menu.

### ISSUE THREAD

**Issue by miladrezaei-ai** [thedevdojo/voyager#391] opened 2016-12-14 14:12 UTC
- Laravel Version: 5.3
- Voyager Version: 0.10.2
- PHP Version: 7.0.10
- Database Driver & Version:

### Description:
I set the prefix in env file in laravel ( lp_ ). After that, I want to create groups menu item.  I create it in database and menu item but it wont be shown. The field of name in data_type table will be saved as lp_groups and when I change it to groups , it works ... 

I have to go to database and change the lp_groups to groups for showing groups menu item in the menu.

**Comment by wuelcas** [comment] 2017-03-18 18:57
This is exactly what's happening to me. The BREAD functionalities won't work correctly when using a database prefix. This is because of your database manager class, I'll try work on this if I can achieve something

**Comment by abdgad** [comment] 2017-03-18 20:41
@wuelcas can you please explain the issue with BREAD and the database manager?

**Comment by wuelcas** [comment] 2017-03-24 16:11
Ok, I made a fresh installation of laravel and voyager for this.

1. I set a prefix for the database tables called 'voyager_'
![image](https://cloud.githubusercontent.com/assets/2205305/24297877/dea9bfd2-1069-11e7-8e27-45424355902f.png)
2. I installed voyager with dummy data by running the `php artisan voyager:install --with-dummy` command. The voyager tables were created with the prefix I set up earlier, everything is going according to plan
![image](https://cloud.githubusercontent.com/assets/2205305/24298143/bbf1a40e-106a-11e7-8498-ad66422cb623.png)
3. I login into the voyager app and go to Tools -> Database. I see that all the tables are listed with the prefix and not one has a BREAD created (some tables supposed to have a BREAD created). 
![image](https://cloud.githubusercontent.com/assets/2205305/24298510/d22fe2f2-106b-11e7-9236-9791e95ef539.png)


### Why is this happening? 

After digging into the source code I found out that the SchemaManager class (found in tcg\voyager\src\Database\Schema\SchemaManager.php) is the one responsable for listing, creating, deleting, updating and all that stuff for the tables and it works managing the table names with the prefix but... when voyager seed the tables, the data_types table (table used in the BREAD funcionalities) is filled with table name data without the prefix I set up, so in the controller when it tries to match the BREADs, it doesn't match. After digging the attribute of the data_types table that the application tries to match with the table name is `name` (I'm sure you guys know this but just trying to make my point more clearly)

#### data_type table
![image](https://cloud.githubusercontent.com/assets/2205305/24299363/9fac009c-106e-11e7-825c-899adb2de12f.png)

### A solution ????
After find all this, I figure that making a change in the DataTypesTableSeeder class and concatenating the prefix (e.g. `'name' => DB::getTablePrefix().'posts',`) will do the trick to make the BREAD works, and it did. I deleted all the data in the data_type table and seed it all over again with the table prefix and it appears in the database manager, I also seed the data_rows table to update the newly created data types.

![image](https://cloud.githubusercontent.com/assets/2205305/24299959/71a7053c-1070-11e7-91d5-82290337b512.png)
![image](https://cloud.githubusercontent.com/assets/2205305/24299989/855c8a84-1070-11e7-8c97-a2bf5b41f6c7.png)

Everything is working correctly with the dummy data. But let's try to create a new table.

Let's create a table, let's call it 'cars' and let's keep it simple, an id and a name attribute and let's create the model and migration for the table
![image](https://cloud.githubusercontent.com/assets/2205305/24300740/06afb4d8-1073-11e7-9d78-4bea01150f0b.png)

Everything works fine, the table is created but without the prefix, so I need to manually change the table name and add the prefix and from now on if I'm using a prefix I need to add the prefix when I create the table with the database manager.

So I change the name of the table from 'cars' to 'voyager_cars' and I create a BREAD for the table, generating the permissions. No problem. **Important: please look the Input Type values for each row**

![image](https://cloud.githubusercontent.com/assets/2205305/24300979/dca4baac-1073-11e7-9a37-c8c5a33abd87.png)

![image](https://cloud.githubusercontent.com/assets/2205305/24301017/fe6e4284-1073-11e7-9278-26a9abd6b32e.png)

### New bug
I'll try to edit the newly created BREAD for the cars table and the info for the rows is not showing. I you see the images above I set up the Input Type for the two rows to be Number for the id and Text for the name but in both it says Checkbox. 

![image](https://cloud.githubusercontent.com/assets/2205305/24301963/947d9674-1076-11e7-80c1-75603acb95ed.png)

Why? **because the data for the rows were not created in the data_rows table.**

Why?.... I digged into the code again and the responsable to store that data is the storeBread method in the VoyagerDatabaseController.php file. Line 254: `$data = $dataType->updateDataType($request->all(), true)`. So I digged a little more and I go to the updateDataType method in the DataType model. To get the fields of the table you guys do this, line 74: `$fields = $this->fields(array_get($requestData, 'name'));` the value for `array_get($requestData, 'name')` **will be the name of the table with the prefix, this is important for what is lying ahead**. I go to that fields method in the same file and to get fields is in line 125: `$fields = Schema::getColumnListing($name);` Ok so digging a little bit more into the getColumnListing method in the Schema class and there it is this code:

```php
public function getColumnListing($table)
    {
        $table = $this->connection->getTablePrefix().$table;

        $results = $this->connection->select(
            $this->grammar->compileColumnListing(), [$this->connection->getDatabaseName(), $table]
        );

        return $this->connection->getPostProcessor()->processColumnListing($results);
    }
```
Basically debugging the code the `$table` parameter is going to be 'voyager_cars' but inside the method there's this line: `$table = $this->connection->getTablePrefix().$table;` which transalates to `$table = 'voyagervoyager_cars'` and that table doesn't exists, so the result for the fields is null or an empty string, I'm not really sure, so it will never fill the data_rows table.

The data_types created by voyager already have data_rows data but if you try to update the BREAD, it won't work because the names have the prefix included.

You know what is awesome? When you create or update a BREAD it doesn't show any errors (notice the sarcasm)

It took me hours to find all this, working with prefix in voyager doesn't work out, it has a lot of bugs. Hopefully you guys will take this information and do something about it, I really like Voyager and I'm using it (obviously without using a prefix) and I really like to use it prefixing my tables. Thanks.

**Comment by abdgad** [comment] 2017-03-24 21:04
@wuelcas thanks for the detailed explanation 👍
So basically all those issues are caused by using a prefix. Here is my suggestion: instead of relying on Laravel to implicitly add the prefix for you, you explicitly hard code it in your tables, since Laravel's prefix works well with tables managed by Laravel, but not with tables managed by other packages (in this case, Voyager).
On Voyager's part, I think we'll add an option to specify a prefix for Voyager's tables during installation, and if left empty, we'll use the prefix specified in Laravel's config.
What do you think about that?

**Comment by wuelcas** [comment] 2017-03-24 22:34
Hey I think is great! Thanks for reading and open that PR, hopefully it will get merged. The thing is I don't like to hardcode the prefix, Laravel does an excellent work managing the prefix  of the tables, hopefully in a future release of Voyager prefixes won't be an issue anymore.

**Closed as completed** 2017-03-25 13:38 UTC
Labels: help wanted, possible bug
