### ISSUE TITLE
Roles do not update anymore

### ISSUE THREAD

**Issue by adeviss2** [thedevdojo/voyager#4701] opened 2020-01-15 11:37 UTC
![4jxdIAltsw](https://user-images.githubusercontent.com/40465038/72430666-aa02f300-379b-11ea-87aa-ce462605d010.gif)

 - Laravel: v6.11.0
 - Voyager: v1.3.1
 - PHP: 7.4
 - Database: sqlite3

Since the last update, roles do not update .. 

1. Go to 'Roles'
2. Click on 'Edit'
3. Check any roles '....'
4. They do not update

Since the last update

**Comment by MrCrayon** [comment] 2020-01-15 11:47
Duplicate of #4668 

Fix has already been merged, you can fix it setting Roles Controller as explained in the other issue.

**Closed as completed by MrCrayon** 2020-01-15 11:47 UTC
Labels: duplicate
