### ISSUE TITLE
BREAD ajax error when searching on a relationship field that has a scope configured

### ISSUE THREAD

**Issue by Stormcloud** [thedevdojo/voyager#4971] opened 2020-06-04 13:57 UTC
## Version information

 - Laravel: v7.6.2
 - Voyager: v1.4.1
 - PHP: 7.4.4
 - Database: MariaDB 10.4.11

## Description

When adding / editing an entry with BREAD, if you search a relationship field where a scope was configured, the search will fail.

Inspection of the AJAX response from the controller shows an exception was raised in Laravel with the following message:

"Property [additional_attributes] does not exist on the Eloquent builder instance."

## Steps To Reproduce
1. Create a table (eg: foos) with a field that references another existing table (eg: users).
2. Configure BREAD for the new table, creating a relationship to the other table (eg: foo belongsTo user).
3. In the model for the referenced table (eg: App\User), create a scope function (eg: filter role_id to show admins only).
4. Back to the BREAD relationship, add a JSON configuration to use your new scope to limit the entries shown in the field.
5. Go create a new entry in the new table (foos). The relationship list (users) is populated. Type in anything to search the list and the error will appear.

## Expected behavior
Search results should appear normally, as they do when no scope is configured.

## Additional context
The exception is raised in line 871 of the following file:
`vendor/tcg/voyager/src/Http/Controllers/VoyagerBaseController.php`

It is trying to access `$model->additional_attributes`.
However, earlier in the code (line 864), if a scope is present in the options, the `$model` variable is reassigned to what the scope function returns (an `Illuminate\Database\Eloquent\Builder` instance). And so accessing `additional_attributes` in the `Builder` instance raises an exception.

I've fixed this locally by adding another variable that references the original model that is loaded on line 860:
`$originalModel = $model = app($options->model);`

Then I use this variable when looking up the attributes on line 871:
`if (in_array($options->label, $originalModel->additional_attributes ?? [])) {`

**Comment by emptynick** [comment] 2020-06-04 14:00
Please search before opening issues.
Duplicate of https://github.com/the-control-group/voyager/issues/4949
And already fixed in https://github.com/the-control-group/voyager/pull/4875

**Closed as completed by emptynick** 2020-06-04 14:00 UTC
Labels: duplicate
