### ISSUE TITLE
Multilanguage BUG in the latest versions

### ISSUE THREAD

**Issue by Rustam95Ur** [thedevdojo/voyager#4103] opened 2019-04-24 12:00 UTC
- Laravel: v5.7
 - Voyager: v1.2.3
 - PHP: 7.2
 - Database: MySQL 5.7

## Description
When you enable multilanguage, a strange error occurs. For example, in order to edit a message, and select Russian, to switch to the Kazakh language, in translation it also shows in Russian.
![image](https://user-images.githubusercontent.com/29037364/56657770-b3eb4000-66ba-11e9-8aa0-92e7bf032560.png)
![image](https://user-images.githubusercontent.com/29037364/56657846-d7ae8600-66ba-11e9-8112-d8e575d3ceb8.png)

## Steps To Reproduce
Just enable multilanguage and create a post. Then try to edit it and switch from on language to another and then backwards.

**Comment by sarxan26** [comment] 2019-04-26 19:29
Same here

**Comment by NurdaKz** [comment] 2019-04-27 09:10
Same here

**Comment by Areg1189** [comment] 2019-04-27 14:22
Same here

**Comment by normangoh** [comment] 2019-04-29 05:37
You can try this #4077

**Comment by emptynick** [comment] 2019-06-01 11:33
Fixed in https://github.com/the-control-group/voyager/pull/4157
Also, duplicate of https://github.com/the-control-group/voyager/issues/4072

**Closed as completed by emptynick** 2019-06-01 11:33 UTC
Labels: duplicate
