### ISSUE TITLE
Personal information can not be saved

### ISSUE THREAD

**Issue by evalor** [thedevdojo/voyager#3033] opened 2018-04-21 20:21 UTC
- Laravel Version: 5.6.17
- Voyager Version: 1.1.0
- PHP Version: 7.2.4
- Database Driver & Version: Mysql 5.6

### Description:
When I modified my personal information and saved it ......

Symfony\Component\Debug\Exception\FatalThrowableError thrown with message "Call to a member function relationLoaded() on null"

Stacktrace:
#0 Symfony\Component\Debug\Exception\FatalThrowableError in /www/wwwroot/chaxun/vendor/tcg/voyager/src/Traits/VoyagerUser.php:121

### Steps To Reproduce:
After normal installation, the problem can be recur immediately.

### composer.json
```json
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": "^7.1.3",
        "barryvdh/laravel-ide-helper": "^2.4",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "^1.0"
    },
    "require-dev": {
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

**Comment by emptynick** [comment] 2018-04-21 20:24
Please search before opening a new issue.
Duplicate of https://github.com/the-control-group/voyager/issues/3028

**Closed as completed by emptynick** 2018-04-21 20:24 UTC
Labels: duplicate
