### ISSUE TITLE
[BUG]:Issue with visibility of Tools menu option

### ISSUE THREAD

**Issue by prakhargvp** [thedevdojo/voyager#4134] opened 2019-05-14 05:08 UTC
## Version information

 - Laravel: v5.8.8
 - Voyager: v1.2
 - PHP: 7.1.24
 - Database: mysql

## Description

- When a Voyager User is under a Role that only has permission to 'browse the Admin', the Tools menu remains in the sidebar even though no options exist under it.
- I would expect that this menu option would not be visible if the User does not have access to either the 'Menu Builder' or 'Database'.

## Screenshots

![Screenshot from 2019-05-14 10-38-24](https://user-images.githubusercontent.com/7056772/57672129-6f592180-7634-11e9-99e7-9ca21aae2888.png)

**Comment by fletch3555** [comment] 2019-05-22 04:28
I'm fairly certain that was fixed many versions ago...  Can you try to clear your view cache and confirm it still remains for that user?

**Comment by ahmedofali** [comment] 2019-05-22 15:41
I can confirm this issue does not exist 
![image](https://user-images.githubusercontent.com/22732463/58188312-a7a5d300-7cb8-11e9-81cf-322a3885623a.png)

And the permissions are 
![image](https://user-images.githubusercontent.com/22732463/58188391-c906bf00-7cb8-11e9-8fde-1a954c165ccd.png)

**Comment by emptynick** [comment] 2019-05-31 19:28
This was fixed in 1.2.3.
Because you didn't provide the whole version number I assume you are using an older version of 1.2.
Closing

**Closed as completed by emptynick** 2019-05-31 19:28 UTC
