### ISSUE TITLE
does voyager admin panel have Forgot Password Functionality ?? 

### ISSUE THREAD

**Issue by priyag597** [thedevdojo/voyager#3946] opened 2019-02-13 10:22 UTC
## Version information

 - Laravel: v5.7
 - Voyager: v1.1.1
 - PHP: 7.2

## Description

does voyager admin panel have Forgot Password Functionality ? if yes so please provide me example how do i build in to voyager ,I am beginner in laravel .

**Comment by theanadimukt** [comment] 2019-02-13 15:48
looking for same functionality

**Comment by emptynick** [comment] 2019-02-20 09:03
Please search before opening issues.
Closing as a duplicate of https://github.com/the-control-group/voyager/issues/2985

**Closed as completed by emptynick** 2019-02-20 09:03 UTC
Labels: duplicate
