### ISSUE TITLE
Route [voyager.hooks] not defined

### ISSUE THREAD

**Issue by nikhileshva** [thedevdojo/voyager#1780] opened 2017-09-20 17:56 UTC
- Laravel Version: 5.4.*
- Voyager Version: "^1.0"
- PHP Version: 5.6.34
- Database Driver & Version: 10.1.16-MariaDB

### Description:
```
InvalidArgumentException
Route [voyager.hooks] not defined.
```

### Steps To Reproduce:

When I go to 127.0.0.1/admin, I get a login screen. 
After I enter the credentials and login, this exception is thrown.

**Comment by fletch3555** [comment] 2017-09-20 18:24
Dupe of #1779

**Closed as completed by fletch3555** 2017-09-20 18:24 UTC
Labels: duplicate
