### ISSUE TITLE
Can't Install Voyager with SQLSRV Database 

### ISSUE THREAD

**Issue by yserrata** [thedevdojo/voyager#2366] opened 2017-12-14 21:41 UTC
- Laravel Version: 5.5.25
- Voyager Version: 1.0.
- PHP Version: PHP Version 7.1.9
- Database Driver & Version: ODBC Driver 13 for SQL Server

### Description:
SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server]
[SQL Server]Introducing FOREIGN KEY constraint 'categories_parent_id_foreign' on table '
categories' may cause cycles or multiple cascade paths. 

Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints. 

(SQL: alter table "categories" add constraint "categories_parent_id_foreign" fo
reign key ("parent_id") references "categories" ("id") on delete set null on update cascade)

Categories Table is not created so i can't found the constrains.

###Migration:

    public function up()
    {
        // Create table for storing categories
        Schema::create('categories', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('parent_id')->unsigned()->nullable()->default(null);
            $table->foreign('parent_id')->references('id')->on('categories')->onUpdate('cascade')->onDelete('set null');
            $table->integer('order')->default(1);
            $table->string('name');
            $table->string('slug')->unique();
            $table->timestamps();
        });
    }

### Steps To Reproduce:
php artisan voyager:install

**Comment by ghost** [comment] 2018-03-23 14:32
same issue here, guess no one is using voyager with sqlsrv?

**Comment by baselbj** [comment] 2018-05-15 16:16
it seems that Voyager didn't support SQLSRV

**Comment by emptynick** [comment] 2018-05-29 11:29
Closing as this is a duplicate of https://github.com/the-control-group/voyager/issues/485

**Closed as completed by emptynick** 2018-05-29 11:29 UTC
Labels: duplicate

**Comment by ledikari** [comment] 2019-03-13 17:18
currently, the onlyway to bypass this is remove the foreign key

` $table->foreign('parent_id')->references('id')->on('categories')->onUpdate('cascade')->onDelete('set null');`

and delete categories table once you access the admin.
