### ISSUE TITLE
[BUG] Timestamp field type not working

### ISSUE THREAD

**Issue by andrey-helldar** [thedevdojo/voyager#3887] opened 2019-01-12 21:34 UTC
## Version information
 - Laravel: v5.7.20
 - Voyager: v1.1.11
 - PHP: 7.2.13

## Description
When you select the type of field `Timestamp` in the bread settings, the script does not initialize the field itself, returning an error in the browser console.

## Steps To Reproduce
1. Go to BREAD settings for table.
2. Change field type to 'timestamp' (in the table field type `varchar`)
3. Saving changes.
4. Go to add/edit record.
5. Open developer console and see that error.

#### 1
![2019-01-13_00-28-39](https://user-images.githubusercontent.com/10347617/51078679-4f3b4500-16ca-11e9-98ee-e0e48c8f999a.png)
#### 2
![2019-01-13_00-31-20](https://user-images.githubusercontent.com/10347617/51078708-f4561d80-16ca-11e9-93e1-929c4388c44c.png)
#### 3
![2019-01-13_00-33-30](https://user-images.githubusercontent.com/10347617/51078709-f61fe100-16ca-11e9-9d3c-97344a6eb20a.png)
#### 4
![2019-01-13_00-33-58](https://user-images.githubusercontent.com/10347617/51078710-f7510e00-16ca-11e9-9d1e-df428bda2965.png)

**Comment by emptynick** [comment] 2019-01-13 09:17
Please search before opening new issues.
Duplicate of #1806

**Closed as completed by emptynick** 2019-01-13 09:17 UTC
Labels: duplicate
