### ISSUE TITLE
Set default photo when delete

### ISSUE THREAD

**Issue by PeterPan73** [thedevdojo/voyager#4705] opened 2020-01-19 07:40 UTC
## Version information

 - Laravel: v5.8
 - Voyager: v1.3.1
 - PHP: 7.2
 - Database: MySQL 8.0

## Description

After delete photo from user in the field in database is set to NULL. Is it possible to put a value after deleting (users/default.png) instead NULL? I want if delete a photo other than the default one (user/default.png) in field to be user/default.png.

## Expected behavior
I expect if I delete a photo it will always be put user/default.png.

**Comment by MrCrayon** [comment] 2020-01-19 08:01
This is not a bug, if you want to set a default value listen to your model events and set a default value when that field is empty. 

If you have further questions about Voyager use and integration please ask in Voyager Slack chat.

**Comment by MrCrayon** [comment] 2020-01-19 08:06
I was a bit to quick to close this, when you delete avatar for a user in database will be set as null but you should still get the default avatar. 

Is that not happening? 

Can you take a screenshot?

**Comment by PeterPan73** [comment] 2020-01-19 08:27
I dont think is a bug, because after I delete the avatar it stays in the folder and the photo field is set to NULL. Is there How can I put 'users/default.png' instead of NULL. In bread there is no option for default value.

**Comment by MrCrayon** [comment] 2020-01-19 08:35
Deleting value from database is the expected behaviour.
You don't need to have the value in db, the default value is passed using an accessor: 
https://github.com/the-control-group/voyager/blob/1a073ecbd2be9edc0b4f8d7c04adda67ec0a4226/src/Models/User.php#L20

Can you see the default avatar even after you delete it in user profile?

**Comment by PeterPan73** [comment] 2020-01-19 08:44
Maybe I should mention that this is not in User table.

Here is my code in app\Customers.php

`namespace App;

use Illuminate\Database\Eloquent\Model;

class Customers extends Model
{
    protected $table = 'customers';
	protected $primaryKey = 'id';
	protected $fillable = array('name','photo');
	
}`

**Comment by MrCrayon** [comment] 2020-01-19 08:46
Yes you should have mentioned that :grinning: 

Follow what it's done in the link I posted earlier, for further questions please join Voyager slack chat.

**Closed as completed by MrCrayon** 2020-01-19 08:46 UTC
Labels: type:question

**Comment by PeterPan73** [comment] 2020-01-19 08:48
Sorry again that i didn't mention early. Can you give link to slack chat?

**Comment by MrCrayon** [comment] 2020-01-19 08:49
https://github.com/the-control-group/voyager/blob/1.3/README.md

**Comment by PeterPan73** [comment] 2020-01-19 08:54
I hope you to help me in chat. I'm in :)
