### ISSUE TITLE
Media library breadcrumb bug

### ISSUE THREAD

**Issue by tabaktoni** [thedevdojo/voyager#4749] opened 2020-02-10 14:21 UTC
## Version information

 - Laravel: v"^5.8"
 - Voyager: v"^1.3.1"
 - PHP: "^7.1.3"

## Description

Media Librady broken showing empty folder that has content after opening folder going back with breadcrump link and opening it again.

## Steps To Reproduce
1. Open Media Library
2. Open some folder  "Media > Library  artworks"
3. Open subfolder "Media Library  > artworks > July2019"
4. Click on media librady breadcrumb parent folder "Media Library  > artworks"
5. Open again same folder "Media Library  > artworksJuly2019"
Breadcrumb link merge last 2 lines and folder is empty

## Expected behavior
To have breadcrumb link at the end "Media Library  > artworks > July2019" and show content of folder

## Screenshots
![bad](https://user-images.githubusercontent.com/923054/74157564-ca965f80-4c18-11ea-9dbf-23dcf9261102.JPG)
![ok](https://user-images.githubusercontent.com/923054/74157596-d550f480-4c18-11ea-82ac-d445ae20476c.JPG)

**Comment by emptynick** [comment] 2020-02-10 14:23
Please search before opening new issues.
Duplicate of https://github.com/the-control-group/voyager/issues/4685.
Please let me know if it's different from https://github.com/the-control-group/voyager/issues/4685

**Closed as completed by emptynick** 2020-02-10 14:23 UTC
Labels: duplicate
