### ISSUE TITLE
Use existing image / other media assets instead upload it again

### ISSUE THREAD

**Issue by rizkiheryandi** [thedevdojo/voyager#3680] opened 2018-10-23 01:27 UTC
## Version information

 - Laravel: v5.7
 - Voyager: v1.1
 - PHP: 7.1
 - Database: MySQL 5.7

How about feature for using existing image / other media assets that already upload before instead upload it again ?

Like wordpress doing now

Still open the pull request ?

**Comment by emptynick** [comment] 2018-10-23 06:17
Please search before opening new issues.
Duplicate of https://github.com/the-control-group/voyager/issues/1877
And there's even a WIP PR https://github.com/the-control-group/voyager/pull/3034

**Closed as completed by emptynick** 2018-10-23 06:17 UTC
Labels: duplicate

**Comment by rizkiheryandi** [comment] 2018-10-23 06:55
This #1877 issue is not same to my issue, please read carefully

But this WIP PR #3034 i think it's same with my request feature, i will waiting for this PR included to the next release

**Comment by emptynick** [comment] 2018-10-23 07:11
I'm pretty sure that #1877 is the very same:
`Add the functionality to upload images via media manager.`
And I dont think #3034 will make it to the next release because there wasn't any activity in a few month.

**Comment by rizkiheryandi** [comment] 2018-10-23 08:23
I said "use existing image / other media assets that already upload" for a post, a page or other, so we don't upload twice for a field with same image content

it's very different with "Add the functionality to upload images via media manager", i know how to upload via media manager, because this feature is already with v1.1

Have you use Wordpress ? i think you never use wordpress, because it's very hard to you to understand what i mean, maybe you should use wordpress, it's very good :D 

Or if you a wordpress expert, i don't know why is very hard to you to understand what i mean, even you a wordpress expert :\

-------------------------------------------------------

Sounds bad about #3034 there wasn't any activity in a few month, because

Thanks :D

**Comment by fletch3555** [comment] 2018-10-23 12:14
@rizkiheryandi please watch your tone.

#1877 is asking about expanding the media manager page's functionality so it can function as a "file chooser" for upload fields.  This will allow you to either upload a new file, or select a previously uploaded one.  This is exactly what you suggested, which is why @emptynick closed this as a duplicate.

**Comment by rizkiheryandi** [comment] 2018-10-23 12:32
Okay, im so sorry too if my tone so bad, my bad, im just excited about this :D

I will make PR for this feature ASAP
