### ISSUE TITLE
Multilungual. Empty body_i18n fields after form submit

### ISSUE THREAD

**Issue by AlexanderWM** [thedevdojo/voyager#3252] opened 2018-05-30 19:40 UTC
- Laravel Version: 5.6
- Voyager Version: 1.1
- PHP Version: 7.1.3
- Database Driver & Version: PostgreSQL 9.6.7

### Description:

Body body_i18n after changing language or submit post add/edit form left empty. Exactly this cause several bugs with "Undefined index: en". 

### Steps To Reproduce:
Look the screen cast: 

![3](https://user-images.githubusercontent.com/12584519/40743496-f943cf9e-6451-11e8-862b-9e24ddb66e08.gif)

Other fields works correctly:

![4](https://user-images.githubusercontent.com/12584519/40743826-e09dda2e-6452-11e8-8db3-2d55edea8158.gif)

**Comment by emptynick** [comment] 2018-05-30 19:43
Please search before opening a new issue.
Duplicate of #3228, #3181, #3187, #3196 and #3089

**Closed as completed by emptynick** 2018-05-30 19:43 UTC
Labels: duplicate
