### ISSUE TITLE
undefined function title_case()

### ISSUE THREAD

**Issue by iamriajul** [thedevdojo/voyager#4392] opened 2019-09-07 11:26 UTC
## Version information

 - Laravel: v6.0.0
 - Voyager: v1.3.x-dev
 - PHP: 7.3
 - Database: MySQL 5.7

## Description
`title_case()` global function may have been removed from Laravel 6.0, so now I think we should use `Illuminate\Support\Str::title()` method instead.
`title_case()` call can be found inside `/resources/views/roles/edit-add.blade.php`

## Steps To Reproduce
Install Voyager on Laravel 6.0
Go to Roles and then Add New or Edit One.

**Comment by emptynick** [comment] 2019-09-07 11:29
Please search before opening new issues.
Duplicate of https://github.com/the-control-group/voyager/issues/4386, https://github.com/the-control-group/voyager/issues/4383, https://github.com/the-control-group/voyager/issues/4380 and https://github.com/the-control-group/voyager/issues/4376

Also note that our Readme explicit states that we only support Laravel 5.5 to 5.8 at the moment.

**Closed as completed by emptynick** 2019-09-07 11:29 UTC
Labels: duplicate
