### ISSUE TITLE
Multi-Lang Rich Text Box Won't Submit

### ISSUE THREAD

**Issue by reageek** [thedevdojo/voyager#3400] opened 2018-07-13 15:56 UTC
## Version information

 - Laravel: v5.6.40
 - Voyager: v1.1.3
 - PHP: 7.2.5
 - Database: mysqlnd 5.0.12-dev
 - env: Homestead v7.10.0

## Description
Pages with translatable fields that have a rich text box bread prevent the creation of new items. Console displays `an invalid form control with name="{fieldname}" is not focusable.`  New item does not submit.

## Steps To Reproduce
1.  Create a fresh project `composer create-project laravel/laravel project-name && cd project-name`
2. Update env file for project. prepend setting `APP_URL` with http://
3. Run `composer require tcg/voyager && php artisan voyager:install --with-dummy`
4. In config/voyager.php: line 113 change false to true, uncomment line 130.
5. Navigate to /admin
6. Sign in.
7. Navigate to /admin/pages/create
8. Fill in the content of the page field. 
9. Attempt to submit the form

## Expected behavior
Form to submit. new page to be added.

## Screenshots
[Note my ss has the error twice because double click. ](https://imgur.com/7hmrDkY)

## Additional context

Applies to more  than just the tcg voyager models. Custom models that have trait Translatable and the appropriate protected $translated values also display properly on the page, but error out and fail to save new items.

## Additional notes
reverting config/voyager.php 113 to true no longer causes the submission to fail.
laravel.log is empty.

#### Additional oddity. If you refresh with f5 the form will sticky the entered data and in addition it will be submit able.

**Comment by emptynick** [comment] 2018-07-17 09:29
Please [search](https://github.com/the-control-group/voyager/issues?utf8=%E2%9C%93&q=is%3Aissue+focusable) before opening an issue.

This is a duplicate of #3209 #2965 #2895 and #2578

**Closed as completed by emptynick** 2018-07-17 09:29 UTC
Labels: duplicate

**Comment by reageek** [comment] 2018-07-17 20:52
The issue is supposed to be resolved with #2660 and with release v1.0.16.
I'll state it again. I am using version v1.1.3. Still experiencing the same problem and not in a chrome based browser. Republishing the assets with the forced flag does not resolve the issue.

While I am glad there is a workaround with https://github.com/the-control-group/voyager/issues/3209#issuecomment-397290668. It's very sloppy as you lose the rest of your validation.

As fletch stated here: https://github.com/the-control-group/voyager/issues/2894#issuecomment-380538958 (and on slack when I posted this issue there) its a known unresolved problem.

Maybe when I have time during my current project it is something I can visit and make a pr for.
Sorry for the duplicate issue!

**Comment by fletch3555** [comment] 2018-07-18 15:39
As @emptynick stated, this issue is a duplicate of those others.  You'll notice at least one of the issues he linked is still open, and is reported using v1.1.1.  Having multiple issues tracking the same problem only leads to confusion.  Therefore, this will remain closed.
