### ISSUE TITLE
Will voyager be built for laravel 5.6?

### ISSUE THREAD

**Issue by Benyaminrmb** [thedevdojo/voyager#2966] opened 2018-04-13 11:16 UTC
- Laravel Version: 5.6
- Voyager Version: *
- PHP Version: 7
- Database Driver & Version:

### Description:
Will voyager be built for laravel 5.6? or we must to migrate to Laravel 5.5 ?

**Comment by emptynick** [comment] 2018-04-13 11:17
Quoting my answer from #2956 again

Please search before opening a new issue.
Duplicate of #2959 #2791 #2759 #2704 #2680 #2676 #2650 #2637 #2624 #2619 and a lot more.
Also this is mentioned in our [Readme](https://github.com/the-control-group/voyager/blob/1.0/README.md) and theres a solution provided in https://github.com/the-control-group/voyager/issues/2650

**Closed as completed by emptynick** 2018-04-13 11:17 UTC
Labels: duplicate
