### ISSUE TITLE
Translations table has two auto_increment columns

### ISSUE THREAD

**Issue by jbnv** [thedevdojo/voyager#1809] opened 2017-09-21 18:40 UTC
- Laravel Version: 5.4
- Voyager Version: 1.0
- PHP Version: 5.6.4
- Database Driver & Version: 14.14 Distrib 5.6.37, for Linux (x86_64)

### Description:

The generation of the `translations` table is failing because the SQL statement for it attempts to make two columns `auto_increment`. 

```
> php artisan voyager:install --with-dummy
Setting up the hooks
Hooks are now ready to use! Go ahead and try to "php artisan hook:install test-hook"
Publishing the Voyager assets, database, language, and config files
Copied Directory [/vendor/tcg/voyager/publishable/assets] To [/public/vendor/tcg/voyager/assets]
Copied Directory [/vendor/tcg/voyager/publishable/database/migrations] To [/database/migrations]
Copied Directory [/vendor/tcg/voyager/publishable/database/seeds] To [/database/seeds]
Copied Directory [/vendor/tcg/voyager/publishable/demo_content] To [/storage/app/public]
Copied Directory [/vendor/tcg/voyager/publishable/lang] To [/resources/lang]
Publishing complete.
Publishing complete.
Migrating the database tables into your application

  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table definition; there c
  an be only one auto column and it must be defined as a key (SQL: create table `translations
  ` (`id` int unsigned not null auto_increment primary key, `table_name` varchar(32) not null
  , `column_name` varchar(32) not null, `foreign_key` int unsigned not null auto_increment pr
  imary key, `locale` varchar(11) not null, `value` text not null, `created_at` timestamp nul
  l, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci)

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table definition; there c
  an be only one auto column and it must be defined as a key

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table definition; there c
  an be only one auto column and it must be defined as a key
```

Note: Support staff in the Slack channel had me replace part of the `translations` migration code:
```
$table->string('table_name')->unique();
$table->string('column_name')->unique();
$table->integer('foreign_key')->unsigned()->unique();
$table->string('locale')->unique();
```
To:
```
$table->string('table_name', 32)->unique();
$table->string('column_name', 32)->unique();
$table->integer('foreign_key', 11)->unsigned()->unique();
$table->string('locale', 11)->unique();
```

This change was because I was still receiving "specified key too long" errors despite applying the patch for Laravel 5.4

**Comment by nitzanb3m** [comment] 2018-09-05 20:46
Any progress on that? This is open for almost a year now

**Comment by fletch3555** [comment] 2018-09-05 21:12
I'm not sure this is valid (anymore).  The translations table migration does not specify multiple auto-increment fields: https://github.com/the-control-group/voyager/blob/1.1/migrations/2017_01_14_005015_create_translations_table.php.  I'm going to close this unless someone else reports the same issue and can identify the cause.

**Closed as completed by fletch3555** 2018-09-05 21:12 UTC
Labels: possible bug
