### ISSUE TITLE
select multiple relationship edit  no Default selection

### ISSUE THREAD

**Issue by xushinongpin** [thedevdojo/voyager#4233] opened 2019-06-28 18:08 UTC
## Version information

 - Laravel: v5.8.*
 - Voyager: v^1.2
 - PHP: 7.3
- MySQL 8.0
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description

select multiple relationship edit  no Default selection

## Expected behavior
add value Screen capture
<p align="center">
<img src="http://metinfo.ilvtian.com/upload/201906/1561745280602021.png" style="" title="1561745280602021.png"/>
</p>
edit value Screen capture
<p align="center">
<img src="http://metinfo.ilvtian.com/upload/201906/1561745280306313.png" style="" title="1561745280306313.png"/>
</p>
bread set
<p align="center">
<img src="http://metinfo.ilvtian.com/upload/201906/1561745488922531.png" title="图片关键词" alt="图片关键词"/>
</p>
database has value
<p align="center">
<img src="http://metinfo.ilvtian.com/upload/201906/1561745596275897.png" title="图片关键词" alt="图片关键词"/>

</p>

**Comment by tunapiq** [comment] 2019-07-02 07:09
I just made a comment on how to fix this here: https://github.com/the-control-group/voyager/issues/4031

**Comment by xushinongpin** [comment] 2019-07-02 20:31
> I just made a comment on how to fix this here: #4031

think you

**Comment by emptynick** [comment] 2019-07-18 16:13
Closing as a duplicate of #4031
Also select multiple is not used for relationships for more than a year now. Don't use it. Its not documented anyway.

**Closed as completed by emptynick** 2019-07-18 16:13 UTC
Labels: duplicate
