### ISSUE TITLE
Laravel 6, edit Bread not working (Database not update after edit)

### ISSUE THREAD

**Issue by host9999** [thedevdojo/voyager#4395] opened 2019-09-08 14:36 UTC
## Version information

 - Laravel: v6.0
 - Voyager: v1.2
 - PHP: 7.2.21
 - Database: [type] [version] (e.g. MySQL 8.0)

## Description of problem
Clean project with laravel6 and Voyager1.2, throws errors when edit bread

Where you can edit Bread to the system the field I updated into the table via the Bread manager in Voyager doesn't show up.

There is no support for laravel6 yet?

**Comment by emptynick** [comment] 2019-09-08 14:37
Please search before opening new issues.
Duplicate of #4386, #4383, #4380, #4376 and #4392

Also note that our Readme explicit states that we only support Laravel 5.5 to 5.8 at the moment.

**Closed as completed by emptynick** 2019-09-08 14:37 UTC
Labels: duplicate
