### ISSUE TITLE
Tinker automatically quits after fresh installation

### ISSUE THREAD

**Issue by peterson-umoke** [thedevdojo/voyager#1940] opened 2017-10-05 09:04 UTC
- Laravel Version: 5.5
- Voyager Version: 1.0.0
- PHP Version:7.1.9
- Database Driver & Version:
mysql
### Description:
Tinker automatically quits and displays a ctrl + d, can't use tinker

### Steps To Reproduce:
simply install a new laravel installation file
install voyager
run php artisan voyager:install

**Comment by peterson-umoke** [comment] 2017-10-07 01:49
after installing this about five times, if i run php artisan tinker, it will able abort, please i need help with this.

**Comment by fletch3555** [comment] 2017-10-07 17:32
It is very unlikely that this is an issue with Voyager.  You would have better luck seeking support through a more generic laravel medium, such as the laracasts forum or larachat slack group

**Comment by peterson-umoke** [comment] 2017-10-09 14:00
i dont suppose so, cause this only happened AFTER I installed voyager

**Comment by peterson-umoke** [comment] 2017-10-13 09:03
closed the-control-group/voyager#1940

**Comment by fletch3555** [comment] 2017-10-13 18:48
@peterson-umoke, I'm assuming your comment was intended to close this issue?

**Comment by peterson-umoke** [comment] 2017-10-14 20:43
yes

**Closed as completed** 2017-10-16 17:31 UTC
Labels: invalid
