### ISSUE TITLE
migrarte:refresh will cause error

### ISSUE THREAD

**Issue by flamerecca** [thedevdojo/voyager#3733] opened 2018-11-08 07:02 UTC
If execute`php artisan migrarte:refresh` the second time will cause error due to foreign key constraint.

## Version information
 - Laravel: v5.7.11
 - Voyager: v1.1.10
 - PHP: 7.2
 - Database: MySQL 5.7

## Description

If execute`php artisan migrarte:refresh` the second time will cause error.

```
Rolling back: 2017_11_26_013050_add_user_role_relationship

   Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1832 Cannot change column 'role_id': used in a foreign key constraint 'users_role_id_foreign' (SQL: ALTER TABLE users CHANGE role_id role_id INT DEFAULT NULL)
```

## Steps To Reproduce
1. Install Voyager
2. Execute 'voyager:install'
3. Execute 'php artisan migrarte:refresh', everything works fine.
4. Execute 'php artisan migrarte:refresh' again, See error.

## Expected behavior
Everything should works fine whenever we execute `php artisan migrarte:refresh`

**Comment by emptynick** [comment] 2018-11-08 07:22
Please search before opening new issues.
Closing as a duplicate of #3071 .
Fixed in 1.x by #3073 . Please try that out.

**Closed as completed by emptynick** 2018-11-08 07:22 UTC
Labels: duplicate
