### ISSUE TITLE
Answer from translate included other fields from other tables

### ISSUE THREAD

**Issue by trollsk1n** [thedevdojo/voyager#1628] opened 2017-08-31 08:53 UTC
- Laravel Version: 5.4
- Voyager Version: 0.11
- PHP Version: 7.1
- Database Driver & Version: MySQL

### Description:
Bug with multilanguage

### Steps To Reproduce:

I create custom model for working with API, and enable multi language on admin panel, after where i send request to back-end i get JSON object, who include translate from other table.

my request function

`protected $table = 'categories';`

```
public function getAllProductCategories() {

		return $this->published()
		            ->where('parent_id', 1)
			    ->withTranslations()
		            ->get();
	}
```

and JSON, where i get 

```
{
    "status": "success",
    "data": {
        "product_categories": [
            {
                "id": 2,
                "parent_id": 1,
                "order": 2,
                "name": "Цеховикам",
                "slug": "for-workshop",
                "status": "ACTIVE",
                "translations": [
                    {
                        "id": 18,
                        "table_name": "banners",
                        "column_name": "title",
                        "foreign_key": 2,
                        "locale": "en",
                        "value": "Main banner_2",
                        "created_at": "2017-08-31 06:26:52",
                        "updated_at": "2017-08-31 06:26:52"
                    },
                    {
                        "id": 19,
                        "table_name": "banners",
                        "column_name": "text",
                        "foreign_key": 2,
                        "locale": "en",
                        "value": "<p>Know how to get our windows&nbsp;<a href=\"/about-us\">/about-us</a></p>",
                        "created_at": "2017-08-31 06:26:52",
                        "updated_at": "2017-08-31 06:26:52"
                    },
                    {
                        "id": 24,
                        "table_name": "categories",
                        "column_name": "name",
                        "foreign_key": 2,
                        "locale": "en",
                        "value": "For workshop",
                        "created_at": "2017-08-31 08:02:33",
                        "updated_at": "2017-08-31 08:02:33"
                    }
                ]
            }
        ]
    }
}
```

**Comment by marktopper** [comment] 2017-09-06 18:28
I will look into this.

**Comment by MrCrayon** [comment] 2020-01-01 10:23
Since this reference a quite old Voyager version I'm closing this. 

If you can reproduce the problem with last Voyager release please open another issue.

**Closed as completed by MrCrayon** 2020-01-01 10:23 UTC
Labels: type:bug
