### ISSUE TITLE
Multilingual issue with select fields and radio buttons on create and edit

### ISSUE THREAD

**Issue by pietrantonio-orbitalwaves** [thedevdojo/voyager#2274] opened 2017-11-22 18:31 UTC
- Laravel Version: 5.5.20
- Voyager Version: 1.0
- PHP Version: 7.0.0
- Database Driver & Version: MySql 5.7

### Description:
We activated Multilingual but there is an issue with select fields and radio buttons.
By compiling a select field (or a radio button) in a language (value A), then changing tab and selecting a different value (value B) on the same field, the first tab shows the new value (value A) but passes the correct value on submit (value B). 

### Steps To Reproduce:

1. Activate multilingual with at least two languages
2. Compile "status" field in the post creation in default language
3. Switch to another language
4. Compile the same field with another value
5. Switch to default language
6. The field doesn't show the right value (also if its submitted value is correct)

**Comment by MrCrayon** [comment] 2020-04-09 11:07
Most probably this has been already resolved since currently selects don't change while switching language and I can't reproduce it.

I'm closing it but we can reopen it if it's still a problem.

**Closed as completed by MrCrayon** 2020-04-09 11:07 UTC
Labels: possible bug, i18n
