### ISSUE TITLE
Laravel 5.6.* support anytime soon?

### ISSUE THREAD

**Issue by amc123-glitch** [thedevdojo/voyager#2956] opened 2018-04-11 17:41 UTC
- Laravel Version: "laravel/framework": "5.6.*",
- Voyager Version: tcg/voyager 1.0.x-dev
- PHP Version: "php": "^7.1.3",
- Database Driver & Version: local Mysql mamp server

### Description:
It is my understanding that people claimed voyager was not working with 5.6 back towards the end of summer, around September or so. Not sure if there is a different version that can work with laravel 5.6 or if I need to downgrade my laravel version to an older version for it to work.

Literally a fresh new project as I am following the voyager academy videos, since I have not used voyager as much

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.6.16
    - Conclusion: don't install laravel/framework v5.6.16
    - tcg/voyager 1.0.x-dev requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.0 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.1 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.10 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.11 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.12 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.13 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.14 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.15 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.16 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.17 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.2 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.3 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.4 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.5 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.6 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.7 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.8 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - tcg/voyager v1.0.9 requires illuminate/support ~5.4.0|~5.5.0 -> satisfiable by illuminate/support[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - illuminate/support 5.4.x-dev conflicts with laravel/framework[v5.6.16].
    - illuminate/support 5.5.x-dev conflicts with laravel/framework[v5.6.16].
    - illuminate/support v5.4.0 conflicts with laravel/framework[v5.6.16].
    - illuminate/support v5.4.13 conflicts with laravel/framework[v5.6.16].
    - illuminate/support v5.4.17 conflicts with laravel/framework[v5.6.16].
    - illuminate/support v5.4.19 conflicts with laravel/framework[v5.6.16].
    - illuminate/support v5.4.27 conflicts with laravel/framework[v5.6.16].
    - illuminate/support v5.4.36 conflicts with laravel/framework[v5.6.16].
    - illuminate/support v5.4.9 conflicts with laravel/framework[v5.6.16].
    - illuminate/support v5.5.0 conflicts with laravel/framework[v5.6.16].
    - illuminate/support v5.5.16 conflicts with laravel/framework[v5.6.16].
    - illuminate/support v5.5.17 conflicts with laravel/framework[v5.6.16].
    - illuminate/support v5.5.2 conflicts with laravel/framework[v5.6.16].
    - illuminate/support v5.5.28 conflicts with laravel/framework[v5.6.16].
    - illuminate/support v5.5.35 conflicts with laravel/framework[v5.6.16].
    - illuminate/support v5.5.36 conflicts with laravel/framework[v5.6.16].
    - illuminate/support v5.5.37 conflicts with laravel/framework[v5.6.16].
    - illuminate/support v5.5.39 conflicts with laravel/framework[v5.6.16].
    - illuminate/support v5.5.40 conflicts with laravel/framework[v5.6.16].
    - don't install illuminate/support v5.5.33|don't install laravel/framework v5.6.16
    - don't install illuminate/support v5.5.34|don't install laravel/framework v5.6.16
    - Installation request for laravel/framework (locked at v5.6.16, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.16].
    - Installation request for tcg/voyager ^1.0 -> satisfiable by tcg/voyager[1.0.x-dev, v1.0.0, v1.0.1, v1.0.10, v1.0.11, v1.0.12, v1.0.13, v1.0.14, v1.0.15, v1.0.16, v1.0.17, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6, v1.0.7, v1.0.8, v1.0.9].

Installation failed, reverting ./composer.json to its original content.

### Steps To Reproduce:
- laravel new project name
- added db credentials to .env
- composer require tcg/voyager

### Attempted (threw every command I could think of)
- php artisan config:cache
- composer dump
- composer update
- composer require tcg/voyager

**Comment by emptynick** [comment] 2018-04-11 17:53
Please search before opening a new issue.
Duplicate of #2791 #2759 #2704 #2680 #2676 #2650 #2637 #2624 #2619 and a lot more.
Also this is mentioned in our [Readme](https://github.com/the-control-group/voyager/blob/1.0/README.md) and theres a solution provided in https://github.com/the-control-group/voyager/issues/2650

**Closed as completed by emptynick** 2018-04-11 17:53 UTC
Labels: duplicate
