### ISSUE TITLE
Admin Database Broken

### ISSUE THREAD

**Issue by JoshuaBedford** [thedevdojo/voyager#4637] opened 2019-12-17 21:15 UTC
## Version information

 - Laravel: v6.8.0
 - Voyager: v1.3.0
 - PHP: 7.2
 - Database: MySQL 14.14

## Description

I just completed a fresh install of the most recent version of laravel, then did an install with the most recent version of voyager. When I go to the Database admin panel (/admin/database), the following error occurs:

```
Facade\Ignition\Exceptions\ViewException
Missing required parameters for [Route: voyager.bread.delete] [URI: admin/bread/{id}]. (View: /app/vendor/tcg/voyager/resources/views/tools/database/index.blade.php)
http://voyager.lndo.site/admin/database
```

## Steps To Reproduce
1. Go to /admin/database

## Expected behavior
I expected to be able to see and edit the database tables.

## Screenshots
<img width="1225" alt="Screen Shot 2019-12-17 at 3 15 05 PM" src="https://user-images.githubusercontent.com/13459258/71034910-05c85680-20e0-11ea-9c0d-25c34f48022e.png">

**Comment by fletch3555** [comment] 2019-12-17 22:48
Duplicate of #4586 and #4595 (among others).  Please search before opening issues

**Closed as completed by fletch3555** 2019-12-17 22:48 UTC
Labels: duplicate
