### ISSUE TITLE
Duplicate key name error when updating a table with unique columns

### ISSUE THREAD

**Issue by Frondor** [thedevdojo/voyager#478] opened 2017-01-02 02:39 UTC
- Laravel Version: 5.3.28
- Voyager Version: 0.10.5
- PHP Version: 7
- Database Driver & Version: MySQL 5.7.11

### Description:
If I create a table with an `unique` column, I can't update it from voyager anymore because it doesn't check if the key is already there, and it turns into a 
```
QueryException in Connection.php line 770:
SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'services_name_unique' (SQL: alter table `services` add unique `services_name_unique`(`name`))
```

### Steps To Reproduce:
![https://i.gyazo.com/342572c068ea4997115f1656930194a0.gif](https://i.gyazo.com/342572c068ea4997115f1656930194a0.gif)

**Comment by fletch3555** [comment] 2017-01-02 05:01
I'm not sure if this was fixed yet, but please update voyager to latest(currently v0.10.7) and test again.

**Comment by Frondor** [comment] 2017-01-02 16:33
I can confirm it still happens on .10.7
Create a new table with an unique column and then try to update it (no changes needed).

**Comment by Frondor** [comment] 2017-01-10 03:57
@marktopper can you pay a look here? Just updated my installation and it is still happening.

**Comment by handiwijoyo** [comment] 2017-01-10 10:20
This issue has been fixed on #518

**Comment by kevinjon27** [comment] 2017-01-19 14:57
@handiwijoyo I can confirm it still happen too on 0.10.10. Update user table for add new field. Thank you

**Comment by marktopper** [comment] 2017-01-19 19:09
The pull request from @handiwijoyo have not been merged yet since it have some issues.
Im open for other pull requests to fix this.

**Comment by Frondor** [comment] 2017-02-02 19:17
This error is still here @ v10.12
Even if I try and delete the `unique` row, more errors pop up. The row is updated but with errors (can't remember right now).

To reproduce: install v10.12 (latest) -> go to `pages` table -> update it.
See the error? Now try to delete the `unique` table

**Comment by zietbukuel** [comment] 2017-02-09 22:48
Same here, I create a table with a unique field, then without doing any changes I hit update and I get this:
`
SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'products_slug_unique' (SQL: alter table `products` add unique `products_slug_unique`(`slug`))`

**Comment by grandsilence** [comment] 2017-11-09 12:48
bug still present( I'll try to fix this later with pull request

**Comment by Skyrant** [comment] 2017-12-10 15:32
I still have this error when i install WHMCS, what is the status or is there a workaround?

**Comment by handiwijoyo** [comment] 2018-01-08 10:46
This is an issue with older Voyager version. Please open a new issue if you still have this error.

**Closed as completed by handiwijoyo** 2018-01-08 10:46 UTC
Labels: type:bug, help wanted
