### ISSUE TITLE
Old image not deleted after updating image field

### ISSUE THREAD

**Issue by donmbelembe** [thedevdojo/voyager#2264] opened 2017-11-21 17:16 UTC
- Laravel Version: 5.5
- Voyager Version: 1.*
- PHP Version: 7.1

The question was asked previously and you say it will be solve in the new version for 1.* otherwise we should repost again.

old issue #1309

**Comment by tr0yka** [comment] 2018-03-07 22:19
+

**Comment by tr0yka** [comment] 2018-03-07 22:19
+1

**Comment by charliepeck** [comment] 2018-12-28 16:36
This is an old post, but it doesn't seem like it's being addressed.  I'm currently working on a project that Voyager is perfect for.  The problem is that at the end of the day, I need to download the active images to a local machine for processing.  It's a lot of extra work to determine which images in the directory should be downloaded.  If anybody has a good work around for this, It would be greatly appreciated.

**Comment by emptynick** [comment] 2018-12-28 16:45
This was addressed in https://github.com/the-control-group/voyager/pull/3240.
It's gonna be included in 1.1.11
Edit: its not fixed in 1.1.11, I will take a look at it.

**Comment by nemrutco** [comment] 2019-02-24 07:17
+1

**Comment by AmirEdward** [comment] 2019-04-03 10:17
+1
a work around that may help you:
in the model page make a boot method and inside make a listener for deleting/updating/creating events and in the closure you can delete the stored image
the problem with me that i have multiple image upload field and i want to trigger a function on column update from the admin panel to delete only the photo that is removed from the column .. any idea how to do that ??

**Closed as completed** 2021-01-28 11:44 UTC
Labels: type:bug, addressed
