### ISSUE TITLE
empty request handle !

### ISSUE THREAD

**Issue by jehadja** [thedevdojo/voyager#3724] opened 2018-11-05 11:17 UTC
i mention on voyager/src/Http/Controllers/Controller.php the fallowing code 

```
             // if the field for this row is absent from the request, continue
            // checkboxes will be absent when unchecked, thus they are the exception
            if (!$request->hasFile($row->field) && !$request->has($row->field) && $row->type !== 'checkbox') {
                // if the field is a belongsToMany relationship, don't remove it
                // if no content is provided, that means the relationships need to be removed
                if ((isset($row->details->type) && $row->details->type !== 'belongsToMany') || $row->field !== 'user_belongsto_role_relationship') {
                    continue;
                }
            } 
```
is this return always true ??
`|| $row->field !== 'user_belongsto_role_relationship'  
` 
as i am sure not all field called  user_belongsto_role_relationship
it mean we any way remove all empty fields even if its belong to many where this is the first part of if statement as || or mean one of them shall be ture and we have second part of if statement are ture 
i think this shall be &&

**Comment by emptynick** [comment] 2018-11-05 11:26
Please use the issue template and [search](https://github.com/the-control-group/voyager/issues?utf8=%E2%9C%93&q=is%3Aissue+user_belongsto_role_relationship) before opening new issues.
Closing as a duplicate of the above results.

**Closed as completed by emptynick** 2018-11-05 11:26 UTC
Labels: duplicate
