### ISSUE TITLE
BelongsToMany select multiple bug

### ISSUE THREAD

**Issue by tunapiq** [thedevdojo/voyager#3350] opened 2018-06-25 05:05 UTC
## Version information

 - Laravel: v5.5.*
 - Voyager: v1.1.2
 - PHP: 7.2
 - Database: [PostgreSQL] [10.4]

## Description

When using BelongsToMany relationship, the select multiple TextBox that automatically appears in the BREAD "Edit view" doesn't "update" if the previously selected options are all removed. My guess for why this happens is that the code simply picks whatever options you select for the update while ignoring a situation whereby the user decides to remove all previously selected options. Is there a way to fix this please?

**Comment by fletch3555** [comment] 2018-06-25 15:41
This is a perfect case for the `Steps to Reproduce` field... 

Just so I understand... 
- You have a dropdown with options `A`,`B`, and `C` (populated by the relationship).
- You select `B` and save (information is stored correctly in the database).
- You then delete `B` from the related table.
- When you reload the `edit` view, it shows the same dropdown with `A` selected from the options of `A` and `C`.  Correct?

**Comment by tunapiq** [comment] 2018-06-25 21:53
I was able to fix this bug by editing the source codes

Bug path:
TCG\Voyager\Http\Controllers\Controller.php

Method: insertUpdateData

By changing 

`if (isset($options->type) && $options->type !== 'belongsToMany') || $row->field !== 'user_belongsto_role_relationship')`

To
`if (isset($options->type) && $options->type !== 'belongsToMany')`

there are some situations whereby the $row->field value is not equal to 'user_belongsto_role_relationship' like in my case. My best guess was the entire if condition was no longer required for this version of Voyager (1.1.2). Please correct me if I have done the wrong thing to fix this bug.

Thank you.

----------------------------
Steps to reproduce bug

- You have a dropdown with options A,B, and C (populated by the relationship).
- You select A,B,C and save (information is stored correctly in the database).
- You then delete ALL previously selected i.e (A,B, C) from the related table, then click update.
- When you reload the edit view, it shows the same dropdown with A,B,C selected from the options.

**Comment by hooch** [comment] 2018-09-15 04:14
I also hit this bug.

When removing A,B,C, Voyager offers a "None" option
Select "None"
On save, exception:

    SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'role_id'
    at row 1 (SQL: insert into `user_roles` (`role_id`, `user_id`) values (, 2))

This happens because the $content data passed to the belongsToMany update function contains:

    [ 0 => null ]

**Comment by hooch** [comment] 2018-09-15 13:23
When removing all A,B,C and not selecting "None", an empty array [] is created, but for the ```continue``` that's triggered by a bug in the first if condition of the for loop.

**Comment by hooch** [comment] 2018-09-15 15:34
re the patch from @tunapiq above, this seems to be what was intended:

    if (isset($options->type) && $options->type !== 'belongsToMany') 
        || $row->field == 'user_belongsto_role_relationship')

i.e. changing the latter ```!==``` to ```==```:

**Comment by hooch** [comment] 2018-09-16 09:48
Apologies, the code change suggested in my last comment breaks when editing the current logged in user.

**Comment by jehadja** [comment] 2018-11-05 12:08
i have open new issue for the last version of code it have been closed any way my solution will be as fallowing but need to test locally it works with me 
voyager/src/Http/Controllers/Controller.php
`                if ((isset($row->details->type) && $row->details->type !== 'belongsToMany') && $row->field !== 'user_belongsto_role_relationship') {
                    continue;
                }`

replace || with && 
also at line 105 - 110 
`            if ($row->type == 'relationship' && $row->details->type == 'belongsToMany') {
                // Only if select_multiple is working with a relationship
                $multi_select[] = ['model' => $row->details->model, 'content' => $content, 'table' => $row->details->pivot_table];
            } else {
                if($content!='[]')
                $data->{$row->field} = $content;
            }`
also
/src/Http/Controllers/ContentTypes/MultipleImage.php
add if statement on before foreach 
`        if(!empty($files) && count($files))
        foreach ($files as $file) {`

**Comment by emptynick** [comment] 2018-12-22 14:35
Fixed in #3016.
Merged into 1.x

**Closed as completed by emptynick** 2018-12-22 14:35 UTC
