### ISSUE TITLE
Updating the admin.description ends up in integrity constraint violation

### ISSUE THREAD

**Issue by philippzentner** [thedevdojo/voyager#4600] opened 2019-11-30 12:54 UTC
## Version information
 - Laravel: v6.5.2
 - Voyager: v1.3.0
 - PHP: 7.3
 - Database: MySQL 5.7.28

## Description:
Updating the Admin Site Description ends up in integrity constraint violation

## Additional context
When I update the Admin Dashboard Description from within the dashboard, voyager tries to update admin description on the wrong id. It tries to update where id=2 (key = site.description) instead of id=7 (key=admin.description).

![Screenshot 2019-11-30 at 13 36 29](https://user-images.githubusercontent.com/1251793/69900844-c926fc00-1378-11ea-9199-6b4d6b1c13b9.png)

**Comment by MrCrayon** [comment] 2019-11-30 13:41
That's because you are in Site Tab trying to update an Admin setting.
![Schermata da 2019-11-30 14-39-57](https://user-images.githubusercontent.com/6875243/69901247-5b320300-137f-11ea-832b-9c372afaa8a6.png)

Switch Tab and it will work.

**Comment by philippzentner** [comment] 2019-12-03 19:37
It should either display the correct inputs or update the correct fields.

**Comment by MrCrayon** [comment] 2019-12-04 00:43
It's showing the correct input as far as I know, but I understand your confusion. 

You are following these steps, correct me if I'm wrong: 
- Go on setting page, Site tab by default
- Change description
- Change option in select from Site to Admin
- Try to save

Third step is your problem, that select is there if you want to move your setting from one tab to another but since there is already an `admin. description` you get the duplicate key error.

Hope that clarified. 

Please let us know if that what's happening or list exact steps to reproduce the problem.

**Comment by philippzentner** [comment] 2019-12-05 11:29
Okay yes, exactly. I tried to reproduce the error and it fails if I for example change an information on the site-tab but the select on the right is on "Admin" - which last time must have happened by accident, which is why I was confused. But what is the point of the select then? If it produces an error, It shouldn't be possible to use it this way.

**Comment by emptynick** [comment] 2019-12-05 11:58
If you change the group of `site.title` to `admin` it will conflict with `admin.title` which already exists.
The select just lets you change the group of a setting.

**Comment by MrCrayon** [comment] 2019-12-06 05:09
I think we can close this.
@philippzentner if you have a suggestion on how to improve Settings interface you can open a feature request or even better propose a PR.

**Closed as completed by MrCrayon** 2019-12-06 05:09 UTC
