### ISSUE TITLE
Remove "None" value from BelongsToMany relationship

### ISSUE THREAD

**Issue by Vlad-Online** [thedevdojo/voyager#3770] opened 2018-11-29 14:14 UTC
## Version information
 - Laravel: v5.7.6
 - Voyager: v1.1.10
 - PHP: 7.2.10-0ubuntu0.18.04.1 
 - Database: mysql 14.14 Distrib 5.7.24
## Description
Hi! I've BelongsToMany relationship, and I want to remove "None" value. All columns in pivot table are not nullable, but I've "None" value first in dropdown. If I select None or nothing, I got a 500 error. So how to remove this value or add validation to relationship?
Thank you!

**Comment by emptynick** [comment] 2018-12-01 17:20
Please search before opening new issues.
Duplicate of #3625

**Closed as completed by emptynick** 2018-12-01 17:20 UTC
Labels: duplicate

**Comment by minhdanh** [comment] 2018-12-04 13:48
@emptynick 
How is this a duplicate of #3625 ?
The OP wants to remove "None" from the dropdown list, while in #3625, "None" is not displayed at all.

**Comment by emptynick** [comment] 2018-12-04 14:31
If your car only drives backwards, and other peoples cars only forwards its likely the same problem.
And it indeed is. See comments in #3625 
And it will be fixed in https://github.com/the-control-group/voyager/pull/3785
