### ISSUE TITLE
Can't install Voyager on a fresh new Laravel projet !

### ISSUE THREAD

**Issue by nacimux** [thedevdojo/voyager#1840] opened 2017-09-23 09:15 UTC
- Laravel Version: 5.5
- Voyager Version: 1.0
- PHP Version: 7.0.11
- Database Driver & Version: MySQL 5.7.14

### Description:

I have a fresh new installation of Laravel 5.5, i added Voyager's dependency via "composer require tcg/voyager".

The problem occur when i try to install voyager with "php artisan voyager:install" so i have these errors : 

```
1-   [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `translations` add unique `translati
  ons_table_name_column_name_foreign_key_locale_unique`(`table_name`, `column_name`, `foreign_key`, `locale`))
2 - [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is ```
1000 bytes

3 -   [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
```
Any idea how to solve this !

**Comment by nacimux** [comment] 2017-09-23 09:21
I solved this issue with deleting this part from "create_translations_table" migration files : 

`  $table->unique(['table_name', 'column_name', 'foreign_key', 'locale']);`

, but this way i think the translation part is broken ?

**Comment by vshapovalov** [comment] 2017-09-23 09:28
Hi, if you set utf8mb4 as default collation for db, try to set default string length to 191 with Schema facade, then install voyager

**Comment by alexandru-core** [comment] 2017-09-23 15:19
Did u try this 

https://laravel-news.com/laravel-5-4-key-too-long-error

**Comment by nacimux** [comment] 2017-09-23 16:19
utf8mb4 set as default, i olso set default lenght to 191 with Schema facade, waybe its due to my sql Version (55.7.14) ?

**Comment by vaggelis2018** [comment] 2017-09-25 11:46
This is not a voyager issue. If you update to Maria DB 10.2 this issue will be solved. Please close this thread.

**Comment by fletch3555** [comment] 2017-09-25 12:18
@vaggelis2018, while you're technically correct, it's still ours to fix since it's directly triggered by something we ship. We can't require users to change DBMS simply because we don't want to optimize our table indexes.  At the same time, the burden of properly managing your DBMS, does fall on the user, which is why this is a complex issue.

I believe the only reasonable fixes we could do are:
1) document the issue and suggested workarounds
2) change our indices so this doesn't happen
3) remove the index altogether

I'm going to throw out number 3, simply because it'll lead to inefficiency in the application and removes a point of validation (it's a combination of 4 fields set to unique).

Number 2 is possible, but takes a bit of research and planning.  There may be some optimizations we could take (maybe we don't need all 4 fields in that unique index)

Number 1 should be done regardless.  @mark has been fielding this question a lot in slack.  @mark, could you post the suggested work-arounds that you've been using?  Also, we should get those documented.

Thanks!

**Comment by vaggelis2018** [comment] 2017-09-26 18:33
@fletch3555  Sorry for the way i spoke but this issue has been mentioned too many times all over the internet. Here someone can find at least 3-4 different solutions. I think last time i tried to fix it nothing worked and had to get an old database cause most of the solutions was outdated or the solution is to just avoid using some features . I don't think it is a voyager issue. Looks like more than a laravel issue which has features compatible only with Maria Db 10.2. Really very annoying bug.

**Comment by fletch3555** [comment] 2017-09-26 18:55
No worries. I definitely understand the frustration.

The original issue is because laravel(or one of it's dependencies) changed the default character encoding used, which means each character requires 4 bytes instead of 1-2, leading to less available space for indices to make use of.

The reason I say this is our problem to fix is because we use a (unique) index that combines 4 fields, whose total length violates the size limit.

This was supposedly fixed in MySQL 5.7.7(or mariadb 10.2.2), but we need to be cognizant of what we're using for indices.

**Comment by mostadev** [comment] 2017-10-11 16:38
i made this change and worked for me
`$table->string('table_name')->unique();
            $table->string('column_name')->unique();
            $table->integer('foreign_key')->unsigned()->unique();
            $table->string('locale')->unique();

            $table->text('value');

            //$table->unique(['table_name', 'column_name', 'foreign_key', 'locale']);`

**Comment by osc2nuke** [comment] 2018-08-04 23:25
So how is this evolving?
Still not able to install.

**Comment by ycs77** [comment] 2019-05-10 09:15
There is a way to try:

*database/migrations/2017_01_14_005015_create_translations_table.php*
```php
    public function up()
    {
        Schema::create('translations', function (Blueprint $table) {
            $table->increments('id');

            $table->string('table_name', 80);
            $table->string('column_name', 80);
            $table->integer('foreign_key')->unsigned();
            $table->string('locale', 80);

            $table->text('value');

            $table->unique(['table_name', 'column_name', 'foreign_key', 'locale']);

            $table->timestamps();
        });
    }
```

table_name: 80 * 4bytes = 320bytes
column_name: 80 * 4bytes = 320bytes
foreign_key: 10 * 4bytes = 40bytes
locale: 80 * 4bytes = 320bytes

unique field: 320bytes + 320bytes + 40bytes + 320bytes = 1000bytes

**Just right!**

**Comment by jaikangam** [comment] 2019-05-17 09:44
This happens to me when I tried to install voyager. After few digging I found these two answers which working
try this on the /config/database.php

'mysql' => [
...,
...,
'engine' => null,
]

to
'mysql' => [
...,
...,
'engine' => 'InnoDB',
]

its work for me.

**Comment by JeepayJipex** [comment] 2019-05-17 21:34
thanks @Jaikangam93 

it worked for me too, by default my database was using MYISAM.

Change it to InnoDB in config/database.php was the only fix that worked.

**Comment by zhoujiate** [comment] 2019-07-26 06:14
I use MySQL 5.7.24 and have the issue too.
Like Jaikangam93 said, I edit the file in config/database.php

'mysql' => [
.....
'engine' => 'InnoDB ROW_FORMAT=DYNAMIC',  //instead of null, problem solved
.....
],

**Comment by hamzaahmadse** [comment] 2020-02-12 13:39
> This happens to me when I tried to install voyager. After few digging I found these two answers which working
> try this on the /config/database.php
> 
> 'mysql' => [
> ...,
> ...,
> 'engine' => null,
> ]
> 
> to
> 'mysql' => [
> ...,
> ...,
> 'engine' => 'InnoDB',
> ]
> 
> its work for me.

i works, but what is does actually, please explain?

**Comment by fletch3555** [comment] 2020-02-12 13:44
@HamzaAhmad932, it sets the database table storage engine to InnoDB.  Specifics on that are available online and have nothing to do with Voyager.

I'm going to close this now.  The original issue has been discussed ad nauseam in the laravel community, and is caused by a change made in newer mysql versions.

**Closed as completed by fletch3555** 2020-02-12 13:44 UTC
