### ISSUE TITLE
The user can normally level up to admin

### ISSUE THREAD

**Issue by saclychan** [thedevdojo/voyager#2224] opened 2017-11-14 13:36 UTC
- Laravel Version: 5.5.20
- Voyager Version:1.0.7
- PHP Version:7.1
- Database Driver & Version:

### Description:
The user can normally level up to admin

### Steps To Reproduce:
![0-user1](https://user-images.githubusercontent.com/5512429/32782563-6681536e-c97b-11e7-873b-2415b7154327.png)
![1 trick](https://user-images.githubusercontent.com/5512429/32782571-6a367426-c97b-11e7-84db-1b1fe613cd9d.png)
![2 become_adm in](https://user-images.githubusercontent.com/5512429/32782573-6c737284-c97b-11e7-8a57-1e96e3f16baf.png)

**Comment by fletch3555** [comment] 2017-11-14 19:31
Dupe of #2192.  Please remember to search through open issues before posting your own.

**Closed as completed by fletch3555** 2017-11-14 19:31 UTC
Labels: duplicate
