### ISSUE TITLE
Site logo in Voyager cannot save

### ISSUE THREAD

**Issue by adillamokhtar** [thedevdojo/voyager#3264] opened 2018-06-01 02:21 UTC
- Laravel Version:5.6
- Voyager Version: 1.1.1
- PHP Version:7.*
- Database Driver & Version: mySQL 

### Description:

I want to save site logo in voyager but it did not save. Why this happen?

**Comment by jannejava** [comment] 2018-06-01 08:25
This is fixed in 1.1.2 I think. https://github.com/the-control-group/voyager/issues/3059

**Comment by emptynick** [comment] 2018-06-01 09:17
@jannejava is correct.
Also this is a duplicate of a handful issues.

**Closed as completed by emptynick** 2018-06-01 09:17 UTC
Labels: duplicate
