### ISSUE TITLE
[Feature]Make itens clickables.

### ISSUE THREAD

**Issue by marcellopato** [thedevdojo/voyager#4099] opened 2019-04-22 20:51 UTC
## Version information

 - Laravel: v5.6
 - Voyager: v1.2
 - PHP: 7.2
 - Database: MySQL 8.0

## Description of problem
Could be awesome click on the name of a user so I can go to his details. 
It is like an item->detail page when click on id, name, i.e.

**Comment by emptynick** [comment] 2019-06-01 11:34
Duplicate of #2333

**Closed as completed by emptynick** 2019-06-01 11:34 UTC
Labels: duplicate
