### ISSUE TITLE
background image and icon always back to default if i dont chose image again.

### ISSUE THREAD

**Issue by mohsennaserikish** [thedevdojo/voyager#3109] opened 2018-05-01 08:20 UTC
- Laravel Version: 5.5
- Voyager Version: 1.1
- PHP Version: 7
- Database Driver & Version: mysql maria-db

Hi Dear,
when i go to setting and for example change site title or something else , if i dont chose image again all image change to default .
i dont want to select image again always  that edit some other text .
so how can i set image to prevent back to default ?
many thanks.

**Comment by emptynick** [comment] 2018-05-01 09:30
Please search before opening a new issue.
Duplicate of https://github.com/the-control-group/voyager/issues/3105 and #3059

**Closed as completed by emptynick** 2018-05-01 09:30 UTC
Labels: duplicate
