### ISSUE TITLE
[BUG] New language not showing in Locale

### ISSUE THREAD

**Issue by PeterPan73** [thedevdojo/voyager#4062] opened 2019-04-05 08:05 UTC
## Version information

 - Laravel: v5.8.8
 - Voyager: v1.2.2
 - PHP: 7.2
 - Database: MySQL 8.0

## Description

If you add an additional language to '..\resources\lang\vendor\voyager\bg' it will not show up at Add/Edit user Locale. This bug come from [Voyager.php -> getLocales](https://github.com/the-control-group/voyager/blob/b00a09028a264c3ed61b39d0fa6db9928a506bb9/src/Voyager.php#L325)
check only in '..\vendor\tcg\voyager\publishable\lang' but not in '..\resources\lang\vendor\voyager'

## Steps To Reproduce
1. Go to '..\vendor\tcg\voyager\publishable\lang' and copy 'en' folder
3. Paste 'en' folder in  '..\resources\lang\vendor\voyager' and rename to 'bg' e.g
4. Go to Voyager Admin panel click Add/Edit user Locale section
5. 'bg' locale will not show in dropdown

**Comment by emptynick** [comment] 2019-04-05 08:18
Please search before opening new issues.
Closing as a duplicate of https://github.com/the-control-group/voyager/issues/4026

**Closed as completed by emptynick** 2019-04-05 08:18 UTC
Labels: duplicate
