### ISSUE TITLE
[BUG] Cannot remove BelongsTo relation 

### ISSUE THREAD

**Issue by gelinger777** [thedevdojo/voyager#4244] opened 2019-07-05 15:48 UTC
## Version information

 - Laravel: v5.8
 - Voyager: v1.2.6
 - PHP:7.2
 - Database: Mysql 
## Description

My Problem is on simple BelongsTo Relation. It works perfect when I am configuring it, and adding an entry with a relation. But when It comes to editing entry and removing the relation, 
I don't find any functionality  to do so. I can only chose another entry from related table as an option but not setting it to null or 0. 

## Steps To Reproduce
1. Create a simple category -> subcategry structure with category table id, title and subcategory table with id, category_id , title  where  category_id   holds 1->1 relation 
2. Make a bread on Subcategory Table , then create a BelongsTo relation for category_id field  pointing to id, title of category
3. Click on browse bread and add a new subcategory which is linked to any of existing category, save 
4. Go to Edit that specific subcategory . 
5. Try to set the parent category to NONE 

![image](https://user-images.githubusercontent.com/184276/60733305-bab0f180-9f4c-11e9-915f-32f349ab18ed.png)
 

## Expected behavior

There should be some NONE Option in dropdown, or a  Delete button  like this 

![image](https://user-images.githubusercontent.com/184276/60733374-f8157f00-9f4c-11e9-9b12-a535d36ffd06.png)

P.S Asked for help in slack with no result

**Comment by emptynick** [comment] 2019-07-05 15:51
Please show us the whole bread-settings for that BREAD.

**Comment by gelinger777** [comment] 2019-07-05 15:54
@emptynick 

![image](https://user-images.githubusercontent.com/184276/60733696-ef717880-9f4d-11e9-9771-618d4ae48c54.png)

**Comment by gelinger777** [comment] 2019-07-05 15:55
And the relations 

![image](https://user-images.githubusercontent.com/184276/60733754-19c33600-9f4e-11e9-82aa-7813364a9f4c.png)

**Comment by emptynick** [comment] 2019-07-05 16:01
So I guess `category_id` is the field you are saving your relationship in?
If the field is not required, it should display a none-option.
See:
https://github.com/the-control-group/voyager/blob/3516848eb558344773ac06b613c6dc924e238336/resources/views/formfields/relationship.blade.php#L36-L38

**Comment by gelinger777** [comment] 2019-07-05 16:11
@emptynick  And where do I set that field as not required?  Maybe in model?

**Comment by emptynick** [comment] 2019-07-05 16:14
If the field in your database-table is nullable it is not required.
But your category_id field says its not required already.

**Comment by gelinger777** [comment] 2019-07-05 16:14
exatly that's the problem...

**Comment by gelinger777** [comment] 2019-07-05 16:16
As you can see it is NULL ... 

![image](https://user-images.githubusercontent.com/184276/60734666-f483f700-9f50-11e9-8162-15e428d17907.png)

**Comment by gelinger777** [comment] 2019-07-05 16:19
Can the reason be the fact I am using MariaDB instead of MySQL? 

mysql  Ver 15.1 Distrib 10.2.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
??

**Comment by gelinger777** [comment] 2019-07-06 13:04
@emptynick  I have tried it also on MySql server, so the same thing happens. Any ideas what can be the reason?

**Comment by fletch3555** [comment] 2019-07-07 02:41
@gelinger777 can you attempt to debug it a little?  Find the line @emptynick mentioned and `dump()` the value of `$row->required`.  If it seems correct, then something else is overriding the values for your dropdown.  If (more likely) it's incorrect, then find where `$row` is instantiated and see where that value is coming from

**Comment by gelinger777** [comment] 2019-07-07 19:59
@fletch3555  @emptynick  


I have made 


```
                    @php

                 echo json_encode($row);
                 @endphp
```

![image](https://user-images.githubusercontent.com/184276/60773175-f345fc00-a101-11e9-8889-09018eb43245.png)

As you can see required:0 . 


I have looked at html  structure .. actually as I can see , the none option is there but not shown in dropdown 

```

<select class="form-control select2-ajax select2-hidden-accessible" name="category_id" data-get-items-route="https://evoality.local/admin/evo-subcategories/relation" data-get-items-field="evo_subcategory_belongsto_evo_category_relationship" data-method="edit" data-select2-id="1" tabindex="-1" aria-hidden="true">
                    
                                            <option value="" data-select2-id="2">None</option>
                    
                                            <option value="1" selected="&quot;selected&quot;" data-select2-id="3">Hot Topics</option>
                                    </select>
```


Maybe this is bug of Select2???

**Comment by gelinger777** [comment] 2019-07-07 20:25
From what I see, the  options  which are generated in the  voyager/resources/views/formfields/relationship.blade.php  are totally ignored in edit mode  when it comes to select2-ajax and only ajax values are taken in account.
 None option is only visible in Add Mode, but when you click on the dropdown it does not show up in the list. So I think it would be logical to have  remote method populate  none option in json when !$row->required .  Could you hint exactly where is that json generated?

**Comment by hitech95** [comment] 2019-07-09 22:31
Yup, it's AJAX, take a look here: #4249

**Comment by emptynick** [comment] 2019-07-18 16:04
Closing as a duplicate of https://github.com/the-control-group/voyager/issues/4031

**Closed as completed by emptynick** 2019-07-18 16:04 UTC
Labels: duplicate
