### ISSUE TITLE
 The title of menus item isn't showing (when edit)

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#3184] opened 2018-05-15 14:06 UTC
- Laravel Version: 5.6.22
- Voyager Version: 1.1
- PHP Version: 7.1
- Database Driver & Version: mySql 5.7

### Description:

When try to edit the title of menu item, the field is empty.(save is working normally)

### Steps To Reproduce:

1.Turn on voyager translations
2.Go to menus builder
3.Edit any menu item

![image](https://user-images.githubusercontent.com/39305343/40061731-46a7d5f6-5862-11e8-81ce-9f23897f8bd5.png)

**Comment by emptynick** [comment] 2018-05-15 14:15
Please search before opening a new issue.
Duplicate of https://github.com/the-control-group/voyager/issues/2731

**Closed as completed by emptynick** 2018-05-15 14:15 UTC
Labels: duplicate
