### ISSUE TITLE
can't save when Bread model has a multi select with relationship

### ISSUE THREAD

**Issue by callect** [thedevdojo/voyager#984] opened 2017-03-21 09:32 UTC
- Laravel Version: 5.4.*
- Voyager Version: 0.11.7
- PHP Version: 7.0.13
- Database Driver & Version:

### Description:

I can't save custom Bread form when it has a multi select with relationship .
laravel thown the error:

BadMethodCallException in Builder.php line 2450:
Call to undefined method Illuminate\Database\Query\Builder::tags_id()

### Steps To Reproduce:
model news

```
class News extends Model
{
    public $timestamps = false;
    public function tagsId(){
      return $this->belongsToMany(Tag::class);
    }
}
```
model tag
`class Tag extends Model
{
    public $timestamps = false;
}
`
news Bread
![2](https://cloud.githubusercontent.com/assets/15102717/24140691/e785d574-0e5b-11e7-8836-c4d08a99be22.jpg)
tags BREAD
![3](https://cloud.githubusercontent.com/assets/15102717/24140755/191994d6-0e5c-11e7-9892-ccb8bd8e43bc.jpg)
table:news_tag 
![4](https://cloud.githubusercontent.com/assets/15102717/24140795/42b85a48-0e5c-11e7-9001-25a98dcb5425.jpg)
then i add/edit news ,I got the error
![1](https://cloud.githubusercontent.com/assets/15102717/24140826/600a1a14-0e5c-11e7-8136-11d6dd1a30d3.jpg)

**Comment by Frondor** [comment] 2017-03-21 10:20
I'm pretty sure that relationship is wrong but please, try going to this file `vendor/tcg/voyager/src/http/Controllers/Controller.php`

Then go to line 86: https://github.com/the-control-group/voyager/blob/master/src/Http/Controllers/Controller.php#L86

change
`$multi_select[] = ['row' => $row->field, 'content' => $content];`
to
`$multi_select[] = ['row' => camelCase($row->field), 'content' => $content];`

save and try again.

Self note: If that works, we should modify `$row->field` directly from the view, not that line, it's just for testing.

**Comment by callect** [comment] 2017-03-21 10:31
yes i think that is reason.
before you reply me,i modify the line 109 to:
`$data->tagsId()->sync($sync_data['content']);`
then it works,but that is test code

I edit code with your reply but got 
`Call to undefined function TCG\Voyager\Http\Controllers\camelCase()`
where do i find function camelCase ?

**Comment by callect** [comment] 2017-03-21 11:08
I use a php function resolve this error 
```
function camelCase($str) {
    $i = array("-","_");
    $str = preg_replace('/([a-z])([A-Z])/', "\\1 \\2", $str);
    $str = preg_replace('@[^a-zA-Z0-9\-_ ]+@', '', $str);
    $str = str_replace($i, ' ', $str);
    $str = str_replace(' ', '', ucwords(strtolower($str)));
    $str = strtolower(substr($str,0,1)).substr($str,1);
    return $str;
}
```
but when i browse list page of this BREAD,i got new error 
`Undefined index: name`

**Comment by Frondor** [comment] 2017-03-21 14:07
No, `camel_case` is a laravel helper, you don't have to provide your own function for it.
https://laravel.com/docs/5.4/helpers#method-camel-case

I just realized I had it wrong at first, its `camel_case` instead of `camelCase`.

Don't modify anything, get everything back to default and do only the change I suggested.

**Comment by callect** [comment] 2017-03-21 14:50
OK，thank you，I will try it later.
Did you See another error ? Dose Multi select can browse? why laravel shown a undefined index: name error.

**Comment by nunomsh** [comment] 2017-03-21 22:04
In the news BREAD uncheck the  tags_id. It will work, BUT it wont show the item in the browse view, neither in the read view. The problem is not in the code sugest by @Frondor , because I use similar names the cameCase and it works fine.
Just a note, set the id input type to NUMBER, no checkbox

I have a similar issue when the simple dropdown is use, relation belongsTo(), it only shows the id, not the title of the relation.
I've read the documentation and from what I understand if you pass to page in the options, it would show the name:
`{
    "relationship": {
        "key": "id",
        "label": "name",
        "page_slug": "admin/users"
    }
}`

But it only shows the id of the realation, not the title of the item. I'm not certain, but I guess it could be the partials and the read view have some issue

**Comment by Frondor** [comment] 2017-03-22 03:29
We may be talking about many issues at the same time. 
Multi-select is not widely tested at the moment, and it may have some issues with page slugs.

Anyway, some weeks ago there was a PR that made BREADs work with specific columns instead of IDs to make URLs more "friendly" I suppose, probably it didn't supported this `formField`.

**Comment by callect** [comment] 2017-03-22 05:41
I resolved this error ,it's work well now.
I modified some code in \vendor\tcg\voyager\src\Http\Controllers\Traits\BreadRelationshipParser.php and \bread\browse.blade.php
Should I commit it to pr ?

**Comment by Frondor** [comment] 2017-03-22 07:04
@callect Show us what you wrote, here please.

**Comment by callect** [comment] 2017-03-22 07:24
1. voyager\src\Http\Controllers\Traits\BreadRelationshipParser.php line 104 
change 
`$item[$field] = $relation[$relationData->label];`
to 
```
if (is_array($relation->all())) {
    $label_arr = [];
    foreach ($relation->all() as $relationItem) {
        $label_arr[] = $relationItem->name;
    }
    $item[$field] = $label_arr;
} else {
    $item[$field] = $relation[$relationData->label];
}
```

2. voyager\resources\views\bread\browse.blade.php line 42
change
```
@if(property_exists($options, 'relationship'))

    @foreach($data->{$row->field} as $item)
        @if($item->{$row->field . '_page_slug'})
        <a href="{{ $item->{$row->field . '_page_slug'} }}">{{ $item->{$row->field} }}</a>@if(!$loop->last), @endif
        @else
        {{ $item->{$row->field} }}
        @endif
    @endforeach

    {{-- $data->{$row->field}->implode($options->relationship->label, ', ') --}}
@elseif(property_exists($options, 'options'))
    @foreach($data->{$row->field} as $item)
     {{ $options->options->{$item} . (!$loop->last ? ', ' : '') }}
    @endforeach
@endif
@if ($data->{$row->field} && isset($options->relationship))
    {{ $data->{$row->field}->implode($options->relationship->label, ', ') }}
@endif
```
to
```
@if(property_exists($options, 'relationship'))
    {{ implode($data->{$row->field}, ', ') }}
@elseif(property_exists($options, 'options'))
    @foreach($data->{$row->field} as $item)
     {{ $options->options->{$item} . (!$loop->last ? ', ' : '') }}
    @endforeach
@endif
```
I just want display multi_select value,so I removed branch page_slug.
Maybe I don't understand,but I think this branch is repeat ,so I removed it:
```
@if ($data->{$row->field} && isset($options->relationship))
    {{ $data->{$row->field}->implode($options->relationship->label, ', ') }}
@endif
```

**Comment by Frondor** [comment] 2017-03-22 07:38
No, we can't implement that. You're adding some extra queries and completely broke the relationship anchor link. We'll have to study what's really wrong here and properly implement it

We can blame this PR #715 
I never liked but got merged, sadly. So now we have to fix that mess.

**Comment by callect** [comment] 2017-03-22 08:56
ok,it dosen't matter. I realized my code is not  widely now.

**Comment by nunomsh** [comment] 2017-03-22 13:06
Got it "working", but it's not the perfect solution. If you like to try it:
In the voyager\src\Http\Controllers\Traits\BreadRelationshipParser.php line 103
Replace 
```
if (!is_object($item[$field])) {
    $item[$field] = $relation[$relationData->label];
} else {
    $tmp = $item[$field];
    $item[$field] = $tmp;
}
if (isset($relationData->page_slug)) {
    $id = $relation->id;
    $item[$field.'_page_slug'] = url($relationData->page_slug, $id);
}
```
for
```
$tmp = $item[$field];
$item[$field] = $tmp;
```

And in the browse.blade.php line 42 replace the "multiple block" for 
```
@elseif($row->type == 'select_multiple')
@if(property_exists($options, 'relationship'))
    
        @foreach($data['relations'][$row->field] as $item)
        
        <span class="label label-info">
          {{ $item->title}}  
        </span>
        @if(!$loop->last)
           
            @endif
        @endforeach

    @elseif(property_exists($options, 'options'))
        @foreach($data->{$row->field} as $item)
         {{ $options->options->{$item} . (!$loop->last ? ', ' : '') }}
        @endforeach
    @endif
```

In my case I'm not using the link to the item. If you want to use it just replace the `<span>` for 
```
<a href="{{ $options->relationship->page_slug}}/{{$item->id}}">
 {{ $item->title}}  
</a>
```
![voyager_relations](https://cloud.githubusercontent.com/assets/2600175/24199074/401a9fae-0f00-11e7-8c78-09f82e39f177.png)
![voyager_browse](https://cloud.githubusercontent.com/assets/2600175/24199080/469b1e62-0f00-11e7-8b25-b63868dcd323.png)
![voyager_result](https://cloud.githubusercontent.com/assets/2600175/24199086/4b3aada2-0f00-11e7-82c3-bb1ab29168f2.png)

Not the perfect soultion but it may help

**Comment by fletch3555** [comment] 2017-03-25 16:19
@nunomsh, you realize this code does nothing, right? 

```
$tmp = $item[$field];
$item[$field] = $tmp;
```

**Comment by nunomsh** [comment] 2017-03-25 18:39
Yes, I do, but as you can confirm this is exactly what the original code does.. ;) 
Like I said, this is not THE solution, and the main changes are in the view

**Comment by Frondor** [comment] 2017-03-25 23:49
I'm rewriting the whole relationship linking because #715 broke it in many ways. When ready, I'll send the PR to get some help.

**Comment by handiwijoyo** [comment] 2018-01-08 11:28
Voyager `1.0` implement new relationship system. Please check it out. Close this for now.

**Closed as completed by handiwijoyo** 2018-01-08 11:28 UTC
Labels: type:bug, help wanted, refactor

**Comment by cbascordoba** [comment] 2019-03-26 15:40
> Got it "working", but it's not the perfect solution. If you like to try it:
> In the voyager\src\Http\Controllers\Traits\BreadRelationshipParser.php line 103
> Replace
> 
> ```
> if (!is_object($item[$field])) {
>     $item[$field] = $relation[$relationData->label];
> } else {
>     $tmp = $item[$field];
>     $item[$field] = $tmp;
> }
> if (isset($relationData->page_slug)) {
>     $id = $relation->id;
>     $item[$field.'_page_slug'] = url($relationData->page_slug, $id);
> }
> ```
> for
> 
> ```
> $tmp = $item[$field];
> $item[$field] = $tmp;
> ```
> And in the browse.blade.php line 42 replace the "multiple block" for
> 
> ```
> @elseif($row->type == 'select_multiple')
> @if(property_exists($options, 'relationship'))
>     
>         @foreach($data['relations'][$row->field] as $item)
>         
>         <span class="label label-info">
>           {{ $item->title}}  
>         </span>
>         @if(!$loop->last)
>            
>             @endif
>         @endforeach
> 
>     @elseif(property_exists($options, 'options'))
>         @foreach($data->{$row->field} as $item)
>          {{ $options->options->{$item} . (!$loop->last ? ', ' : '') }}
>         @endforeach
>     @endif
> ```
> In my case I'm not using the link to the item. If you want to use it just replace the `<span>` for
> 
> ```
> <a href="{{ $options->relationship->page_slug}}/{{$item->id}}">
>  {{ $item->title}}  
> </a>
> ```
> ![voyager_relations](https://cloud.githubusercontent.com/assets/2600175/24199074/401a9fae-0f00-11e7-8c78-09f82e39f177.png)
> ![voyager_browse](https://cloud.githubusercontent.com/assets/2600175/24199080/469b1e62-0f00-11e7-8b25-b63868dcd323.png)
> ![voyager_result](https://cloud.githubusercontent.com/assets/2600175/24199086/4b3aada2-0f00-11e7-82c3-bb1ab29168f2.png)
> 
> Not the perfect soultion but it may help


**how did you add the export buttons ??**

**Comment by emptynick** [comment] 2019-03-26 15:53
There's a built-in way to add mass-actions and its mentioned in the docs.
