### ISSUE TITLE
Error No Database connection yet in VoyagerServiceProvider loadAuth()

### ISSUE THREAD

**Issue by cotiga** [thedevdojo/voyager#5339] opened 2021-05-26 22:20 UTC
## Version information
 - Laravel: 8.42.1
 - Voyager: 1.4.2
 - PHP: 7.4.3
 - Database: MySQL 8.0

## Description
I end up with a recurring errors that doesn't seem to be a problem for my app (but populated my log file).
This error occurs even outside Voyager admin panel.

[datetime] local.ERROR: No Database connection yet in VoyagerServiceProvider loadAuth()

**Comment by emptynick** [comment] 2021-05-27 06:29
Please search before opening issues.
Duplicate of https://github.com/the-control-group/voyager/issues/5285, https://github.com/the-control-group/voyager/issues/5069 and https://github.com/the-control-group/voyager/issues/4045

**Closed as completed by emptynick** 2021-05-27 06:29 UTC
Labels: duplicate

**Comment by cotiga** [comment] 2021-05-27 08:31
I had watched carefully before opening my issue, and messages like: "This is just a warning, not an error" does not suit me, thank you!
Voyager seems to be at a standstill and is proving to be more and more buggy, I will take my time to create my own administration panel.
Thank's for your work, but Pity :(

**Comment by emptynick** [comment] 2021-05-27 12:08
But it's true, when we'd delete that line no one would notice (I actually thought about removing it).
It's just saying that there is no database connection yet and will try again later.

Saying that Voyager is dead is not correct at all. We are still merging PRs.
Beside that we are working hard on V2 which is why merging/releasing/triaging is just a bit slower at the moment.

**Comment by emptynick** [comment] 2021-05-27 18:52
Quoted from https://github.com/the-control-group/voyager/issues/5285

> The error messages was "softened" and is now an information.
This message (No database connection yet in VoyagerServiceProvider loadAuth()) can be ignored safely and is definitely not the cause of any problems mentioned here.
