### ISSUE TITLE
Laravel Voyager: Undefined variable: dataRow when Add BREAD to this table!

### ISSUE THREAD

**Issue by cuongcx87** [thedevdojo/voyager#3666] opened 2018-10-21 10:20 UTC
## Version information

 - Laravel: v5.7.9
 - Voyager: v1.1
 - PHP: 7.2.2
 - Database: MySQL 5.7.19

**Comment by emptynick** [comment] 2018-10-21 10:31
Please search before opening new issues.
This has been fixed in 1.1.8/9 and is a duplicate of https://github.com/the-control-group/voyager/issues/3646

**Closed as completed by emptynick** 2018-10-21 10:31 UTC
Labels: duplicate

**Comment by cuongcx87** [comment] 2018-10-21 10:42
Thank you!
