### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#3879] opened 2019-01-09 11:10 UTC
## Version information

 - Laravel: v5.7.19
 - Voyager: v1.1.10
 - PHP: 7.2
 - Database: MySQL 5.7.21

## Description

ErrorException (E_ERROR)
count(): Parameter must be an array or an object that implements Countable (View: resources/views/vendor/voyager/events/browse.blade.php)

## Steps To Reproduce
1. Just create a new BREAD Events
2. Then when trying to create first event 
3. Then on the Event List page, it shows this error
4. The error is somewhere in this line, in the 

File- project/vendor/tcg/voyager/resources/views/bread/browse.blade.php 
Line number - 112
Line - @if (count(json_decode($data->{$row->field})) > 0)

**Comment by emptynick** [comment] 2019-01-09 11:13
> (View: resources/views/vendor/voyager/events/browse.blade.php)

And
> File- project/vendor/tcg/voyager/resources/views/bread/browse.blade.php

Is not the same. Thats your custom view.

**Comment by ghost** [comment] 2019-01-09 11:21
Hello,

I just made a custom view by copying the code from the project/vendor/tcg/voyager/resources/views/bread/browse.blade.php

And by the way in my custom file, I just fixed the issue by doing-
from this-
@if (count(json_decode($data->{$row->field})) > 0)

to this-
@if (!empty(json_decode($data->{$row->field})))

Because in PHP 7.* versions, if we pass an empty array to count(), then it returns an error.

Is not the same. That's your custom view.

**Comment by emptynick** [comment] 2019-01-14 15:09
Are you able to create a PR for this?

**Comment by stefanos82** [comment] 2019-01-29 00:30
@classiebit I remember this silly thing from PHPMyAdmin. 

Your original code is 
```php
@if (count(json_decode($data->{$row->field})) > 0)
```

Can you try wrapping your count inside parentheses?
 
```php
@if ((count(json_decode($data->{$row->field}))) > 0)
```
This should resolve the issue.

**Comment by suhaboncukcu** [comment] 2019-02-13 10:55
The problem is that with PHP7.X versions only entities implementing Countable interface can be used as a countable and `count()` function is only able to use countables. So while `count(json_decode('{}', true))`  is working as expected, `count(json_decode('{}'))` will throw an error. (check this: https://3v4l.org/4JF9V) 


But anyway, I guess checking the condition with `empty` would be more performant than counting the vals and checking the result with `> 0` 

I can open a detailed PR if nobody is picking this up.

**Comment by stefanos82** [comment] 2019-02-13 12:00
In the http://php.net/manual/en/function.json-decode.php explains it clearly why the use of `true` make it work as expected: 

![image](https://user-images.githubusercontent.com/1777466/52710284-a49f9600-2f97-11e9-9a73-68d04dcbdc4b.png)

**Comment by suhaboncukcu** [comment] 2019-02-13 14:37
> In the http://php.net/manual/en/function.json-decode.php explains it clearly why the use of `true` make it work as expected:
> 
> ![image](https://user-images.githubusercontent.com/1777466/52710284-a49f9600-2f97-11e9-9a73-68d04dcbdc4b.png)

that's why I said that :) arrays, even when they're empty, are countable.

**Comment by stefanos82** [comment] 2019-02-13 15:02
Yes, but `json_decode` without the explicit use of the second argument, it defaults to `false`, therefore it's not converted to associative array.

**Comment by emptynick** [comment] 2019-02-25 08:32
Fixed in https://github.com/the-control-group/voyager/pull/3909 commit https://github.com/the-control-group/voyager/pull/3909/commits/469dad1b1616bfcde0111ef9300d6a746653adbc

**Closed as completed by emptynick** 2019-02-25 08:32 UTC
Labels: type:bug, help wanted
