### ISSUE TITLE
Permissions not saved when editing a role.

### ISSUE THREAD

**Issue by fuzzyjared** [thedevdojo/voyager#4806] opened 2020-03-04 15:29 UTC
## Version information

 - Laravel: v6.18.0
 - Voyager: v1.3.1
 - PHP: 7.3
 - Database: MariaDB 10.4.12

## Description
Permissions are not saved when editing a role. 

## Steps To Reproduce
1. Go to Roles and click edit on any role.
2. Modify the Permissions via the supplied checkboxes.
3. Click Submit.
4. You will be redirected to the Roles Browse page with a success message.
5. Click on Edit on the same Role that you just submitting the permission changes on and you will see that the roles were not saved.

## Expected behavior
Modifying the permissions through the Role edit form should save those changed values.

## Screenshots
![image](https://user-images.githubusercontent.com/1541668/75894629-21e3b600-5dfa-11ea-93bc-dc9ec4676a01.png)
![image](https://user-images.githubusercontent.com/1541668/75894649-28722d80-5dfa-11ea-90d4-ae4d962ac39c.png)
![image](https://user-images.githubusercontent.com/1541668/75894666-2dcf7800-5dfa-11ea-8fa6-be0095683cca.png)

## Additional context
A new installation of laravel and voyager without any modifications or additional libraries added. No custom gates or permissions created.

**Comment by emptynick** [comment] 2020-03-04 15:44
Please search before opening issues.
Duplicate of https://github.com/the-control-group/voyager/issues/4791 and https://github.com/the-control-group/voyager/issues/4668

**Closed as completed by emptynick** 2020-03-04 15:44 UTC
Labels: duplicate
