### ISSUE TITLE
419

### ISSUE THREAD

**Issue by jatinkumar09** [thedevdojo/voyager#4399] opened 2019-09-09 16:50 UTC
## Version information
 - Laravel: v6.0.0
 - Voyager: ^1.2
 - PHP: 7.2
 
Hi 
I am trying to deploy laravel with voyager on a Digital Ocean Server via cloudways . The login/Signup keeps giving 419 , I have tried all available online solutions .

**Comment by emptynick** [comment] 2019-09-09 16:52
Please search before opening new issues.
Duplicate of #4386, #4383, #4380, #4376, #4395 and #4392

Also note that our Readme explicit states that we only support Laravel 5.5 to 5.8 at the moment.

**Closed as completed by emptynick** 2019-09-09 16:52 UTC
Labels: duplicate

**Comment by jatinkumar09** [comment] 2019-09-09 18:38
Hi 
I just installed laravel 5.8 and tried getting same error on server . no matter what i try I am unable to login/signup

**Comment by AdelNamani** [comment] 2020-05-17 01:40
> ## Version information
> * Laravel: v6.0.0
> * Voyager: ^1.2
> * PHP: 7.2
> 
> Hi
> I am trying to deploy laravel with voyager on a Digital Ocean Server via cloudways . The login/Signup keeps giving 419 , I have tried all available online solutions .

@jatinkumar09 I am facing exactly the same problem, and it's on cloudways too, can you tell me how did you solve this problem please ?

**Comment by jatinkumar09** [comment] 2020-05-17 08:36
Hi 
I was unable to solve this . But as per my experience issue may be with varnish cache on cloudways . Try disabling it and then try .

**Comment by AdelNamani** [comment] 2020-05-17 09:18
@jatinkumar09 I think it's working after deactivating varnish, thank's a lot
