### ISSUE TITLE
Migration file is not marked as migrated

### ISSUE THREAD

**Issue by marktopper** [thedevdojo/voyager#956] opened 2017-03-17 10:45 UTC
- Laravel Version: x.x.x
- Voyager Version: 0.11.7
- PHP Version: 7.1.1
- Database Driver & Version: MySQL

### Description:
When creating or editing a table in the Voyager database section while enabling the `Create migration` option.
Then a migration is created and the database changes are done but the migration file is not marked as migrated, and will try to create the table once again if someone runs `php artisan migrate`.

**Comment by marco-solare** [comment] 2017-03-17 11:17
what is the reason for that?
I guess it is not added to the "migrated" table?

**Comment by preginald** [comment] 2017-03-17 11:27
I experienced this issue on a fresh installation of Laravel and Voyager. This was my workflow.

1. new laravel app

2. install voyager (no dummy content) 

3. create admin user

4. log in 

5. create new table via 'Voyager\Create New Table'

6. entered 'projects' table name 

7. Create model = yes

8. Create migrations for this table = yes 

9. added one column = "name" 

10 Create New Table

**Result**

I could see a new 'create_projects_table' migrations file is created however the migration didn't run  (confirmed via php artisan migration:status)

Also the migration file had 'id' and 'time stamps' but not the 'name' column' that I specified in Voyager\Database.

When I 'described' the table via mysql cli I can see the 'projects' table created by voyager and it only has the one column 'name' and not 'id' or 'created_at & updated_at' as I expected.

When I delete the table created via voyager then the table does get dropped in mysql.

The second time I created a new 'projects' table via Voyager\Database with 'id', 'name', 'created_at', 'updated_at' columns. The migration file was created but didn't run according to migrate:status.

Also, the migration file that voyager created only has 'id' and 'timestamps' columns, it is missing the 'name' column so even if that migration file did run then it would not have created the 'name' column I want in the 'projects' table.

As a work around I was able to delete the 'projects' table via Voyager\Database,  create the migration file manually.

**Comment by abdgad** [comment] 2017-03-17 12:19
Since Voyager only generates a partial migration at the moment, we should simply remove that option, and bring it back when we have full migration generation support.

**Comment by abdgad** [comment] 2017-03-17 12:24
@preginald which version of Voyager are you using?

**Comment by abdgad** [comment] 2017-03-17 21:06
Note: keep this open as a future reminder.

**Comment by preginald** [comment] 2017-03-17 22:50
@abdgad 

```
        "php": ">=5.6.4",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0",
        "tcg/voyager": "^0.11.7"
```

**Comment by fletch3555** [comment] 2017-08-31 19:17
I'm going to close this due to age.  The migration generation feature has been removed and will be re-implemented from scratch.

**Closed as completed by fletch3555** 2017-08-31 19:17 UTC
Labels: type:bug
