### ISSUE TITLE
[BUG] rich text fields multilanguage error

### ISSUE THREAD

**Issue by trippo** [thedevdojo/voyager#4112] opened 2019-04-30 18:25 UTC
- Laravel: v5.8.15
 - Voyager: v1.2.3
 - PHP: 7.2
 - Database: MySQL 8.0

## Description
Multilanguage rich text fields can't change language. In the version 1.2.2 this work fine.
If you change language the tinymce editor stuck on the same version

## Screenshots
![image](https://user-images.githubusercontent.com/497169/56984323-0aa6bd00-6b86-11e9-8f87-7912ddc67f08.png)

**Comment by emptynick** [comment] 2019-04-30 18:26
Please search before opening new issues.
Duplicate of https://github.com/the-control-group/voyager/issues/4072

**Closed as completed by emptynick** 2019-04-30 18:26 UTC
Labels: duplicate
