### ISSUE TITLE
can't save

### ISSUE THREAD

**Issue by liziliang123** [thedevdojo/voyager#3421] opened 2018-07-27 01:19 UTC
## Version information

 - Laravel: v5.5.*
 - Voyager: v1.1.*
 - PHP: 7.1
 - Database: [MySQL 5.6] 

## Description

can't  save

## Steps To Reproduce
1. Go to 'admin'  ,  edit the posts or other
2. Click on 'save'
3. See error

## Expected behavior
app.js:24 Uncaught TypeError: r.set is not a function

## Additional context
after installed ,can't save page 、posts or other .
then the app.js error :app.js:24 Uncaught TypeError: r.set is not a function

**Comment by emptynick** [comment] 2018-08-07 20:54
Duplicate of https://github.com/the-control-group/voyager/issues/3419

**Closed as completed by emptynick** 2018-08-07 20:54 UTC
Labels: duplicate

**Comment by hooch** [comment] 2018-09-16 01:57
Should be fixed by #3546
