### ISSUE TITLE
Use prefix for voyager tables

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#4631] opened 2019-12-15 22:36 UTC
Yeah, it's me again...

## Description of problem
I think users should be able to use whatever names they like for their application's tables and models. Laravel only defines 3 tables by default:
- migrations
- users
- password_resets

They can all be configured:
- `password_resets` in `config/auth.php`
- `migrations` in `config/database.php`
- `users`: change the migration and the table name in the model

This allows developers to have a `migrations` table to store information about birds migrations if they like.

## Proposed solution
Since the installation process does not really allow users to edit the migrations (`artisan voyager:install` runs the migrations from the vendor directory), use a prefix for the tables specific to Voyager.

## Alternatives considered
If you want a `menu` table for a restaurant, use a different slug. Inconvenient: it will be displayed to a user who does not even know there is a `menu` *menu* which is used for another purpose.

**Comment by MrCrayon** [comment] 2019-12-16 04:57
Duplicate of #1014

I think you are looking for this #4538 

> Since the installation process does not really allow users to edit the migrations (artisan voyager:install runs the migrations from the vendor directory), use a prefix for the tables specific to Voyager.

Migrations can be overriden, you just need to copy it in your migration folder.

Finding issues and giving suggestions is appreciated but please search before if there is already an issue / PR opened.

**Closed as completed by MrCrayon** 2019-12-16 04:57 UTC
Labels: duplicate
