### ISSUE TITLE
Laravel 6, route('voyager.bread.create', ['name' => $table->name]) not working

### ISSUE THREAD

**Issue by sadart** [thedevdojo/voyager#4386] opened 2019-09-06 14:45 UTC
## Version information

 - Laravel: v6.0.0 & 6.0.1
 - Voyager: v1.2
 - PHP: 7.2
 - Database: mysql  Ver 14.14 Distrib 5.7.27

## Description

Named routes route('voyager.bread.create', ['name' => $table->name]) for admin/bread/{table}/create doesn't work in laravel 6

## Steps To Reproduce
1. Install a fresh copy of laravel
2. Install voyager with dummy data
3. Run php artisan serve
4. Go to host:port/admin
5. Enter admin@admin.com for email and 'password' for password
6. To to Tools->Databases
7. Click on 'Add BREAD to this table' button for 'failed_jobs' table
8 http://IP:PORT/admin/bread//create?name=failed_jobs

## Expected behavior
Step 7 above should produce
http://IP:PORT/admin/bread/failed_jobs/create

## Screenshots

![Screenshot from 2019-09-06 14-36-53](https://user-images.githubusercontent.com/2045059/64436940-da7fa580-d0b4-11e9-8d12-d27b18dd89a2.png)

## Additional context
Test on Laravel 5.8.34 didn't produce this error. Error occurs only in Laravel 6
Laravel < 6 seems flexible on named route params placeholders. I can see Laravel 6 strictly expects named param to be exactly as the provided param. Laravel 6 expects route('voyager.bread.create', ['**table**' => $table->name]) NOT route('voyager.bread.create', ['name' => $table->name])
php artisan route:list gives insight to the route in question
admin/bread/{table}/create 
{table} placeholder might demand ['table'=>   param

When  ['name'=>  is changed to  ['table'=> in these files

vendor/tcg/voyager/resources/views/tools/bread/edit-add.blade.php
vendor/tcg/voyager/resources/views/tools/bread/index.blade.php
vendor/tcg/voyager/resources/views/tools/database/index.blade.php

The url renders correctly.

**Comment by emptynick** [comment] 2019-09-06 14:47
Please search before opening new issues.
Closing as a duplicate of https://github.com/the-control-group/voyager/issues/4380, https://github.com/the-control-group/voyager/issues/4376 and https://github.com/the-control-group/voyager/issues/4383

Also, our readme states that we don't support Laravel 6.0 (yet)

**Closed as completed by emptynick** 2019-09-06 14:47 UTC
Labels: duplicate
