### ISSUE TITLE
[BUG] voyager 1.1 bread panel breadcrumbs link error

### ISSUE THREAD

**Issue by giorgosstab** [thedevdojo/voyager#3900] opened 2019-01-18 19:00 UTC
## Version information

 - Laravel: v5.6.39
 - Voyager: v1.1.10
 - PHP: 7.1.3
 - Database: [mysql] [5.7.24] (e.g. MySQL 8.0)

## Description

hey guys i have a problem in bread of voyager panel with breadcrumbs doesn't work the last link have error.i send photos to check it and fix it in the next commit

## Steps To Reproduce
1. Go to bread tab
2. Click on edit a bread
3. Go to breadcrumbs and click last link before edit

## Screenshots
![2019-01-18](https://user-images.githubusercontent.com/17095088/51407243-fa814980-1b63-11e9-9b80-4f3a36ed6481.png)
![2019-01-18 1](https://user-images.githubusercontent.com/17095088/51407256-0967fc00-1b64-11e9-9cd3-db185bb459b0.png)

**Comment by emptynick** [comment] 2019-01-18 19:20
Please search before opening new issues.
This has already been fixed in https://github.com/the-control-group/voyager/pull/3779 and is a duplicate of #3434

**Closed as completed by emptynick** 2019-01-18 19:20 UTC
Labels: duplicate

**Comment by giorgosstab** [comment] 2019-01-18 19:23
mate its so many issues and possible fixxes the github is so big. its like looking for a needle in the straw..thats why asked here..and thank you
