### ISSUE TITLE
The query always appears

### ISSUE THREAD

**Issue by huantransuper** [thedevdojo/voyager#5241] opened 2021-02-22 08:10 UTC
## Version information

 - Laravel: v.8
 - Voyager: v^1.4
 - PHP: 7.4
 - Database:  MySQL 8.0

## Description

I see in every request when using voyager has a query 

"select
   *
from
   information_schema.tables
where
   table_schema = 'your-database'
   and table_name = 'data_types'
   and table_type = 'BASE TABLE' "

can you please explain more for me???

it's called in VoyagerServiceProvider @ loadAuth. If you use it like this, all requests will call redundant queries and affect performance

**Comment by MrCrayon** [comment] 2021-02-24 12:17
Duplicate of #3396

**Closed as completed by MrCrayon** 2021-02-24 12:17 UTC
Labels: duplicate

**Comment by huantransuper** [comment] 2021-02-26 14:26
@MrCrayon 
it's completely different. I also wrote a caching model to cache all the data. But you use Schema :: hasTable (VoyagerFacade :: model ('DataType') -> getTable ()). This is the problem

**Comment by MrCrayon** [comment] 2021-02-27 04:11
@huantransuper that query is still made for the same reason, because data_types are in database and they are needed for both routes and policies.
I think the schema check was put there to avoid an error if database is switched and there is no data_types table but it's already inside a try so maybe we can remove that.
