### ISSUE TITLE
Menu builder edit item problem

### ISSUE THREAD

**Issue by jltrevizon** [thedevdojo/voyager#4432] opened 2019-09-24 14:35 UTC
- Laravel: v5.8.35
 - Voyager: v1.2.7
 - PHP: 7.2
 - Database: mysql Ver 5.7.14, for Win64 (x86_64)

## Description

After updating to the Voyager 1.2.6 version, in the menu builder, when editing an item, the values are not shown in their corresponding input, the type of route is displayed without selecting, same with target and the icon field is shown with the title instead of the icon class

## Steps To Reproduce
1. Go to 'Tools'
2. Click on Menu Builder on Admin Menu
3. Select Edit any Item

## Screenshots
![image](https://user-images.githubusercontent.com/22945459/65521377-230dd000-deb7-11e9-9c44-9d29ddc0b87a.png)

**Comment by MrCrayon** [comment] 2019-09-24 16:00
Duplicate of #4365.
Fix is already merged but I don't know when next version will be released.

**Comment by jltrevizon** [comment] 2019-09-24 16:05
thanks

**Closed as completed** 2019-09-24 16:27 UTC
Labels: duplicate
