### ISSUE TITLE
"Call to a member function relationLoaded() on null"

### ISSUE THREAD

**Issue by devahmedfarouk** [thedevdojo/voyager#3018] opened 2018-04-20 12:29 UTC
- Laravel Version: 7.6.#
- Voyager Version:1.1.#
- PHP Version: 7.1

 private function loadPermissionsRelations()
    {
        $this->loadRolesRelations();
 
        if (!$this->role->relationLoaded('permissions')) {
            $this->role->load('permissions');
            $this->load('roles.permissions');
        }
    }

**Comment by emptynick** [comment] 2018-04-20 12:40
Please search before opening a new issue.
Duplicate of https://github.com/the-control-group/voyager/issues/2451

**Closed as completed by emptynick** 2018-04-20 12:40 UTC
Labels: duplicate
