### ISSUE TITLE
Call to a member function getTranslatedAttribute() on null

### ISSUE THREAD

**Issue by Sanswan** [thedevdojo/voyager#4689] opened 2020-01-11 10:58 UTC
**Version information**

 - Laravel:v6.10.0
 - Voyager: v1.3.1
 - PHP: 7.2.26
 - Database:  MySQL 5.7.28
 - Ubuntu 18.04.1

**Description**
I Know this is a pakkage from PVTL/Voyager-Forms
On there GitHub page the don't response so maby here i while get the answer.

When i am on the admin page and click on forms its just ok, butt when i click on VIEW ENQUIRIES i get this error:

Symfony\Component\Debug\Exception\FatalThrowableError

Call to a member function getTranslatedAttribute() on null

http://***********************/admin/enquiries?filter=contains&key=id&s=2

vendor/tcg/voyager/src/Http/Controllers/VoyagerBaseController.php:55

 $displayName = $dataRow->where('field', $value)->first()
>getTranslatedAttribute('display_name');

<img width="1206" alt="Schermafbeelding 2020-01-11 om 11 58 06" src="https://user-images.githubusercontent.com/38183034/72203271-aa348300-3469-11ea-96e1-50c9b4b5b650.png">

Thanks for the help

**Comment by MrCrayon** [comment] 2020-01-11 11:39
Duplicate of #4406
Please check my comments there.

**Closed as completed by MrCrayon** 2020-01-11 11:39 UTC
Labels: duplicate

**Comment by howdu** [comment] 2020-01-12 09:13
This appears to be a long standing issue which never gets fixed correctly. 

The problem is with this line when the data_row doesn't exist in the 
$displayName = $dataRow->where('field', $value)->first()->getTranslatedAttribute('display_name');

All it needs is to be separate into an IF statement. 
https://github.com/the-control-group/voyager/pull/4690/commits/e852148117e4c92ecb737ab1e21debfb355ad772

**Comment by MrCrayon** [comment] 2020-01-12 09:34
The same error could have been caused by two reasons: 
 - fields with uppercase letters
 - new field in db not present in data_rows

The first one was solved, for the second one there was the work around to save BREAD after table changes, that should be good practice anyway. 
For sure if you send again PR it's welcome. 

For PR please don't use tabs, they should be set as 4 spaces, and create a new branch from an updated untouched 1.3 branch I posted the command your old PR.
