### ISSUE TITLE
Undefined index: en when saving post

### ISSUE THREAD

**Issue by fr8ak2** [thedevdojo/voyager#3196] opened 2018-05-16 18:55 UTC
- Laravel Version: 5.6
- Voyager Version: 1.1
- PHP Version: 7.1.17
- Database Driver & Version: mysql 5.7

### Description:
Error Exception on updating post when English language selected. Other post languages are working fine.

### Steps To Reproduce:
Enable multi language and add few languages, then go to Posts section, click edit on any post, change some value and click on update post.

**Comment by emptynick** [comment] 2018-05-16 18:58
Please search before opening a new issue.
Duplicate of https://github.com/the-control-group/voyager/issues/3181, https://github.com/the-control-group/voyager/issues/3187 and https://github.com/the-control-group/voyager/issues/3089

**Closed as completed by emptynick** 2018-05-16 18:58 UTC
Labels: duplicate

**Comment by khandaniel** [comment] 2018-06-26 14:53
Dear @emptynick, can you please explain why do you close all of the issues on account of "undefined index" and other problems with multilingual feature while none of them is solved. You only reference to one possible fix which is not helpful at all. Could you please explain this to me? Would be grateful. Thanks in advance.

**Comment by emptynick** [comment] 2018-06-26 15:46
This particular issue is a duplicate of the issues I mentioned.
Having multiple issues about the same topic is pointless.
Imagine each issue having 5 duplicates, there would be a few thousan open issues.

The oldest issue will stay open until a bugfix is merged.
In this case it is #3089, and #3089 was automatically closed by Github when #3265 was merged.
#3265 does fix the issue, but isn't released yet.

**Comment by alkhachatryan** [comment] 2019-08-15 16:13
@emptynick it's not fixed yet in 2019 men.

**Comment by emptynick** [comment] 2019-08-16 07:55
You are the only one to say it's not working in 2019.

**Comment by siltais** [comment] 2019-08-23 14:49
It`s not working

**Comment by josepcrespo** [comment] 2019-09-05 16:56
It's also not working for me. Working with the latest version available of Voyager (1.2) and Laravel 5.8

**Comment by alkhachatryan** [comment] 2019-09-05 21:21
@emptynick 
This screenshot was captured in 06.09.2019
![image](https://user-images.githubusercontent.com/22774727/64381606-9f458e00-d044-11e9-9bd9-594e55900d66.png)

**Comment by siltais** [comment] 2019-09-06 07:01
How does your model look ? 
My worked like this:

![Capture](https://user-images.githubusercontent.com/53013669/64407885-1a7f6200-d08e-11e9-92b8-663d0a3b6e7f.JPG)



I also got this error if column was in INT (or other number) format.

**Comment by josepcrespo** [comment] 2019-09-06 11:47
Ok, I've found the reason why it's failing (at least in my project). Thanks to @siltais for pointing me in the right direction.

In my case, I was trying to configure a column in the database with the JSON data type and, the input type as "Code Editor" in the BREAD for the model.

It seems like, the translations can only work with text-based data types (CHAR, VARCHAR, TINYTEXT, TEXT, MEDIUMTEXT, LONGTEXT, but not JSON) (on the database) and, with "text" or "textarea" as the type of input in the BREAD configuration for the translatable properties of the model.
