### ISSUE TITLE
Validation Rules in Settings not working

### ISSUE THREAD

**Issue by classiebit** [thedevdojo/voyager#4366] opened 2019-08-30 12:41 UTC
## Version information
 - Laravel: v5.8.33
 - Voyager: v1.2.6
 - PHP: 7.2
 - Database: MySQL 8.0

## Description
I've set validation rules while adding a new setting but it's not applying/working.

## Steps To Reproduce
1. Go to Settings
2. Add a new setting e.g
Name - Test
Key - test
Type - TextBox
Group - --Any--
Options - 
```json
{
    "validation": {
        "rule": "required"
    }
}
```

3. Then when you click on Save Settings without entering any value in the new setting column, it gets saved and does not show any validation error.

## Expected behavior
If we set validation rule in a new setting, then it must through an error on invalid value and the old value must not be updated.

## Screenshots
[https://prnt.sc/ozm897](https://prnt.sc/ozm897)

**Comment by emptynick** [comment] 2019-08-30 12:50
Please search before opening new issues.
Duplicate of https://github.com/the-control-group/voyager/issues/3494

**Closed as completed by emptynick** 2019-08-30 12:50 UTC
Labels: duplicate

**Comment by classiebit** [comment] 2019-08-30 13:48
Woops... sorry! :(
