### ISSUE TITLE
BelongsTo ServerSide Search on Browse Page of BREAD of any Model

### ISSUE THREAD

**Issue by ikramulmustafa** [thedevdojo/voyager#4493] opened 2019-10-21 10:06 UTC
- Laravel: v6.0
 - Voyager: v1.3
 - PHP: 7.2
 - Database: aurora-Mysql 5.6

## Description

Can't search BelongTo items on Browse view in Server-Side Search

## Steps To Reproduce
1. Go to BREAD
2. Create a new BelongsTo relationship.
3. Select Server-Side pagination
4. Go to the model Browse View
5. Try to search for content based on the Related table.

## Expected behavior
What is needed here, is to customize the search-key dropdown filter, so it is possible to search based on the related model data.

**Comment by emptynick** [comment] 2019-10-21 10:08
As you already wrote in your title https://github.com/the-control-group/voyager/issues/3595 already exists.
Closing as a duplicate of https://github.com/the-control-group/voyager/issues/3595

Also, it is not _that_ easy to search relationships

**Closed as completed by emptynick** 2019-10-21 10:08 UTC
Labels: duplicate

**Comment by ikramulmustafa** [comment] 2019-10-21 10:10
but if i want to search date base on customer name  in ORDERs
but in order table i store id of customer 
and i am making relation in model then why its not searching with name

**Comment by ikramulmustafa** [comment] 2019-10-21 10:10
there is not way to add filteration?

**Comment by Spartaa** [comment] 2019-10-21 10:12
like issue #4216
