### ISSUE TITLE
crash at installing,  table categories key too long

### ISSUE THREAD

**Issue by rbkkm** [thedevdojo/voyager#2596] opened 2018-02-02 23:05 UTC
crash at installing

table categories key too long

why make so long key??

solution : 
goto `/app/Providers/AppServiceProvider.php `

and fill `\Schema::defaultStringLength(191);` to function boot

<?php
namespace App\Providers;
use Illuminate\Support\ServiceProvider;
class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
         \Schema::defaultStringLength(191);        <=================

even 191 was too long,  I use now 100

why is there a crash stop for this error

when the install just would continue ,  it had saved me hours.

**Comment by rbkkm** [comment] 2018-02-02 23:07
all laravel 5. whatever migrations crash on too long key, unbelievable.

**Comment by emptynick** [comment] 2018-02-02 23:49
Please read the manual:
https://github.com/the-control-group/voyager#3-run-the-installer

Duplicate of #2583, #2540, #2536, #1840, #1552, #1333, #1158, #1007, #754, #977, #1222, #901, #865 and all other you find [here](https://github.com/the-control-group/voyager/issues?utf8=%E2%9C%93&q=is%3Aissue+key+too+long)

**Closed as completed** 2018-02-02 23:56 UTC
Labels: duplicate

**Comment by rbkkm** [comment] 2018-02-03 16:09
i think 99,9999% have outdated mysql.  nice solution.  can't change mysql version, you should change your installer for outdated mysql.

**Comment by fletch3555** [comment] 2018-02-03 16:21
It's not our installer, it's laravel.

**Comment by rbkkm** [comment] 2018-02-04 09:04
This is a really BIG issue. Trim the column is ridiculous, u should trim the index.

"Best" Solution: Use Smaller Indexes
This solution fixes the underlying issue and allows us to avoid issues caused by any customer's particular configuration of MySQL.

On VARCHAR fields (this hasn't been necessary on INT fields, and generally only FULLTEXT indexes are created on TEXT fields), we have the option to use smaller indexes; Up to the first 191 characters.

-- Index first 20 characters of the username column
ALTER TABLE users ADD INDEX username_index_name (username(20))
This lets you use the full 255 characters at the "expense" of index length, rather than getting the full index length at the expense of the varchar field length.

Depending on your use case, this solution can provide a speed boost to MySQL, as we're not storing as much information in the indexes (making it faster for MySQL to search the index). It definitely will remove warnings and errors about the index length when using the utf8mb4 character set.

This also makes an application less susceptible to issues to using within different/unknown MySQL environments.

Because this could be managed within our code, not create an issue where customers needed to do MySQL configuration changes, and wouldn't risk truncating "legacy" customer data, this was our most viable solution.

**Comment by emptynick** [comment] 2018-02-04 10:51
Again, its a Laravel problem. Voyager uses Laravels migrations, and things Laravel provides.
Show us the place where **Voyager** defines the length of indexes, then we can discuss what to do.
**Hint:** look [here](https://github.com/the-control-group/voyager/blob/1.0/publishable/database/migrations/2016_02_15_204651_create_categories_table.php#L17)

Also please mention your source if you copy text from another site.
https://serversforhackers.com/c/mysql-utf8-and-indexing
Did you notice that this text is 3 years old?
