### ISSUE TITLE
Cannot Browse BREAD - Getting Error Exception [mb_strlen expects parameter 1 to be a string, array given]

### ISSUE THREAD

**Issue by J-George** [thedevdojo/voyager#3121] opened 2018-05-02 13:13 UTC
- Laravel Version: 5.6.19
- Voyager Version: 1.1.0
- PHP Version: 7.1
- Database Driver & Version: phpmyadmin 4.0.10.18

### Description:
I cannot Browse the Users BREAD- get an Error Exception about mb_strlen expects parameter 1 to be a string, array given.
The problem started when i added 2 additional columns to the user table, both were VARCHARS. Once i saw the error i deleted the 2 columns to set it back to default - but no use.
![2](https://user-images.githubusercontent.com/6556016/39524602-d6c30fe8-4def-11e8-9502-0dc46a8eac5e.PNG)
![1](https://user-images.githubusercontent.com/6556016/39524613-dd108092-4def-11e8-9a79-9c10de7d1f7c.PNG)
All other table's BREAD work correctly. I can go to phpmyadmin and see the table.

Is it looking elsewhere in the code for those 2 columns to exist?

### Steps To Reproduce:
I merely added 2 extra columns to the users table. Once i saved the table, the changes showed up correctly in php my admin, but i cannot browse the BREAD in Voyager. I didn't change the code anywhere else on the site just yet, will be modifying the User Model once this issue gets resolved.

**Comment by emptynick** [comment] 2018-05-02 13:16
Aware of the issue.
For now: go to the BREAD-settings page ( `/admin/bread/users/edit` ) and uncheck `Browse/Read/Edit/Add/Delete` for `settings`
Despite that: this is a duplicate of #3102 and #3116

**Closed as completed by emptynick** 2018-05-02 13:16 UTC
Labels: duplicate

**Comment by J-George** [comment] 2018-05-02 13:22
Thank you @emptynick! That worked perfectly.
