### ISSUE TITLE
Uploaded images not working

### ISSUE THREAD

**Issue by leocarmo** [thedevdojo/voyager#2365] opened 2017-12-14 21:00 UTC
- Laravel Version: 5.5
- Voyager Version: latest
- PHP Version: 7.1

### Description:
When i upload a new image or file, its not showing on browser, but the image is correctly on my filesystem. Primary images from install are correctly display

### Already tried
- Change my `APP_URL` in `.env`
- Try if existis on `/storage/app/public/posts`

### Steps To Reproduce:
![voyager-img01](https://user-images.githubusercontent.com/21243754/34013866-3e404e0e-e100-11e7-964b-f4609ee6741e.PNG)

![voyager-img02](https://user-images.githubusercontent.com/21243754/34013885-50aba9d0-e100-11e7-9cbc-55ca5b22c213.PNG)

![voyager-img03](https://user-images.githubusercontent.com/21243754/34013981-b2c63504-e100-11e7-83a1-50841f0bcd40.PNG)

![voyager-img04](https://user-images.githubusercontent.com/21243754/34013998-c34b8168-e100-11e7-8b0b-730a79852189.PNG)

![voyager-img05](https://user-images.githubusercontent.com/21243754/34014036-dcfabcaa-e100-11e7-928c-4423f25400d4.PNG)

**Comment by mateushackfaccat** [comment] 2017-12-18 13:31
Hi @leocarmo, I noticed that the standard Voyager files are in .JPG, and what you're trying to upload is .PNG. Have you tried uploading a .JPG file to see if the problem still continues?

**Comment by leocarmo** [comment] 2017-12-18 13:37
Hi @mateushackfaccat , tks for your attention.

Same problem... Its not only with images, files too

![voyager-img06](https://user-images.githubusercontent.com/21243754/34108573-c04afb4e-e3e7-11e7-9295-6780736ccc5a.PNG)

![voyager-img07](https://user-images.githubusercontent.com/21243754/34108579-c3d14840-e3e7-11e7-93e5-8bbfafe6e0c1.PNG)

**Comment by mateushackfaccat** [comment] 2017-12-18 13:46
Have you checked whether the folders where Voyager is running have all the permissions?
From what I can see, it creates the file call in the database, but does not actually save the file. 

I'm glad that more Brazilians are using Voyager. :)

**Comment by leocarmo** [comment] 2017-12-18 15:41
Yes, all permissions are the same... And all exists

Yeah! Im tryng :)

![voyager-img08](https://user-images.githubusercontent.com/21243754/34114135-13ae4622-e3f9-11e7-8a6d-325c9faa6c43.PNG)

**Comment by mateushackfaccat** [comment] 2017-12-18 16:06
I do not know what might be happening then. Have you tried installing a new instance of Voyager to run a test and see if that installation is not in trouble?
Another possibility could give the `composer update` command to update Composer and other dependencies.

**Comment by leocarmo** [comment] 2017-12-18 17:15
Yes, already done... I tryed 3 times another instance. When i used laravel 5.4 everything run, but on 5.5 i have this problem

**Comment by mateushackfaccat** [comment] 2017-12-18 17:36
I do not know what might be happening then. :(

**Comment by fletch3555** [comment] 2017-12-18 18:53
Please reload the page with your browser's devtools open and record the requests for those images (one working, one "broken").  For each, please share with us what the URL is for the image, as well as the mime-type being sent by the server, and any other information you believe may be relevant ("size", etc). 
 If you'd like to repeat the process with files that do/don't work, that would be appreciated as well.

Additionally, please share a screenshot of your `public` folder indicating that the `public/storage` symlink is set up properly.

**Comment by leocarmo** [comment] 2017-12-18 21:08
Anyway thanks for the help @mateushackfaccat 

Thanks for the answer @fletch3555 

Yes, something is wrong with the type:
![voyager-img09](https://user-images.githubusercontent.com/21243754/34128089-a7957d56-e426-11e7-84c8-6a8b7af646be.PNG)

`public\storage`
![voyager-img10](https://user-images.githubusercontent.com/21243754/34128117-bd21d106-e426-11e7-8c66-721be66a995d.PNG)

**Comment by fletch3555** [comment] 2017-12-18 21:26
@leocarmo, Can you please look at the network request for POST `/media/files`? I'm interested in the response.  It should contain JSON-formatted metadata about each file in that folder.  For each file, there should be a `type` field containing the mimetype ([ref](https://github.com/the-control-group/voyager/blob/1.0/src/Http/Controllers/VoyagerMediaController.php#L225)).

**Comment by leocarmo** [comment] 2017-12-19 12:28
@fletch3555 take a look:

![voyager-img11](https://user-images.githubusercontent.com/21243754/34157110-5068fcfc-e4a7-11e7-9b50-fff51a1d3e4a.png)

**Comment by merby04** [comment] 2017-12-20 03:42
i have same issue, Any solution master ?

**Comment by ostryanyn** [comment] 2017-12-21 19:14
hi, i was facing such problem, i've managed to fix the issue by updating `APP_URL` in .env file from http://localhost to my website domain name http://example.org

**Comment by merby04** [comment] 2018-01-02 08:14
no solution sir ?

**Comment by leocarmo** [comment] 2018-01-02 10:57
nothing... @x5c

**Comment by vafagh** [comment] 2018-02-07 06:04
I had a same problem. I update my .env for new domain but due to production and cache it stay same until I ran `php artisan config:cache` to force Laravel to get&cache new value from .env file.
Read more: [hear](https://laravel.com/docs/5.5/configuration#configuration-caching)

**Comment by gstoa** [comment] 2018-02-10 14:29
php artisan storage:link

**Comment by chirill** [comment] 2018-07-03 15:22
hi, i had the same issue.
In my case i found the problem....
All files from voyager was working, but my uploads not......
i checked my public_html folder from hosting, and i found in there a FOLDER called storage, and guess what, the app was reading from this folder(/public_html/storage) and not from my /projectname/storage/app/public, i renamed the storage folder, and use this to create the link to proper folder:
`<?php
$target = '/home/{your user name on hosting website}/{your project name}/storage/app/public'; 
$shortcut = 'storage'; 
symlink($target, $shortcut); 
?>`
by default voyager try to create symlink, but on my hosting he just copied the folder :)

**Comment by fletch3555** [comment] 2018-07-03 15:30
@chirill, since you mentioned `public_html`, I'm guessing you're on shared hosting, with a non-default setup (public_html is your `public` folder).  Did you also override `path.public` in AppServiceProvider so laravel knows how to find the public directory? This is how laravel knows where to put the symlink, and therefore where voyager puts it.  Not doing so is likely the root cause for your issue

**Comment by chirill** [comment] 2018-07-03 15:51
@fletch3555, i didn't override path.public.
i edited my index.php at require __DIR__. and $app to get back and to go to my project folder

**Comment by fletch3555** [comment] 2018-07-03 15:59
Both would be needed. What you did is enough to get laravel to work, but what I suggested is needed for anything calling the `public_path()` method, which is common for packages publishing static assets (css/js/images), as well as the `artisan storage:link` command

**Comment by chirill** [comment] 2018-07-03 16:06
I set this
`public function register()
    {
        $this->app->bind('path.public', function() {
            return base_path().DIRECTORY_SEPARATOR.'public_html';
        });
    }`
in AppServiceProvider, now at dashboard voyager offer me to fix symlink, i click fix and get an error
symlink(): No such file or directory

**Comment by yilmazerhakan** [comment] 2018-09-26 10:33
In Unix systems, check your storage file owners.
It must be same user with  php and nginx/apache etc.

**Comment by stantoju** [comment] 2018-10-24 09:12
It's simple. I had exact same problem. So here's my fix...
Simply delete the storage folder shortcut in the public folder.
The re-run the symlink command "php artisan storage:link" from your terminal
That's it.
Lemme know if it worked for you

**Comment by BMCTeixeira** [comment] 2018-12-21 17:11
I currently have this problem in production 

Symlink is created
App_url is updated

Still the images are broken (avatars, etc)
However the previous images work on the frontend, I'm unable to upload new ones as it gives an error

**Comment by ledikari** [comment] 2019-02-27 10:37
encountered the same issue, 

currently my voyager app's core is not saved in httdocs, 

what i notice is that when I copy images to  httdocs/myapps/storage it correctly displays. But when I upload it goes to the  public/storage

**Comment by cardinalwebma** [comment] 2019-03-04 02:16
php artisan storage:link

**Comment by ledikari** [comment] 2019-03-14 09:37
yep, i ran php artisan storage:link couple of times, it doest not fix the issue.

**Comment by Fenweldryn** [comment] 2019-03-21 19:13
having the same issue. I changed the admin background image through the options but after the image is uploaded it does not show. Dev tools show 404. Media does not load the image as well.
I can't create a symlink because I'm on corporate network and I do not have admin privileges to create it.

Everything else is working properly. Important to say that I had to move the project to a subfolder. Locally the image is loaded after an upload. Using the server the image does not show.

**Comment by Fenweldryn** [comment] 2019-03-21 19:41
I have uploaded an image to use in a dimmer and it works just fine. It did not work while using admin image background upload.

**Comment by Fenweldryn** [comment] 2019-03-21 19:52
I found my issue.
My .env APP_URL was set as localhost =P
Now it works just fine!

**Comment by cessto103** [comment] 2019-07-04 18:56
I had same exact issues. changing my APP_URL .env did solve my problem although that is the most suggested solution here, I wasn't able to fix it until I found this video, https://www.youtube.com/watch?v=8FjqHsmAeCM . I hope this will also fix yours.

**Comment by fletch3555** [comment] 2019-07-04 19:54
I'm going to close this since it's so old and multiple causes/solutions have been identified, all related to misconfiguration.

**Closed as completed** 2019-07-04 19:54 UTC

**Comment by HariKumarValluru** [comment] 2019-08-27 04:50
I have solved this issue by adding the below code in filesystems.php and mentioned in .env as

`FILESYSTEM_DRIVER=production`

```
'production' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/public/storage',
            'visibility' => 'public',
        ],
```

**Comment by mf0wzi** [comment] 2019-09-27 12:04
I solved the issue by adding this to AppServiceProvider.php in register function

$this->app->bind('path.public', function() {
//use this if you are using a subdomain
  return dirname(getcwd().DIRECTORY_SEPARATOR.preg_replace('#^https?://#', '',env('APP_URL')));
// use this if you are using public_html
// return dirname(getcwd().DIRECTORY_SEPARATOR.'public_html');
});
and then php artisan storage:link

This works for Shared hosting only
