### ISSUE TITLE
[BUG] Richtextbox multilingual

### ISSUE THREAD

**Issue by Hi7cl4w** [thedevdojo/voyager#4096] opened 2019-04-22 13:35 UTC
## Version information

 - Laravel: v5.8
 - Voyager: v1.3
 - PHP: 7.2
 - Database: 5.6

## Description
from any translatable bread model edit page, language switch not working with rich text box (TinyMCE) , other text fields are fine.
When I update or create it shows error page (Only when bread contains rich text box) `Undefined index: en`

## Steps To Reproduce
1. Enable Multilingual from voyager config
2. Add multiple languages 
```json
'locales' => [
            'en',
            'ar',
        ],
```
3. Create Bread for any table and add rich text for a text column.
4. Enable Translatable from the model of the corresponding table

## Expected behavior
When I update or create it shows error page (Only when bread contains rich text box) `Undefined index: en`

**Comment by reageek** [comment] 2019-04-22 18:20
https://github.com/the-control-group/voyager/pull/4077

**Comment by emptynick** [comment] 2019-04-24 12:05
Closing as a duplicate of https://github.com/the-control-group/voyager/issues/4072
Edit: maybe not #4072 but all you can find [here](https://github.com/the-control-group/voyager/issues?utf8=%E2%9C%93&q=is%3Aissue+Undefined+index%3A+en).
Also, Voyager 1.3 does not exist.

**Closed as completed by emptynick** 2019-04-24 12:05 UTC
Labels: possible bug
