### ISSUE TITLE
Many to Many relation Builder::getTranslationsOf() ErrorException

### ISSUE THREAD

**Issue by gsokolowski** [thedevdojo/voyager#2777] opened 2018-03-06 16:16 UTC
- Laravel Version: 5.4.36
- Voyager Version: 1.0.15
- PHP Version:5.6.30
- Database Driver & Version:

### Description:

Many to Many relation
I got an issue when added many to many relationship

(2/2) ErrorExceptionCall to undefined method Illuminate\Database\Query\Builder::getTranslationsOf() (View: /Users/Grzegorz/Sites/laravel-codecreators/vendor/tcg/voyager/resources/views/posts/edit-add.blade.php)

### Steps To Reproduce:
make post table and model
make category table and model
create pivot tables
set relationship

And on my web I can see that post has many categories and category has many post
but when I try to edit post through voyager I get this error

(2/2) ErrorExceptionCall to undefined method Illuminate\Database\Query\Builder::getTranslationsOf() (View: /Users/Grzegorz/Sites/laravel-codecreators/vendor/tcg/voyager/resources/views/posts/edit-add.blade.php)

Any help would be appreciated 
Greg

**Comment by emptynick** [comment] 2018-03-08 08:34
Thats probably because `posts` has custom views.
There is a PR where you can exclude built-in custom views, but thats not merged yet.
You can try to change the BREAD-slug to something different than `posts` or `pages`.

**Comment by rokasma** [comment] 2018-06-16 07:56
@emptynick Thank you!

**Comment by bnymn** [comment] 2018-08-04 20:58
Hi @emptynick 
This issue has not been solved yet, I think. I still have this problem. Which PR is it?

**Comment by emptynick** [comment] 2018-08-04 21:25
Its https://github.com/the-control-group/voyager/pull/2117 but it wont solve the "problem".
The problem is the hardcoded view, which you can simply override (as mentioned in our docs).
You can just put something like this inside:
`@include('voyager::bread.edit.add')`

Closing this, as its not a bug.

**Closed as completed by emptynick** 2018-08-04 21:25 UTC

**Comment by SoldierCorp** [comment] 2018-08-19 13:36
I created a custom view to solve this but I thought the sidebar, the navbar and the other elements will be in that custom view but that is not happening, is there a way to use a custom view with including all these other sections?

**Comment by fletch3555** [comment] 2018-08-20 14:53
@SoldierCorp, that is a different problem, most likely related to how you built your custom view.  Please ask in slack or open your own issue with all relevant details, and we'll review there.
