### ISSUE TITLE
500 (Internal Server Error) whenever the Add/Edit User form is not completely filled

### ISSUE THREAD

**Issue by nuhu-ibrahim** [thedevdojo/voyager#4979] opened 2020-06-12 23:02 UTC
## Version information

 - Laravel: v7.14.1
 - Voyager: v1.2.3
 - PHP: v3.4.0
 - Database: [MySQL] [8.0.19]

## Description

Whenever an attempt to create or edit a user is made without filling the entire form, the application throws a 500 (Internal Server Error) because of null values. Apparently, that is because no server-side validation is performed for user input and client-side (HTML) validation is also not enforced.

## Steps To Reproduce
Steps to reproduce the behaviour:
1. Install Voyager and Login
2. Click on Users
3. Click on Add New
4. Partially fill the form and Click Save
5. You will see a 500 (Internal Server Error)

## Expected behaviour
Performs both client-side and server-side validation

## Screenshots
![image](https://user-images.githubusercontent.com/45234328/84552474-c4b8a400-ad08-11ea-9273-644457836700.png)

**Comment by MrCrayon** [comment] 2020-06-13 03:16
Duplicate of #3153

**Closed as completed by MrCrayon** 2020-06-13 03:16 UTC
Labels: duplicate
