### ISSUE TITLE
belongsTo Relationship bug Voyager 1.2.7 after changing from $options->column to $relationshipField

### ISSUE THREAD

**Issue by mf0wzi** [thedevdojo/voyager#4437] opened 2019-09-26 04:39 UTC
## Version information

 
    Laravel: v5.8.#
    Voyager: v1.2.7
    PHP: 7.1
 - Database: MySQL v5.7.26

## Description:
After changing the fields relationship in Path: resources/views/formfields/relationship.blade.php

From:
<select class="form-control select2-ajax" name="{{ $options->column }}" data-get-items-route="{{route('voyager.' . $dataType->slug.'.relation')}}" data-get-items-field="{{$row->field}}" >

To

<select class="form-control select2-ajax" name="{{ $relationshipField }}" data-get-items-route="{{route('voyager.' . $dataType->slug.'.relation')}}" data-get-items-field="{{$row->field}}" >

The data is not sent to the database and the belong to relationship is not created 
but if I change the .select2-ajax from {{ $relationshipField }} to {{ $options->column }} it functions properly and the relationship is created

## Additional context
Relation screenshot attached 
![belongtoRelationship](https://user-images.githubusercontent.com/30725615/65658502-b3bbeb80-e030-11e9-9475-625b0d291769.jpg)

**Comment by MrCrayon** [comment] 2019-09-26 13:39
I don't think this is a bug like I don't think #4031 was a bug, but with #4228 was actually solved another problem and now it's possible to use validation for belongsTo relationship.

Voyager can use both values in name to save, the only thing is you need to enable edit in the correct field in your BREAD configuration.

In short enable Edit for project_parent_id and it should work.

**Comment by mf0wzi** [comment] 2019-09-27 10:37
The thing is that project_parent_id edit is enabled in BREAD as shown in the attachment
![Screenshot_2019-09-27 Edit BREAD for projectpages table](https://user-images.githubusercontent.com/30725615/65763392-f1ea0580-e12b-11e9-90f1-4d0ba4fef78e.png)


also when {{ $relationshipField }} set the field name would be "projects projectpage_belongsto_project_relationship"  and then the id would not be saved in the project_parent_id field

but if {{ $options->column }} isset the field name is  "project_parent_id"   and the id is saved.

**Comment by MrCrayon** [comment] 2019-09-27 11:35
I got it backward I thought last PR was changing it from the long form projects projectpage_belongsto_project_relationship to project_parent_id, but was the other way around so I retract my claim of any benefit on that PR.

I still stand that both ways should work, if you check 
https://github.com/the-control-group/voyager/blob/015c517a1e52ee93a6f83a24a601f50cb0b92cf1/src/Http/Controllers/Controller.php#L69
you'll see how value is saved in the right field even if sent with _wrong_ name.

Now I see what's this bug is about and also #4031 and has nothing to do with the name chosen.

The problem is that values saved are assigned with a foreach of data rows:
https://github.com/the-control-group/voyager/blob/015c517a1e52ee93a6f83a24a601f50cb0b92cf1/src/Http/Controllers/Controller.php#L55

When there is a belongsTo there are two rows that can potentially assign the value and one of them is going to be set as NULL, so your problem right now is that project
_parent_id comes after the relationship so it set value back to NULL.

**You can fix this in two ways:**
Move the relationship field after project_parent_id
Even better remove the edit and add check for  project_parent_id

I think this problem should be addressed but I don't know how BREAD is going to change in the future releases.

**Comment by mf0wzi** [comment] 2019-09-27 12:27
YES :) 

I can confirm by moving the relationship below project_parent_id or vice-versa the value is saved in its field.

Thank you for your follow up 
![Screenshot_2019-09-27 Edit BREAD for projectpages table(1)](https://user-images.githubusercontent.com/30725615/65769030-40eb6700-e13b-11e9-94bb-7089a35cd87a.png)
and Thumb up

**Comment by MrCrayon** [comment] 2019-09-27 12:34
You are welcome.
I think it's better if you set again the edit and add for project_parent_id, it will still work and if my PR is merged you won't have to change anything after and there will be no problem about ordering either.

**Comment by mf0wzi** [comment] 2019-09-27 12:38
Great will do, Thanks again :)

**Closed as completed** 2019-09-27 12:41 UTC
