### ISSUE TITLE
Uploaded file always removed after updating (BREAD)

### ISSUE THREAD

**Issue by jericizon** [thedevdojo/voyager#3201] opened 2018-05-17 04:14 UTC
- Laravel Version: 5.5
- Voyager Version: 1.1
- PHP Version: 7.1.15
- Database Driver & Version: MySQL

### Description:

When saving the data, the file was always removed if there is no attached to the file upload field.

## Before updating

![save-1](https://user-images.githubusercontent.com/8746166/40155955-1a97f46a-59c9-11e8-9b54-b9a298f1a579.JPG)
![save-2](https://user-images.githubusercontent.com/8746166/40155957-1acacc8c-59c9-11e8-94bb-d5ec9f9dd82f.JPG)

## After updating

![after-update-1](https://user-images.githubusercontent.com/8746166/40155958-1af60e1a-59c9-11e8-818c-9fb54aed586a.JPG)
![after-update-2](https://user-images.githubusercontent.com/8746166/40155959-1b258a5a-59c9-11e8-8704-c752f2aa0aac.JPG)

### Steps To Reproduce:
- Create new table with BREAD
- Insert record with file attached
- Update newly inserted record
- Click save without updating the uploaded file
- The uploaded file removed

**Comment by emptynick** [comment] 2018-05-17 07:42
Please search before opening a new issue.
Duplicate of https://github.com/the-control-group/voyager/issues/3097

**Closed as completed by emptynick** 2018-05-17 07:42 UTC
Labels: duplicate
