### ISSUE TITLE
mb_strlen() expects parameter 1 to be string, array given (View: /Users/jeremy/Desktop/projects/medreps/vendor/tcg/voyager/resources/views/bread/browse.blade.php)

### ISSUE THREAD

**Issue by Xerakon** [thedevdojo/voyager#3116] opened 2018-05-01 18:40 UTC
- Laravel Version: 5.6
- Voyager Version: 1.1
- PHP Version: 7.2.4
- Database Driver & Version: 

### Description:

Added more fields via Voyager/BREAD interface to users table. Received following error when attempting to browse users. Multilingual is set to false.

"mb_strlen() expects parameter 1 to be string, array given (View: /Users/jeremy/Desktop/projects/medreps/vendor/tcg/voyager/resources/views/bread/browse.blade.php) {"userId":3,"email":"jeremy@medrepsrx.com","exception":"[object] (ErrorException(code: 0): mb_strlen() expects parameter 1 to be string, array given (View: /Users/jeremy/Desktop/projects/medreps/vendor/tcg/voyager/resources/views/bread/browse.blade.php) at /Users/jeremy/Desktop/projects/medreps/storage/framework/views/b231f808ccd3d62a40794668c75f05fa3be0db37.php:154, ErrorException(code: 0): mb_strlen() expects parameter 1 to be string, array given at /Users/jeremy/Desktop/projects/medreps/storage/framework/views/b231f808ccd3d62a40794668c75f05fa3be0db37.php:154)"

**Comment by emptynick** [comment] 2018-05-01 22:02
Please search before opening a new issue.
Duplicate of https://github.com/the-control-group/voyager/issues/3102

**Closed as completed by emptynick** 2018-05-01 22:02 UTC
Labels: duplicate
