### ISSUE TITLE
Exception when null given to foreach

### ISSUE THREAD

**Issue by maxmadknight** [thedevdojo/voyager#3133] opened 2018-05-04 10:48 UTC
https://github.com/the-control-group/voyager/blob/97291990327abc28ffca1f1703125c22413bf6da/src/Http/Controllers/ContentTypes/MultipleImage.php#L19

When i try to edit item with multiple images get error 
"
ErrorException (E_WARNING)
Invalid argument supplied for foreach()
"

I thinks there should be check is null given

**Comment by fletch3555** [comment] 2018-05-04 19:55
Please search before opening issues.  Duplicate of #3065.  Fix in #3070, pending merge

**Closed as completed by fletch3555** 2018-05-04 19:55 UTC
Labels: duplicate
