### ISSUE TITLE
While creating table adding precision in datatype like FLOAT, DOUBLE and DECIMAL is not working

### ISSUE THREAD

**Issue by Haritsinh** [thedevdojo/voyager#4498] opened 2019-10-22 13:21 UTC
## Version information

 - Laravel: v6.0
 - Voyager: v1.3.*
 - PHP: 7.2
 - Database:  MySQL 5.6

## Description

While creating table field adding precision in datatype like FLOAT, DOUBLE and DECIMAL is not working, field with FLOAT and DOUBLE datatype are also ignoring length with precision.

## Steps To Reproduce
1. Go to `Database` menu 
2. Click on `create table`
3. Add new column
4. Enter any name (for e.g. price) in `name` field
5. in Type field select any datatype from (`FLOAT, DOUBLE or DECIMAL`) take DECIMAL for example
6. in `Length` field type `5,2` or any precision point you wanted
7. click on **save**
8. Table will be successfully created but if you will see it in table structure then you can see there that **price field's length will be DECIMAL(5,0)**, if you choose FLOAT or DOUBLE then it will remove the user entered length completely, it is **ignoring precision point in `DECIMAL` datatype and ignoring length and precision both in FLOAT and DOUBLE.**

## Expected behavior
Table creation should support **precision point** added by user in table field like 
Type - DOUBLE,FLOAT OR DECIMAL  and Length -10,2 should create the same column in table but it is now creating Length of (10,0) it is not considering values for precision point.

## Screenshots
See Below price with float datatype and length 10,2 and other fields Inserted in create new table:
![laravel-voyager-datatype-float-decimal-double](https://user-images.githubusercontent.com/38683068/67288372-79901d80-f4fa-11e9-9ac7-9fe1d0d1d995.PNG)

After inserting screenshot of newly created table `products` table in database:
![table-not-taking-float-precision-point](https://user-images.githubusercontent.com/38683068/67286024-4481cc00-f4f6-11e9-86b8-6c716cd7886e.PNG)

Inserting Field for decimal datatype
![decimal-datatype-problem](https://user-images.githubusercontent.com/38683068/67289433-3c2c8f80-f4fc-11e9-9e9f-1db1cad94e91.PNG)

After inserting database table not taking precision point as per defined:
![decimal-datatype-table-problem](https://user-images.githubusercontent.com/38683068/67289436-3c2c8f80-f4fc-11e9-9717-7b6f86434898.PNG)

## Additional context
while creating table after selecting any datatype, in field length if you type value with precision like 5,2 then if you click outside of that length input then you can see that it removes values after comma and comma itself, so after losing focus it will be only 5, so it saves as 5,0 in table, but i think `voyager` has not feature like this for saving precision point so it has put validation to remove other values.

**Comment by emptynick** [comment] 2019-10-23 13:14
Please search before opening new issues.
Closing as a duplicate of https://github.com/the-control-group/voyager/issues/3793

**Closed as completed by emptynick** 2019-10-23 13:14 UTC
Labels: duplicate

**Comment by Haritsinh** [comment] 2019-10-23 13:31
@emptynick  i had seen that but it was only about `decimal` and mine is for `float`,`double` and `decimal`.

**Comment by emptynick** [comment] 2019-10-23 13:51
It's still 99% the same issue.
It's much better to just post that in the other issue.

**Comment by Haritsinh** [comment] 2019-10-23 17:26
> It's still 99% the same issue.
> It's much better to just post that in the other issue.

Ok, then it is ok to close this, i have thought it is different because of different datatypes, anyways thanks for creating tool like `Voyager`.
