### ISSUE TITLE
Invalid Datetime Format when trying to update user profile.

### ISSUE THREAD

**Issue by sarath-c-sandwich** [thedevdojo/voyager#539] opened 2017-01-12 09:09 UTC
- Laravel Version: 5.3.*
- Voyager Version: 0.10.8
- PHP Version: 7.0.4
- Database Driver & Version: MySQL v 5.7.11

### Description:
Trying to update User Profile then can not save to DB with Invalid Date Time Format.

![screenshot 289](https://cloud.githubusercontent.com/assets/1330852/21883381/6ce30364-d8e1-11e6-95f9-aaca14ccfe35.png)

**Comment by eimanavicius** [comment] 2017-01-12 14:42
Remove created_at field from edit visibility on Users bread http://localhost:8000/admin/database/bread/3/edit

**Comment by eimanavicius** [comment] 2017-01-12 14:44
Duplicate of #521

**Comment by handiwijoyo** [comment] 2017-01-12 16:38
Closed due duplicate.

**Closed as completed by handiwijoyo** 2017-01-12 16:38 UTC
