### ISSUE TITLE
Database Buttons

### ISSUE THREAD

**Issue by iboldurev** [thedevdojo/voyager#931] opened 2017-03-14 06:48 UTC
- Laravel Version: 5.4
- Voyager Version: 0.11.6
- PHP Version: 7
- Database Driver & Version:

### Description:

No shortcut keys on database
- + Add Timestamp Fields
- + Add Soft Delete Field

@marktopper

**Comment by abdgad** [comment] 2017-03-14 08:01
Duplicate of #921

**Closed as completed by abdgad** 2017-03-14 08:01 UTC
Labels: type:enhancement

**Comment by abdgad** [comment] 2017-03-14 08:04
Right now, you can manually add `created_at`, `updated_at`, `deleted_at` columns and set their type to `TIMESTAMP`.
