### ISSUE TITLE
Certain lang files are not overwritten

### ISSUE THREAD

**Issue by MikadoInfo** [thedevdojo/voyager#5051] opened 2020-08-26 07:59 UTC
Version information
 - Laravel: v 7.24
 - Voyager: v 1.4
 - PHP: 7.4.8
 - Database: MySQL 5.7.24

Description
I have overridden the package lang file as explained in the Laravel docs
[https://laravel.com/docs/7.x/localization#overriding-package-language-files](url)
and I was able to override all the file except the seeders.php 

Steps To Reproduce
Fresh install and override the lang files

Expected behavior
Translate the settings page and the page titles in italian 

Screenshots
English ain't my first language so I'm uploading some screenshots to describe my problem:

My seeders.php compared to Voyager's:
![custom-vs-voyager](https://user-images.githubusercontent.com/69799889/91275586-aa775980-e780-11ea-8ce0-b5b0efb03131.PNG)
What I mean by page title (oddly the one in the settings page is translated):
![Page-title](https://user-images.githubusercontent.com/69799889/91275636-b3682b00-e780-11ea-90b7-e525ec87b128.PNG)
Setting page site tab
![settings-page](https://user-images.githubusercontent.com/69799889/91275661-ba8f3900-e780-11ea-8634-d8f0d9fec8c8.PNG)
Setting page admin tab
![settings-page2](https://user-images.githubusercontent.com/69799889/91275675-bfec8380-e780-11ea-8085-21410b070a53.PNG)
My settings in config/voyager.php
![Voyager-lang-settings](https://user-images.githubusercontent.com/69799889/91275684-c3800a80-e780-11ea-9609-b39198612de3.PNG)
Override path:
![override-path](https://user-images.githubusercontent.com/69799889/91277605-56ba3f80-e783-11ea-9173-be80a95160e9.PNG)

Additional context
To solve the problem I tried to:
stop and restart the virtual server
Clear cache `php artisan cache:clear` and/or `php artisan config:cache`
Reload apache
Remove my translations clear the cache again, reload apache and put my translations back

**Comment by emptynick** [comment] 2020-08-26 08:22
Those translations are only used when installing Voyager.
It is `seeded` into the database and won't be used after that.

**Comment by MikadoInfo** [comment] 2020-08-26 10:19
Why the settings are translated via that file? How I can translate it now?

**Comment by emptynick** [comment] 2020-08-26 12:10
Because that's the way things get translated in Laravel.
Either remove all settings, set your app locale to `it` and run the settings-seeder or rename them manually in your database.

Closing as this is not a bug.

**Closed as completed by emptynick** 2020-08-26 12:10 UTC

**Comment by MikadoInfo** [comment] 2020-08-26 14:39
Renaming manually fixed it
