### ISSUE TITLE
voyager-themes is not working 

### ISSUE THREAD

**Issue by afrasiyabhaider** [thedevdojo/voyager#5204] opened 2021-01-25 11:32 UTC
**voyager-themes** is not working in latest Laravel version. It displays following error in composer
`require.voyager-themes is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$".`

I've tried **thedevdojo/voyager-themes** as well but its same.
Please tell me how to resolve this issue @the-control-group

**Comment by emptynick** [comment] 2021-01-25 11:42
The issue template is not optional when opening issues.
Also, duplicate of https://github.com/the-control-group/voyager/issues/5138

**Closed as completed by emptynick** 2021-01-25 11:42 UTC
Labels: duplicate
