### ISSUE TITLE
BREAD- Files get deleted in Edit page on submit

### ISSUE THREAD

**Issue by Diaa-Boraq** [thedevdojo/voyager#4312] opened 2019-08-02 16:03 UTC
## Version information

 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.3
 - Database: MariaDB  10.1.38-MariaDB-0ubuntu0.18.04.1

## Description

files get deleted in Edit pageon submit

## Steps To Reproduce
1. Create any new Entity with files
2. Open Edit - u can see the file is uploaded and can be downloaded
3. Just click submit
4. click EDIT/BROWSE again and the file is empty

![image](https://user-images.githubusercontent.com/50443911/62383341-32783900-b558-11e9-9ddd-cd643193aa02.png)

**Comment by emptynick** [comment] 2019-08-02 16:04
Please search before opening new issues.
Duplicate of https://github.com/the-control-group/voyager/issues/4305

**Closed as completed by emptynick** 2019-08-02 16:04 UTC
Labels: duplicate
