### ISSUE TITLE
Uploading a new image removes all other previous image uploads (i.e., in the settings view)

### ISSUE THREAD

**Issue by mihaiconstantin** [thedevdojo/voyager#3118] opened 2018-05-01 20:11 UTC
- Laravel Version: 5.6.19
- Voyager Version: 1.1.0
- PHP Version: 7.2.3
- Database Driver & Version: 10.2.13-MariaDB

### Description:
- uploading an image (i.e., via settings view) discards all other images uploaded under other settings

### Steps To Reproduce:
- assume a fresh install
- suppose you have 2 settings of image type: `site.logo` and `site.footer_logo` (i.e., as in the picture below)
![Example Settings](https://i.imgur.com/1UAroz9.png)
- adding an image to the `site.logo` setting will remove the image already uploaded under `site.footer_logo`

Any clues how to get past this? It seemed to work just fine under `v1.0`.

**Comment by emptynick** [comment] 2018-05-01 20:21
Please search before opening a new issue.
Duplicate of https://github.com/the-control-group/voyager/issues/3059 and #3105

**Closed as completed by emptynick** 2018-05-01 20:21 UTC
Labels: duplicate
