### ISSUE TITLE
Remove "None" default value on relationship select box

### ISSUE THREAD

**Issue by dmitrymaslov99** [thedevdojo/voyager#5210] opened 2021-02-02 07:53 UTC
## Version information

Laravel: v8.21.0
Voyager: v1.4
PHP: 7.4.11
Database: MySQL 5.7.26

## Description
It is possible to remove the default value "None" on a select box when the relationship is required?

## Steps To Reproduce
Add a relationship (BelongTo for instance) with the BREAD screen. In data creation screen, "None" is showing up in the dropdown list.

## Expected behavior
Get "None" option not displayed.

## Screenshots
![image](https://user-images.githubusercontent.com/36110676/106568777-c7406600-6544-11eb-824d-7e7801fc2bf2.png)

## Additional context
The problem has not been fixed for six months.
Is there a temporary solution?

**Comment by dmitrymaslov99** [comment] 2021-02-02 08:06
Or can you at least swear if the person has not chosen anything?

**Comment by MrCrayon** [comment] 2021-02-02 08:13
Duplicate of #5190 

As explained in the other issue fix is available in `1.4.x-dev` now that my PR has been merged.

1.4.3 will hopefully be released soon with the fix but I'm not sure about the timing.

**Closed as completed by MrCrayon** 2021-02-02 08:13 UTC
Labels: duplicate

**Comment by dmitrymaslov99** [comment] 2021-02-02 08:23
Thank you!
