### ISSUE TITLE
error 1071 on fresh install

### ISSUE THREAD

**Issue by hmzlam** [thedevdojo/voyager#3763] opened 2018-11-24 10:46 UTC
## Version information

 - Laravel: v5.7.*
 - Voyager: Master
 - PHP: 7.2
 - Database: Mysql 5.6

## Description

fresh install on a fresh project will end with the famous error 1071 even after adding the Schema::defaultStringLength(191);

>    Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 the key is too long.
>  max length: 1000 (SQL: alter table `translations` add unique `translations_table_name_column_name_foreign_key_locale_unique`(`table_name`, `column_name`, `foreign_key`, `locale`))
> 

## Steps To Reproduce

Follow docs installation steps with a database ut8mb4_unicode_ci

## Additional context
removing this line from create_translation_table.php solve the problem

`            $table->unique(['table_name', 'column_name', 'foreign_key', 'locale']);`

**Comment by emptynick** [comment] 2018-11-24 10:48
Please [search ](https://github.com/the-control-group/voyager/issues?utf8=%E2%9C%93&q=is%3Aissue+1071)before opening new issues.
Duplicate of the above results.

**Closed as completed by emptynick** 2018-11-24 10:48 UTC
Labels: duplicate

**Comment by hmzlam** [comment] 2018-11-24 11:02
Thanks, would you please explain in docs that we should should change this line in database.php
`'engine' => 'InnoDB ROW_FORMAT=DYNAMIC',`
