### ISSUE TITLE
Bug on validate file upload

### ISSUE THREAD

**Issue by zeroiszero** [thedevdojo/voyager#3431] opened 2018-07-31 14:40 UTC
## Version information
 - Laravel: v5.6
 - Voyager: v1.1.3
 - PHP: 7.1
 - Database: MySQL 10.0

## Description
I was trhying to validate the file upload with the following rules that is similar to image file, but its not working.
`{
    "validation": {
        "rule": "mimes:pdf",
        "messages": {
            "mimes": "This :attribute field must be a pdf"
        }
    }
}`

then i found that ajax response was 
`{"errors":{"file":["This File field must be a pdf"]}}`

where the field name was `file[]` (with the support of multiple file uploads) which is different from `file` in ajax response.

it works when i manually edited the html in inspect tools.

**Comment by emptynick** [comment] 2018-12-27 22:49
Closing as a duplicate of https://github.com/the-control-group/voyager/issues/1930

**Closed as completed by emptynick** 2018-12-27 22:49 UTC
Labels: duplicate
