### ISSUE TITLE
user registration form

### ISSUE THREAD

**Issue by PaulinPrize** [thedevdojo/voyager#3516] opened 2018-09-03 16:37 UTC
## Version information

 - Laravel: v5.6
 - Voyager: v1.1
 - PHP: 7.2.3
 - Database: mysql

## Description

the setting up of traveling worked fine but the registration form of users generates an error when I try to validate it without pre-filling the fields.

## Screenshots
![capture](https://user-images.githubusercontent.com/41732884/44996411-1c5ca400-afa8-11e8-9095-156f8b60d195.PNG)

**Comment by fletch3555** [comment] 2018-09-04 19:01
Please provide the full stacktrace.  Right now, I don't see how this ties into Voyager at all, since Voyager doesn't have a "registration" form

**Comment by erisanolasheni** [comment] 2018-10-01 21:35
Having the same issue, I guess the problem is from the Voyager registration for validation... Can someone provide the location to the Voyager's user registration validation, you may need to do some edit to it.

**Comment by emptynick** [comment] 2018-10-01 22:35
There is none, as said before.

**Comment by emptynick** [comment] 2018-10-28 15:14
Closing as this is not related to Voyager at all.

**Closed as completed by emptynick** 2018-10-28 15:14 UTC
