### ISSUE TITLE
belongsToMany  - show Extra Pivot Column in the Form view

### ISSUE THREAD

**Issue by foxgenki** [thedevdojo/voyager#3745] opened 2018-11-11 13:36 UTC
## Version information

 - Laravel: v5.7.13
 - Voyager: v1.1.10
 - PHP: 7.2.10
 - Database: MySQL 5.7

## Description

First, in my app, I have those 3 models : 

Workout

   * id
   * name
   * image

Exercise

   * id
   * name
   * description

exercise_workout   
> Pivot Table

   * exercise_id
   * workout_id
   *  **_number_sets_**

When a user want to add new workout, he will enter the name, image and multiple exercises for this workout. For that I used "BelongsToMany" Relationship and it's worked perfectly.

![voyager_form](http://themeswow.com/upload/voyager_1.png)

## Expected behavior
The issue that the "Add Form" generated by Voyager not showing  a field for **_number_sets_**, it's showing only a field for exercises only. How can I resolve this issue?

**Comment by emptynick** [comment] 2018-11-11 15:46
Please [search ](https://github.com/the-control-group/voyager/issues?utf8=%E2%9C%93&q=is%3Aissue+in%3Atitle+pivot+)before opening new issues.
Closing as a duplicate of  https://github.com/the-control-group/voyager/issues/3327 , https://github.com/the-control-group/voyager/issues/2556 and many more.

**Closed as completed by emptynick** 2018-11-11 15:46 UTC
Labels: duplicate
