### ISSUE TITLE
Image delete modal is below dropdown

### ISSUE THREAD

**Issue by lucabartoli** [thedevdojo/voyager#1901] opened 2017-09-28 17:35 UTC
- Voyager Version: 1.0.4

### Description:
![image](https://user-images.githubusercontent.com/3965942/30980854-bc580f62-a482-11e7-9844-8afb632fc899.png)

### Solution:
Line 5150 of app.scss
Change `.modal-open .select2-container`
With (maybe... what was the intent?) `.modal-open .modal .select2-container`

**Comment by fletch3555** [comment] 2017-10-02 23:08
We're open to pull requests for this if you'd like to submit one.

**Comment by lex111** [comment] 2017-10-04 11:35
How can I reproduce this with a demo data (`with dummy`)?

**Comment by vaggelis2018** [comment] 2017-10-20 09:54
.modal-open .select2-container {
    z-index: 999999 !important; // this is the reason for that
    width: 100% !important;
}

**Comment by fletch3555** [comment] 2017-10-24 00:17
@vaggelis2018, do you want to open a PR with a fix? or are you just identifying the cause?

**Comment by detlab** [comment] 2017-11-06 07:00
i have same problem in Voyager v1.0.6
![image](https://user-images.githubusercontent.com/33146715/32428856-8ccbfa06-c2fa-11e7-9936-b4dd4f78ec47.png)
I've tried to change my file like this https://github.com/the-control-group/voyager/pull/2087/commits/d5d7b385afb597a82d4b03ff926c5e148442980b but nothing change
hopefully fixed soon

**Comment by marktopper** [comment] 2018-02-08 09:12
Is this still an issue in `v1.0.14`?

**Comment by Bhayres** [comment] 2018-02-13 18:08
yes i have the same issue, i fix it changing z.index of the modal... BUTTTT when you try to create a relationship en bread ( use select2 ) and the fields end up under the modal.  i still not find how fixit.

**Comment by fletch3555** [comment] 2018-02-20 18:05
Same issue as #2699, closed in #2700

**Closed as completed by fletch3555** 2018-02-20 18:05 UTC
Labels: help wanted, possible bug
