### ISSUE TITLE
CAN'T ADD BREAD

### ISSUE THREAD

**Issue by DonGasby** [thedevdojo/voyager#3657] opened 2018-10-20 13:07 UTC
Each time i try to add BREAD the attached error message comes up on screen.

How do i resolve that?

Thanks
![error](https://user-images.githubusercontent.com/34869826/47256042-67a41680-d471-11e8-87d1-6017849e7d84.png)

**Comment by emptynick** [comment] 2018-10-20 13:08
Please search before opening new issues and use the issue-template.
Duplicate of https://github.com/the-control-group/voyager/issues/3646
This has been fixed in 1.1.9, just update.

**Closed as completed by emptynick** 2018-10-20 13:08 UTC
Labels: duplicate
