### ISSUE TITLE
Allow NULL in select dropdown for relation

### ISSUE THREAD

**Issue by ateresi** [thedevdojo/voyager#2124] opened 2017-10-30 17:53 UTC
- Laravel Version: 5.5.19
- Voyager Version: 1.0.6
- PHP Version: 7.0
- Database Driver & Version: Mysql 5.6

### Description:
It is required to select a value for foreign key even if it is nullable, first value from parent table always selected in relation select dropdown.
It is not possible to remove all value for a many to many relation even if it is nullable. Almost one value must exists saving the master table.
Regards

**Comment by iSWORD** [comment] 2017-12-27 11:14
any update on this? or at least a workaround?

**Comment by iSWORD** [comment] 2018-01-01 03:51
I wrote a quick 'n dirty JavaScript workaround until this gets fixed:

```javascript
var nullable_relations = [
    'categories.parent_category_id',
    'users.neighbourhood_id'
];

nullable_relations.forEach(function (relation_key) {
    [table, field] = relation_key.split('.');

    var select_item = jQuery('body.voyager.'+table+' [name='+field+']');
    // Add the "None" option
    select_item.prepend(
        jQuery("<option></option>")
            .attr('value','')
            .text('None')
    );

    // Select it when editing an item that has a null relation
    if (jQuery('body.voyager.'+table+' [name='+field+'] option:selected').attr('selected') === undefined) {
        select_item.val('').change();
    }
});
```
1. Change the **nullable_relations** array according to your needs.

1. Save it as **public/js/nullable_relationship_hack.js**

1. Then add it in **config/voyager.php** under additional_js:
```php
'additional_js' => [
    'js/nullable_relationship_hack.js',
],
```

**Comment by emptynick** [comment] 2018-04-17 22:30
Fixed in https://github.com/the-control-group/voyager/pull/2931

**Closed as completed by emptynick** 2018-04-17 22:30 UTC

**Comment by textoo** [comment] 2018-06-26 11:03
@emptynick i think #2931 is not related with this issue, 
problem here is to allow NULL value in belongsTo relationships dropdown , the fix you referenced is about belongsToMany .

**Comment by emptynick** [comment] 2018-06-26 11:05
> It is not possible to remove all value for a many to many relation even if it is nullable. Almost one value must exists saving the master table.

In the original issue.

**Comment by textoo** [comment] 2018-06-26 12:33
you're right, i did not see that part, sorry.
btw the title and the first part is related to belongsTo relation : 

> It is required to select a value for foreign key even if it is nullable, first value from parent table always selected in relation select dropdown.

this is still true,
so the issue is partialy solved (and should have been divided in two).
i guess the best way to deal with it is to open a new issue ?
