### ISSUE TITLE
Sidebar and body animation on page load

### ISSUE THREAD

**Issue by akazorg** [thedevdojo/voyager#877] opened 2017-03-07 04:22 UTC
Hello @frondor, I've test it out and found a couple of things to sort out.

**1. Extra icon**
The extra icon is useless, and also the need of clicking twice (1st for opening the sidebar, 2nd to click the anchor in order to save the state).

> When the user click for open the sidebar, it should save the state in that moment.

**2. Web Storage or Cookie?**
The unpleasant animation I mention to you before is happening (image attach).
I've tested and this occur in Ubuntu (Firefox, Chrome) and Win 7 (Firefox).

Don't you like cookies? :)
I really don't care if we use cookies or data storage, we just need to make it work properly.

![peek 2017-03-07 02-51_sidebar_behaviour](https://cloud.githubusercontent.com/assets/34574/23641578/e813af72-02ec-11e7-884a-68a7d6387934.gif)

**Comment by Frondor** [comment] 2017-03-07 05:20
1. No, because **it's an opt-in feature**, which is not active by default. People who makes use of a mobile device to browse their admin panels may want to keep this feature disabled for obvious reasons (screen width).
And yes, you need to click it "twice" **only the FIRST time** you activate the feature, then it saves the state to `localStorage` and you won't need to activate it never again in that browser.

2. As you can see, localStorage is working perfectly with `side-menu` (it doesn't animate on page load), what you see there is a glitch indeed, but that's because [the script is not properly targeting the page container](https://github.com/the-control-group/voyager/blob/master/resources/views/master.blade.php#L103) to do the same as it does with `side-menu`: temporarily disable `transition` property. (or not, and the problem is somewhere else)

I might see what's wrong with that selector and properly disable that transition later today.

**Comment by akazorg** [comment] 2017-03-07 06:26
It makes no sense to click twice, really, nor hiding the breadcrumb.

I've read firefox has some issues with localStorage. I'm afraid that it wont work right with some browsers.

What's the reason for not using cookies?

**Comment by Frondor** [comment] 2017-03-07 19:27
I've already explained it twice. If you make the sidebar to remember its state by only clicking the hamburger menu (which is the only way you can open it when in small screens) then the whole improvement was useless, because sidebar shall be open on every page load even on small screens. That's why we **need** the anchor icon. We can move it, yes, but we need it.

Seems like you don't use a mobile device to browse your admin panel, which makes sense, we are developers that work from a computer. But we may work with other non-developer people; assistants, community managers, or simply employers... Its 2017 and I can ensure all of them are more likely to use a mobile device to browse it. (I do)

I understand you, some people like you may prefer to keep the sidebar open, that's your choice. Me and other people that not only browse the panel from a mobile device, but also those panels have big sized tables ([see this comparison](http://i.imgur.com/7EnFIvd.png)). You'll want to use the minimal sidebar for that site.
And that's not the only reason, some people simply like compact things.

So the best approach here is to **make it optional**. You only "click twice" the FIRST time to activate the feature and remember sidebar's status. Then you shall keep using the panel normally like you wanted to, "cross-session".
Now, why isn't it activated by default? Because of mobile devices.

> What's the reason for not using cookies?

Decoupling design logic from the PHP code.
We can still get/set cookies with javascript only, but now is the _cookie vs localStorage_ thing, in this case, localStorage would be faster.

> I've read firefox has some issues with localStorage. I'm afraid that it wont work right with some browsers.

Yes but no, the feature is widely supported by all browsers now (except ie8 -_what kind of website administrator uses ie8??_-).

Its been a lot of time since Firefox is an evergreen browser. I've tested it on both Firefox and Chrome, today I did it in ie9 and it did work flawlessly (besides that glitch you found with `.app-container` transition still being triggered).

So summing it up, there's a glitch to be fixed, and stop hiding the breadcrumb when sidebar is expanded. I can fix those in a couple of hours when I arrive home.

**Comment by akazorg** [comment] 2017-03-07 23:54
You can repeat yourself a thousand times, write a huge argument, and at the end:
- the need of click twice, is **wrong**.
- the extra icon is awful, screwing the screen.

If you require that icon, it's basically a bad design, and we should find another approach.

**Comment by akazorg** [comment] 2017-03-08 00:05
@Frondor, you closed this?!

This is nor even open for discussion?

You just came, dictate your ideas, close the issue... it's very bad, I totally disagree and I think you have too much permission hover this project.

@tnylea, @marktopper, @fletch3555, @abdgad, this will not work in the future.

**Comment by Frondor** [comment] 2017-03-08 00:25
> the need of click twice, is wrong.

You think its wrong, you don't like it, I know that. But I wonder why can't you understand the point that we NEED that feature, probably because you are not a mobile user, hence you don't understand how important is to provide a better UX for those users as well.
Ok, provide the fix yourself as long as mobile UX doesn't get compromised. You want the hamburger menu to do what actually the anchor icon does, that's not a fix and I already explained why.

You write things like "I've read firefox has some issues with localStorage" and "*this will not work in the future.*" but where are the arguments man? If you wanted to discuss something, you had to provide arguments.

> the extra icon is awful, screwing the screen.

I won't argue about that, it's a matter of taste. I don't mind if someone decides to change it as long as the feature keeps working as intended.

> @Frondor, you closed this?!

The commit did, but you @mention me so I guessed it was meant for me to address it.
You are free to discuss EVERYTHING about voyager and send PRs, please, don't dramatize something this small.

> I think you have too much permission hover this project.

Yes? I didn't ask for it, I guess my contributions were good enough to be promoted. It's an open source project and this is how it works. I've talked with Mark few times and he knows I'm not that authoritative. You came with an issue, you mentioned me and all I did was addressing exactly what you described. 
The issue wasn't formatted as a "discussion" to my understanding. We can always use slack for that tho, the crew is always there.

My final statement:

You complain about TWO clicks to activate something that counts as a *theme feature*. Haven't you seen any theme with features yet? Like the ones that let you choose the theme colors, font sizes, etc?? That's how they work! You have to activate the feature ONCE, and that's all!
At the end, you're creating a problem when there's none actually, and there are so many other things (way more important) to address before this.

If you don't like it, you can change it! or ask to @marktopper or any other of the crew to do it for you, I don't care. The only thing I care is to improve UX for all users and don't make something that can be browsed only from desktop screens. We are not wordpress, thankfuly.

**Comment by Frondor** [comment] 2017-03-08 00:25
I'll reopen this just for you, because I hate any kind of drama.

**Comment by akazorg** [comment] 2017-03-08 01:43
I'm here to work, for creating a great product, with easy going discussions.
Take care

**Comment by fletch3555** [comment] 2017-03-08 03:51
@akazorg and @Frondor.  We all appreciate the work you've both put into this project over the last few months, and I hope that can continue.  With that said, here's my thoughts on the current issue.

@Frondor: I understand you came in to respond to an issue you were tagged in.  I appreciate your detailed (albeit somewhat long-winded) responses.  However, many of your comments do come across as extremely defensive and, in some cases, aggressive.  The claim that we **NEED** this feature (especially your way of doing it) is an "absolute", and absolutes are rarely true.

@akazorg: I appreciate your diligence with testing and opening these issues as you find them.  I also appreciate your willingness to work through solutions for them.  However, some of your language comes across as unprofessional and very argumentative.  Additionally, your accusation that he has too much control in this project is unfounded.  As with my comments to Frondor, there is absolutely no **NEED** to do anything any particular way.

I want to commend you both for not allowing this to spin wildly out of control.

---- 

Now for the original issue here.  I think there are multiple possible solutions to this, and I believe we can reach a compromise.

I'm not sure I understand the issue here.  @Frondor, you mention mobile users need this, but as a mobile user, I can't imagine why I would ever want that menu to remain open between page changes.  As a desktop user, I could see myself maybe wanting to minimize it, but feel I would likely want it to just stay open.  Maybe that's just me.

Perhaps we make this an optional feature? It could be controlled by a `Setting` or config value.  Thoughts?

**Comment by Frondor** [comment] 2017-03-08 05:23
@fletch3555 my apologizes for extensive responses, in these cases when a feature has been suggested I prefer to explain myself as good as I can to avoid long threads and save replies (and quotes make them even bigger).
 
Now, the comments here may sound defensive for you probably because you're not aware of #827 where akazorg reported "bad behaviors" and I provided not only the arguments of why we "need" this, but also bug fixes.
I attended to all his complaints on that issue, [he personally told me the PR looked good](http://i.imgur.com/buz3WP2.png), and now he seems to have changed his mind. :confused: I fixed what he reported on his second point and provided an argument of why he has to make a second click to activate what works as a theme option, that you activate only once. Then all the @mention thing started and this turned into a childish drama. (I feel so embarrassed to be in the middle, for real)

> I'm not sure I understand the issue here. @Frondor, you mention mobile users need this, but as a mobile user, I can't imagine why I would ever want that menu to remain open between page changes. As a desktop user, I could see myself maybe wanting to minimize it, but feel I would likely want it to just stay open. Maybe that's just me.

Akazorg wants the sidebar to remember its state by default, which turns out into an expanded sidebar after every page load, even on small screens (taking aprox. 80% of the page content and forcing you to manually close it after navigation).

> Perhaps we make this an optional feature? It could be controlled by a Setting or config value. Thoughts?

So I came with this solution, an optional "sidebar anchor" button, available only for desktop screens which allows you to keep the sidebar always open. And if you prefer it to be compacted, then switch it, as easy as that.
The button and script could be a setting but that leave us where we started, with a stateless sidebar (which I like).

So you decide guys, I don't enjoy programming when things like this show up.

**Comment by akazorg** [comment] 2017-03-08 05:41
@fletch3555 unprofessional for not elaborate the obvious? This isn't a new topic, anyway. Did you see the image?

@Frondor does have too much permission, it's the reality. It's totally incorrect to start a discussion, enter in monologue mode, close it, ignore others opinion. Doesn't seam unfounded -.-

This is too much Frondor, you start to change the facts to stay pretty now? I did not change my mind. The image you've sent me for the first time looked good, here (https://i.gyazo.com/24bbe894254b2673b25148f7c44e716c.gif), the one I reported is on the top of this page.

This is a waste of time, take care.

**Closed as completed** 2017-03-08 05:42 UTC
Labels: design
