### ISSUE TITLE
Error update image in settings area

### ISSUE THREAD

**Issue by virzillo** [thedevdojo/voyager#3158] opened 2018-05-09 12:32 UTC
- Laravel Version: 5.6
- Voyager Version: 1.1.1
- PHP Version:7.2
- Database Driver & Version:
MariaDB 10.1.31-MariaDB
### Description:
Hello, when i try to change the images of the setting area, just one image, after i save all the other images (admin logo,background admin) resets.
i'm sure with the old version of voyager all was fine.
i'm very sorry for my english.
thanks and good job, voyager is amazing

### Steps To Reproduce:
backend - settings tab - change logo site - save
logo site correctly update, all the other image in the other tabs disappered.

**Comment by emptynick** [comment] 2018-05-09 12:44
Please search before opening a issue.
Duplicate of https://github.com/the-control-group/voyager/issues/3059 and https://github.com/the-control-group/voyager/issues/2934

**Closed as completed by emptynick** 2018-05-09 12:44 UTC
Labels: duplicate
