### ISSUE TITLE
Cannot remove permissions from Role

### ISSUE THREAD

**Issue by kingIZZZY** [thedevdojo/voyager#4791] opened 2020-02-28 14:24 UTC
- Laravel: v6.17.1
 - Voyager: v1.3.1
 - PHP: 7.2
 - Database: postgresql 10

## Description
Unchecking permissions of a role and then saving the Role has no effect; the Role still has those permissions and they remain checked upon editing again.

## Steps To Reproduce
0. Create a new custom Role, add some permissions and save
1. Go to edit this new custom role (ex. http://127.0.0.1:8000/admin/roles/3/edit )
2. Uncheck some of the permissions selected in step 0
3. Scroll down and Save
4. Go back to Step 1: the permissions are still there and not removed

## Expected behavior
The entire permissions array should be considered and "replaced" into the database, but instead it's probably just saving the submitted IDs, not removing any non-submitted IDs

**Comment by kingIZZZY** [comment] 2020-02-28 14:28
I'll be this is a general issue in the code-base logic, about submitting deletions by way of absence of data (ex. lack of certain permission IDs being submitted) is not being considered and not deleted, only presence of data (ex. only the permission IDs submitted) are noticed and are being saved/updated.

**Comment by MrCrayon** [comment] 2020-02-28 14:35
It was a problem with routes, please search before opening an issue.

Duplicate of #4668 you can find a fix there.

**Closed as completed by MrCrayon** 2020-02-28 14:35 UTC
Labels: duplicate

**Comment by kingIZZZY** [comment] 2020-02-28 18:04
Voyager: v1.3.1
Issue still persists
This bug as well as bug #4668 are NOT fixed yet, i.e. default vanilla installation of voyager still results in erroneous saving of users/roles

**Comment by kingIZZZY** [comment] 2020-02-28 18:17
# Workarounds

The workaround mentioned in #4668 setting the VoyagerRoleController in role's BREAD work.
See also the details in this comment https://github.com/the-control-group/voyager/pull/4669#pullrequestreview-337527167

However - as of yet a vanilla install of voyager without visiting these github issues and manually implementing the workarounds still has the bug
