### ISSUE TITLE
[BUG] Image Removed but Received "Error Removing File"

### ISSUE THREAD

**Issue by yoonwaiyan** [thedevdojo/voyager#4093] opened 2019-04-20 14:30 UTC
## Version information
 - Laravel: v5.8
 - Voyager: v1.2.1
 - PHP: 7.3.2
 - Database: MySQL 8.0.15(local) / 5.6.43(server)

## Description
I'm trying to remove one image from a Multiple Images field, but I received "Error removing file" error instead. When I refreshed the page, the image is removed. I tried to debug directly on edit-add.blade.php and VoyagerMediaController.php within vendor folder and I found out that everything works, but somehow the API result isn't returned in the jquery POST request.

In the code, somehow, the response seems valid after reorganized the code for debug purpose:
```php
            $response = [
               'data' => [
                   'status'  => 200,
                   'message' => __('voyager::media.file_removed'),
               ],
            ];

            Log::alert('response');
            Log::alert($response);

            return response()->json($response);
```

## Steps To Reproduce
1. Go to /admin
2. Click on one bread collection with multiple images field enabled
3. Create one new record with multiple images attached
4. Edit the record
5. Click on 'x' at any image of the multiple images field
6. Received 'Error removing file'

## Expected behavior
Expecting the API result to return success response and being captured properly in `$.post` request.

## Screenshots
![remove_image](https://user-images.githubusercontent.com/3081772/56458642-e267d300-63bb-11e9-86c8-c843cb2f00cf.gif)

<img width="745" alt="Screen Shot 2019-04-20 at 10 12 50 PM" src="https://user-images.githubusercontent.com/3081772/56458463-7be1b580-63b9-11e9-9e8e-2d135167cf51.png">

**Comment by MmKargar** [comment] 2019-04-20 14:43
1 - check storage link have not problem.
2- check you have granted user the media page in permisions.
it should work.

**Comment by yoonwaiyan** [comment] 2019-04-20 14:50
Since Voyager could read and upload images, I believe this issue is not related to storage and permission. I could see the `$response` being logged in my log file but somehow jquery received empty response.

```
[2019-04-20 14:29:08] local.ALERT: array (
  'data' => 
  array (
    'status' => 200,
    'message' => 'File removed',
  ),
)  
```

**Comment by MrCrayon** [comment] 2019-04-22 11:01
@yoonwaiyan can you check what's in Network Headers tab?
It might be related to the bug report I just opened #4095

**Comment by yoonwaiyan** [comment] 2019-04-22 14:00
@MrCrayon the headers looks ok and and it returns 200, in my case it's probably something weird going on between controller return and jquery handling response. 
<img width="581" alt="Screen Shot 2019-04-22 at 9 33 21 PM" src="https://user-images.githubusercontent.com/3081772/56502884-7c5b8700-6546-11e9-80e9-7b162f53839c.png">


This is the script I've modified to console log the response:
```
$('#confirm_delete').on('click', function(){
    $.post('{{ route('voyager.media.remove') }}', params, function (response) {
        console.log("response", response);
        if ( response
            && response.data
            && response.data.status
            && response.data.status == 200 ) {

            toastr.success(response.data.message);
            $file.parent().fadeOut(300, function() { $(this).remove(); })
        } else {
            toastr.error("Error removing file.");
        }
    });

    $('#confirm_delete_modal').modal('hide');
});
```
but my console log shows nothing on the response:
<img width="509" alt="Screen Shot 2019-04-22 at 9 59 54 PM" src="https://user-images.githubusercontent.com/3081772/56504078-fe997a80-6549-11e9-8a9e-f17455f19bca.png">

**Comment by MrCrayon** [comment] 2019-04-22 14:18
No idea what could cause that looking at VoyagerMediaController method called, you could try to debug that file to understand where script ends, since the image is removed from database I would start looking after https://github.com/the-control-group/voyager/blob/5096e8582c52355bc9a4e0db7c15f8773818a271/src/Http/Controllers/VoyagerMediaController.php#L328

_Edit: wrong line linked_

**Comment by yoonwaiyan** [comment] 2019-04-22 15:36
@MrCrayon yup, I've debug VoyagerMediaController and I'm certain that the data returned in https://github.com/the-control-group/voyager/blob/5096e8582c52355bc9a4e0db7c15f8773818a271/src/Http/Controllers/VoyagerMediaController.php#L348-L353 is correct (as mentioned and code modified as shown in OP), but somehow `return response()->json()` returns Content-Type header as text/html (!). I tried everything I can find to force return as json type but nothing works.

**Comment by MrCrayon** [comment] 2019-04-23 12:21
Sounds like a nightmare to debug.
I can't think how could be different but just to check: is the address from which is starting the request also on localhost:8000?
Because if protocol, domain and port don't match there might be problems with CORS
Is there any error on Console tab?

**Comment by yoonwaiyan** [comment] 2019-04-23 15:06
@MrCrayon yes, both ends are hosted on port 8000 locally. My Console tab is clean (except logging `response`) as shown in the screenshot above, and Network tab returns status code 200.

btw, I hope that any contributor / maintainer could let me know if any of them are trying to replicate this issue or solving it though. I want to help out too but my knowledge on PHP / Laravel is not as strong as Ruby on Rails but I did my best to debug and try to make it work as expected.

**Comment by MrCrayon** [comment] 2019-04-23 15:31
@yoonwaiyan sorry I missed console screenshot
I can't reproduce the problem (but I'm using v1.2.3) it sounds quite weird, I can only advise you to:
Try clearing views cache
Try with a different browser
Try with a fresh install
Try in a different server if you can

Good luck

**Comment by normangoh** [comment] 2019-04-30 08:58
@yoonwaiyan Just want to check, does the folders have the correct permissions? Can you try to go to Media Manager and delete a file from there and see what it does.

**Comment by yoonwaiyan** [comment] 2019-04-30 09:20
@ohmygod8 tried, it's removing files with proper message returned.

**Comment by MrCrayon** [comment] 2019-04-30 09:22
Actually, unless this was different in v1.2.1,  files are not removed from filesystem only the reference from db is removed, so it can't be a problem with file permissions.

**Comment by normangoh** [comment] 2019-04-30 09:51
@yoonwaiyan You are right, files might not be removed physically. I need to test it again haha..

**Comment by edge104** [comment] 2019-05-08 08:06
same problem :-(

**Comment by MrCrayon** [comment] 2020-01-01 09:35
Since many things have changed on file removal I'm closing this one.

Please update and if you are still experiencing a problem you can open another issue.

**Closed as completed by MrCrayon** 2020-01-01 09:35 UTC
Labels: possible bug
