### ISSUE TITLE
Remove "None" default value on relationship select box

### ISSUE THREAD

**Issue by dmitrymaslov99** [thedevdojo/voyager#5190] opened 2021-01-08 21:51 UTC
## Version information

 - Laravel: v8.21.0
 - Voyager: v1.4
 - PHP: 7.4.11
 - Database:  MySQL 5.7.26

## Description
It is possible to remove the default value "None" on a select box when the relationship is required?

## Steps To Reproduce
Add a relationship (BelongTo for instance) with the BREAD screen. In data creation screen, "None" is showing up in the dropdown list.

## Expected behavior
Get "None" option not displayed.

## Screenshots
<img width="898" alt="Снимок экрана 2021-01-09 в 00 49 05" src="https://user-images.githubusercontent.com/36110676/104067613-85a5ef00-5214-11eb-831c-d9ef1569bcc7.png">

**Comment by fletch3555** [comment] 2021-01-09 02:42
That option is tied to the nullability of that field.  I believe the criteria are if it's required or not-null.

Also, per the issue template, questions are best asked in our slack group

**Comment by MrCrayon** [comment] 2021-01-09 03:53
I think even if it started as a question it turns out it's a bug.
Normally Voyager sets a field as required if it's not nullable and there is a check while showing options to show "None" only if field is not required.
The problem is that even if foreign key is set as not nullable (so required) a belongsto relationship created that reference that field is not set as required so it will always show "None".

Example:
In posts BREAD we set `category_id` as not nullable then we create a `belongsTo` Category relationship, it will create a `data_row` record with `field` = `posts_belongsto_category_relationship` and `required` = 0 instead of 1.

A quick dirty fix is to set in database the relationship fields as required in `data_rows` table BUT that change will get lost if you save again BREAD configuration from the interface.

**Comment by dmitrymaslov99** [comment] 2021-01-09 11:42
> Думаю, даже если это началось как вопрос, оказалось, что это ошибка.
> Обычно Voyager устанавливает поле как обязательное, если оно не допускает значения NULL, и есть проверка при отображении параметров, чтобы показать «Нет», только если поле не требуется.
> Проблема в том, что даже если внешний ключ установлен как не допускающий значения NULL (что является обязательным), отношение «принадлежащее к нему», созданное для этой ссылки, это поле не установлено должным образом, поэтому всегда будет отображаться «Нет».
> 
> Пример:
> в сообщениях BREAD мы устанавливаем `category_id`значение, не допускающее значения NULL, затем мы создаем `belongsTo`отношение категории, оно создаст `data_row`запись с `field`= `posts_belongsto_category_relationship`и `required`= 0 вместо 1.
> 
> Быстрое грязное исправление - установить в базе данных поля отношений, как требуется в `data_rows`таблице, НО это изменение будет потеряно, если вы снова сохраните конфигурацию BREAD из интерфейса.

Tell me how you can fix it? There is no mandatory clause in a relationship (
![image](https://user-images.githubusercontent.com/36110676/104090588-c9d2d700-5288-11eb-8bc3-790b8b70e095.png)

**Comment by MrCrayon** [comment] 2021-01-09 12:53
@dmitrymaslov99 no idea where that **Many to one** is coming from there is no such relationship in Voyager (or even Laravel I think).

You cannot fix your problem from the interface right now, to fix your problem you have to:

Wait that my PR is merged then: wait for a new Voyager version to be released  **OR** use 1.4-dev branch.

**OR**

Use the branch in my fork

**OR**

Change manually your **database** and set required for the relationship field (this change is lost if you save from the interface)

**Comment by dmitrymaslov99** [comment] 2021-01-09 13:00
> @dmitrymaslov99 no idea where that **Many to one** is coming from there is no such relationship in Voyager (or even Laravel I think).
> 
> You cannot fix your problem from the interface right now, to fix your problem you have to:
> 
> Wait that my PR is merged then: wait for a new Voyager version to be released **OR** use 1.4-dev branch.
> 
> **OR**
> 
> Use the branch in my fork
> 
> **OR**
> 
> Change manually your **database** and set required for the relationship field (this change is lost if you save from the interface)

Understood you. Thank you. Tell me how can I install 1.4-dev?

**Comment by MrCrayon** [comment] 2021-01-09 15:41
```
composer require tcg/voyager:1.4.x-dev
```

**Comment by dmitrymaslov99** [comment] 2021-01-09 15:50
> ```
> composer require tcg/voyager:1.4.x-dev
> ```

Installed it. It didn't help(
![image](https://user-images.githubusercontent.com/36110676/104096080-6ad28980-52ab-11eb-89e0-575b35f4f3f6.png)
![image](https://user-images.githubusercontent.com/36110676/104096087-70c86a80-52ab-11eb-8c46-aba1fd62aeb3.png)
![image](https://user-images.githubusercontent.com/36110676/104096095-7756e200-52ab-11eb-8cb5-18f9c5f72d5e.png)

[composer.txt](https://github.com/the-control-group/voyager/files/5791353/composer.txt)

**Comment by MrCrayon** [comment] 2021-01-09 15:56
Because my PR has not been merged yet.

>**Wait that my PR is merged** then: wait for a new Voyager version to be released OR use 1.4-dev branch.

**Closed as completed** 2021-01-28 12:04 UTC
Labels: type:bug, type:question, addressed

**Comment by dmitrymaslov99** [comment] 2021-02-01 12:56
The problem is not solved?

**Comment by dmitrymaslov99** [comment] 2021-02-01 12:57
> Because my PR has not been merged yet.
> 
> > **Wait that my PR is merged** then: wait for a new Voyager version to be released OR use 1.4-dev branch.



The problem is not solved?
