### ISSUE TITLE
Unable to use validators on BREAD image field

### ISSUE THREAD

**Issue by sergiocastrovale** [thedevdojo/voyager#3686] opened 2018-10-23 16:35 UTC
## Version information

 - Laravel: v5.6
 - Voyager: v1.1
 - PHP: 7.1.3
 - Database: MySQL 10.1.33-MariaDB

## Description

I'm trying to validate an image upload field in three ways:

1. Test if it is an `image`
2. Test if `mimes:jpg,jpeg`
3. Test if `max:500`

None of these seem to work. Here's what's thappening when I try to add a 20kb jpg image:

![screenshot_7](https://user-images.githubusercontent.com/8822036/47376337-3f731c80-d6ea-11e8-8079-2cd7384c2596.png)

Here's what happens if I try to upload a 600kb image, remove all rules and just leave `max:500`. The error shows up but no page is rendered whatsoever:

![screenshot_4](https://user-images.githubusercontent.com/8822036/47375900-3d5c8e00-d6e9-11e8-8659-2b8d392d3fae.png)

## Steps To Reproduce

1. Add a field such as `$table->string('image')->nullable();` to a table
2. Configure your BREAD for that table as such:

![screenshot_5](https://user-images.githubusercontent.com/8822036/47376059-9cba9e00-d6e9-11e8-9e0d-30c72e91b4a5.png)

![screenshot_6](https://user-images.githubusercontent.com/8822036/47376065-9e846180-d6e9-11e8-9846-cc8153dabb6c.png)

This is the options object:

```
{
    "resize": {
        "width": "254",
        "height": "222"
    },
    "quality": "70%",
    "upsize": true,
    "thumbnails": [
        {
            "name": "small",
            "scale": "75%"
        }
    ],
    "validation": {
        "rule": "image|mimes:jpg,jpeg|max:500"
    }
}
```

## Expected behavior
Each of the validators should ... validate as expected.

## Additional context
My php.ini `upload_max_filesize` is `20M`.

**Comment by jessmancia** [comment] 2018-10-31 17:42
@sergiocastrovale Did you find any solution? I have the same problem

**Comment by sergiocastrovale** [comment] 2018-10-31 18:03
Not yet, unfortunately :(

**Comment by emptynick** [comment] 2018-12-27 22:46
Closing as a duplicate of https://github.com/the-control-group/voyager/issues/1501

**Closed as completed by emptynick** 2018-12-27 22:46 UTC
Labels: duplicate
