### ISSUE TITLE
Cant change a admin background image

### ISSUE THREAD

**Issue by AlbertSigsbert** [thedevdojo/voyager#5133] opened 2020-10-30 13:28 UTC
version information
Laravel: v7.24
Voyager: v1.4
PHP: 7.3
Database: MySQL 5.7.24
Description:
Cant change a admin background image

Additional context
Admin Background Image change result to Intervention\Image\Exception\NotSupportedException
**Reading Exif data is not supported by this PHP installation.**
##Please help if it is another error causing it and how can i fix it

**Comment by fletch3555** [comment] 2020-10-30 14:18
Still not a bug.  Please stop spamming issues when we've already responded to your others.

Duplicate of #5130 and #5132

**Closed as completed by fletch3555** 2020-10-30 14:18 UTC
Labels: duplicate
