### ISSUE TITLE
Sidebar bad behavior

### ISSUE THREAD

**Issue by akazorg** [thedevdojo/voyager#827] opened 2017-02-24 20:41 UTC
- Laravel Version: 5.4
- Voyager Version: 0.11.2

![peek-sidebar-bug-2017-02-24 20-30](https://cloud.githubusercontent.com/assets/34574/23320453/c09cb2b2-fad2-11e6-922f-9aaece04ee4c.gif)

**Comment by akazorg** [comment] 2017-02-27 15:25
Hello @marktopper 

There are still some bugs with the side-bar:
1. side bar doesn't remember it's state anymore (if it's open/closed)
2. the dark overlay is still appearing, it looks really unpleasant
3. expand the menu item when a sub-item is selected

**Comment by marktopper** [comment] 2017-02-27 16:45
I think we should open a issue for those to remember them.
Could you open a issue for this @akazorg ?

**Comment by marktopper** [comment] 2017-02-27 16:46
Good point!

**Comment by turtuga** [comment] 2017-03-01 12:27
save state @Frondor remove it :(

**Comment by Frondor** [comment] 2017-03-01 13:19
Not a bug, neither a bad behavior.

This is one change I made because mobile UX was terrific due to the sticky sidebar always showing on each page, forcing you to manually close it, which was *really* annoying.
You have to consider wider BREAD pages, with huge tables (like 8-9 columns), if you keep sidebar open you'll be wasting horizontal space for the table to properly display. Still, you can simply hover it with your mouse and the animation is fast enough to let you quickly click the item you want.
Once again, it's designed like that to make a better mobile browsing of voyager.
Probably I can send a PR with a new button next to the hamburguer menu that only shows up for medium to large screens, making the sidebar sticky. I'm a bit busy these days but that won't steal much time from me.

The overlay is there as an UX pattern and it works as expected. Its function is to induce the user to guess about closing the sidebar by tapping/clicking outside. Probably, its color should be theme-dependent and black by default.
And as you can see, it appears only on small screens using bootstrap media queries,  That's how responsive design works. If you resize for a smaller window, the browser will interpret that you're from a mobile device. Also it appears when *half of the document is hidden under sidebar*, hence you'll have to close sidebar to keep browsing the contents anyway (due to screen size). It's actually pretty good UX in my opinion.

I don't see any problem with child items in menu actually. I can perfectly expand them and sidebar won't hide until I `mouseleave` it. If you found a bug about it, please help me to reproduce it.
Or you meant "_expand the menu item when a sub-item is active by current route_"?

**Comment by akazorg** [comment] 2017-03-01 18:09
There are a few things to consider.

1. Sidebar should **remember it's state**. It's the User who decides whether he wants the sidebar open or closed.

2. I agree with the overlay pattern, but honestly, the result is unpleasant. Maybe changing the color, and make it work full height, will make it look much better.

3. Yes, I mean "expand the menu item when a sub-item is active by current route".

**Comment by marco-solare** [comment] 2017-03-01 19:35
+1 for "sidebar should remember it's state" - is the behaviour I was expecting

**Comment by Frondor** [comment] 2017-03-01 19:47
Problem with it was it wasn't correctly implemented.
I'm preparing a PR with the option to enable/disable stickiness using `localStorage` instead of cookies.

**Comment by akazorg** [comment] 2017-03-01 22:03
@Frondor, when we first implemented sidebar state #150, we also opted for using localStorage, but it didn't work out because we were unable to get the stored value before page load, and we need that, otherwise the sidebar have to be processed after it's displayed, and that will cause a sidebar transition on every page load.
Using a cookie might be the best option.

**Comment by Frondor** [comment] 2017-03-02 20:15
Not actually, `localStorage` is there in the very moment the page loads, hence I can set a script to load as soon as possible and disable momentarily `transition` properties for those elements.

**Closed as completed** 2017-03-03 06:53 UTC
Labels: type:bug, help wanted, design
