### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by futsurdmitriy** [thedevdojo/voyager#4153] opened 2019-05-20 18:36 UTC
## Version information
 - Laravel: v5.8.15
 - Voyager: v1.2.3
 - PHP: 7.2.18-1
 - Database: PostgreSQL 11.3

## Description
Menu item that was added and then removed stays visible in menu items list view. Cache supposed to be cleared after destroy action.

## Steps To Reproduce
1. Go to the admin panel.
2. Click on Tools module and enter to "Menu builder" section.
2. Create new menu by pressing "Add New" button.
3. Name your menu somehow and after you will be redirected to list of your menus go to the menu builder of menu that you has just created.
4. Add some new items to menu.
5. Delete some of them.
Result: Items doesn`t remove from list and they are still visible. If you try to delete some of them again you will be redirected to 404 page because items was removed from database.

## Expected behavior
Items removes from menu items after they were deleted. Cache suppose to be cleared after destroy action.

**Comment by fletch3555** [comment] 2019-05-20 18:41
PR welcomed

**Comment by really4you** [comment] 2019-05-21 23:47
because the menu model function display：
\Carbon\Carbon::now()->addDays(30)；
use：\Cache::flush();

**Comment by MrCrayon** [comment] 2019-05-22 02:48
Duplicate of #4071 
@fletch3555 I thought you merged it already :smile: #4083

**Comment by fletch3555** [comment] 2019-05-22 02:59
Fair point.  We did, but haven't released a new version yet.

**Closed as completed by fletch3555** 2019-05-22 02:59 UTC
Labels: duplicate
