### ISSUE TITLE
Minor bug in breadcrumb (db manager)

### ISSUE THREAD

**Issue by reficul** [thedevdojo/voyager#1827] opened 2017-09-22 14:11 UTC
- Laravel Version: 5.5
- Voyager Version: 1.0.2
- PHP Version:7
- Database Driver & Version: MariaDB

### Description:
Bread item on breadcrumb in database->edit bread point to nothing.

**Comment by fletch3555** [comment] 2017-09-22 18:57
Out of curiosity, what do you think it should point to?

**Comment by reficul** [comment] 2017-09-23 06:41
I can make the same question to you :D
I only try to click and return an error.

**Comment by fletch3555** [comment] 2017-09-23 12:17
I was just asking for your input on what you think that particular link should point to.

**Comment by reficul** [comment] 2017-09-23 12:19
Maybe we only need  
-> Database -> Bread Edit
instead of
-> Database -> Bread -> Edit

**Comment by whyayala** [comment] 2017-10-05 20:45
I'd like to offer some recommendations for this too.

The parsing done on the bread crumbs is pretty nasty and is dependent on the assumption that each segment plus it's prefixes is a uri that points to another page. The problem is that;

**_database/table/bread_** isn't defined in routes and
 **_database/table_** seems to point to a page that displays model info? 

I think this was supposed to be the response from an ajax call for the modal dropdown on the **_database_** index page, but I haven't looked into it that much so pure speculation.

make **_database/table_** a modal dropdown on that page, and give **_database/table/bread_** a route definition. Maybe point it to **_database/table/edit_** ?

The other alternative would be to rewrite that piece of code parsing the request segments to handle some edge cases like this one. Personally I think it needs that and I would move it into a partial so it can be referenced outside of navbar.blade.php.

**Comment by emptynick** [comment] 2019-01-05 10:09
Closing as #3850 was merged (into 1.x, to be released in a future 1.2 release)

**Closed as completed by emptynick** 2019-01-05 10:09 UTC
Labels: possible bug
