### ISSUE TITLE
Missing Route Parameters in built in database module

### ISSUE THREAD

**Issue by vkiranmaniya** [thedevdojo/voyager#4595] opened 2019-11-29 17:01 UTC
## Version information

 - Laravel: v6.6.0
 - Voyager: v1.3.0
 - PHP: 7.2
 - Database: MySQL 5.7.25

## Description
I'm getting this exception in fresh voyager project.
```
Facade\Ignition\Exceptions\ViewException
Missing required parameters for [Route: voyager.bread.delete] [URI: admin/bread/{id}]. (View: /Applications/MAMP/htdocs/odhnifashion/vendor/tcg/voyager/resources/views/tools/database/index.blade.php)
http://localhost/odhnifashion/public/admin/database
```
## Steps To Reproduce
1. Follow the installation steps in the documentation
2. go-to database page, you'll get this exception.

## Expected behavior
The documentation says there should be an issue with table primary key, I've checked. But every modal has a primary key. However, it's a fresh installation of a voyager.

## Screenshots
![image](https://user-images.githubusercontent.com/22276302/69882942-fda6a380-12f7-11ea-9ebc-b70cee4e3e74.png)

## Additional context
Running on MacOS and MAMP

**Comment by emptynick** [comment] 2019-11-29 17:02
Please search before opening issues.
Duplicate of https://github.com/the-control-group/voyager/issues/4586

**Closed as completed by emptynick** 2019-11-29 17:02 UTC
Labels: duplicate
