### ISSUE TITLE
When bootstrap 4 is used rather than bootstrap 3.3.7

### ISSUE THREAD

**Issue by yanuaraditia** [thedevdojo/voyager#5094] opened 2020-09-24 07:11 UTC
## Version information

 - Laravel: v8.6.0
 - Voyager: v1.4
 - PHP: 7.3.11
 - Database: MySQL 8.0

## Description of problem
My team was using Voyager for many big web panel project. Voyager is a good kit, but we had so many problems when starting develop the front-end of it, Bootstrap 3.3.7 is gold but Bootstrap 4.x is easier to use.  Grid alert, button, modal, label, badge, etc in bootstrap 3.3.7 was crappy and get so confusing to use it.

## Proposed solution
Separate the js, css files that Voyager has with bootstrap so we can use different version of Bootstrap that we prefer

## Alternatives considered
Upgrade the app.css to Bootstrap 4 support

## Additional context
[Bootstrap 3 end of life](https://blog.getbootstrap.com/2019/07/24/lts-plan/)

**Comment by emptynick** [comment] 2020-09-24 07:12
Please search before opening issues.
Duplicate of https://github.com/the-control-group/voyager/issues/4762, https://github.com/the-control-group/voyager/issues/3908, https://github.com/the-control-group/voyager/issues/3347 and possibly some more.

**Closed as completed by emptynick** 2020-09-24 07:12 UTC
Labels: duplicate
