### ISSUE TITLE
The BelongsTo SelectBox is bugged on Edit - Doesn't Update the value

### ISSUE THREAD

**Issue by PointfullDevelopers** [thedevdojo/voyager#2996] opened 2018-04-18 16:42 UTC
- Laravel Version: 5.5
- Voyager Version: Last
- PHP Version: 7.2
- Database Driver & Version:

### Description:
The BelongsTo SelectBox is bugged on Edit - Doesn't Update the value

### Steps To Reproduce:
Add a record to a table with a relantionship. After, edit it and select other value on the relationship. The record won't update the value after saving. I debbuged the Select and looks like the "Selected" value never changes.

**Comment by varbark** [comment] 2018-04-20 12:22
Me too, I have the same issue.

**Comment by sav-valerio** [comment] 2018-04-20 17:39
Same here on Chrome, Firefox and Edge.

Still, the HTTP request is sent correctly to the server.
If I manually open the 'record list' then, I can see the new record that I just added. 
No JavaScript errors in Console.

This is very annoying, please check it out.

**Comment by varbark** [comment] 2018-04-22 03:59
I think it related to this issue #3014

**Comment by emptynick** [comment] 2018-04-22 08:28
@varbark How can a bug reported 4 days ago be caused by a PR merged 2 days ago? ;)
Despite that, this PR is not tagged, so you cant get it easily through composer

**Comment by sav-valerio** [comment] 2018-04-22 10:08
@varbark the PR has been merged to 1.1.x-dev.

Still no change, the bug is still present.

**Comment by varbark** [comment] 2018-04-27 15:39
After I look up the commit history , I think this problem exist in previous version. 
Anyway,  the way I found to temporary fix it is by adding original column as hidden field in add or edit.

**Comment by sav-valerio** [comment] 2018-04-27 15:43
What do you mean precisely with 'original column'? @varbark

**Comment by varbark** [comment] 2018-04-28 14:13
@sav-valerio   ex:   if there is an orders table which has user_id, and you have an order_belongs_to_user relationship , then you should also set user_id as hidden field

**Comment by emptynick** [comment] 2018-12-27 10:09
Fixed in https://github.com/the-control-group/voyager/pull/3016 (merged into 1.x)

**Closed as completed by emptynick** 2018-12-27 10:09 UTC
