### ISSUE TITLE
Request Multiple BREAD for one table

### ISSUE THREAD

**Issue by hexters** [thedevdojo/voyager#5071] opened 2020-09-09 09:08 UTC
## Version information

 - Laravel: v8
 - Voyager: v1.4
 - PHP: 7.3
 - Database: MySql 8

## Description of problem

I need create BREAD which support [Laravel Single Table Inheritance
](https://github.com/jonspalmer/single-table-inheritance)

## Proposed solution
One table can create multiple BREAD with different Model

**Comment by MrCrayon** [comment] 2020-09-09 10:10
Duplicate of #1926

**Closed as completed by MrCrayon** 2020-09-09 10:10 UTC
Labels: duplicate, feature
