### ISSUE TITLE
Allow overriding the Relationship's option to control the display size 

### ISSUE THREAD

**Issue by vkiranmaniya** [thedevdojo/voyager#4650] opened 2019-12-20 20:30 UTC
## Version information

 - Laravel: v6.6.1
 - Voyager: v1.3.0
 - PHP: 7.3.1

## Description
Currently, I'm using the below-given Option Details to control the field size in BREAD,
```
{
    "display": {
        "width": 6
    }
}
```
The issue is, how do I do that in Relationship? as the relationship doesn't allow overriding the option details, I didn't find any way to do it. Is it possible by overriding the view inside `resources/views/tools/bread/relationship-partial.blade.php`? I just want the JSON configuration box for the Relationship. if it is the only way Igave, let me know. I'll do it and create a pull request for it.

**Comment by MrCrayon** [comment] 2019-12-21 00:42
Duplicate of #2182 

That will be available soon, it's already merged. 
#4633

**Closed as completed by MrCrayon** 2019-12-21 00:42 UTC
Labels: duplicate
