### ISSUE TITLE
Menu Builder not display  menu TITLE when Add New/Edit

### ISSUE THREAD

**Issue by hungxinh** [thedevdojo/voyager#3042] opened 2018-04-23 16:01 UTC
- Laravel Version: 5.6.12
- Voyager Version: 1.1.0
- PHP Version: 7.1.14
- Database Driver & Version: mysqlnd 5.0.12-dev - 20150407

### Description:
Menu Builder NOT display **menu title** Add New/ Edit.
I'm using 2 language: vi (Vietnam) and en (English).
default: vi
locales: vi, en

![screenshot 2018-04-23 22 44 35](https://user-images.githubusercontent.com/23396671/39138215-aa01b380-4749-11e8-8a10-a19a1342bb75.png)

![screenshot 2018-04-23 22 57 07](https://user-images.githubusercontent.com/23396671/39138230-b18600de-4749-11e8-95c4-8b35a29b1a91.png)

View Menu  HTML:
`<div class="dd-handle">
<input type="hidden" data-i18n="true" name="title17_i18n" id="title17_i18n" value="{&amp;quot;vi&amp;quot;:&amp;quot;About VI&amp;quot;,&amp;quot;en&amp;quot;:&amp;quot;About EN&amp;quot;}">
<span></span> <small class="url">/</small>
</div>`
 
Edit HTML:
`<label for="name">Title of the Menu Item</label>
<input type="hidden" data-i18n="true" name="title_i18n" id="title_i18n" value="{&quot;vi&quot;:&quot;&quot;,&quot;en&quot;:&quot;&quot;}">
<input type="text" class="form-control" id="m_title" name="title" placeholder="Title">`

**Comment by hungxinh** [comment] 2018-04-24 14:59
If i set 'enabled' => true on config/voyager.php  then menu title not display
    'multilingual' => [
        /*
         * Set whether or not the multilingual is supported by the BREAD input.
         */
        'enabled' => **# true**, 
![screenshot 2018-04-24 22 01 37](https://user-images.githubusercontent.com/23396671/39195996-3dc8a800-480b-11e8-9e0f-8be42677bd57.png)

if  'enabled' => false  then menu title display

**Comment by emptynick** [comment] 2018-04-27 11:58
Closing as this is a duplicate of https://github.com/the-control-group/voyager/issues/2731

**Closed as completed by emptynick** 2018-04-27 11:58 UTC
Labels: duplicate
