### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by MohsinNadeem** [thedevdojo/voyager#1961] opened 2017-10-08 19:34 UTC
- Laravel Version: 5.5
- Voyager Version: dev-master
- PHP Version: 7.1

### Description:

I have a table and bread by the name of institutes. All attributes are just like the default posts table. But when I try to edit a previously created institute. Instead of updating, it shows this error:

`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY' (SQL: update `institutes` set `id` = 1, `updated_at` = 2017-10-08 19:21:45 where `id` = 4)`

When I try to edit a default post from posts table, it works fine. But here on editing institute from institutes table it is showing error. 

Please suggest a solution.

**Comment by JapSeyz** [comment] 2017-10-08 22:37
It seems like you somehow may have run the seeders multiple times, and/or is doing an illigal action from the bread-editor.

Could you try to re-migrate and see if that works out?

`php artisan migrate:reset` followed by `php artisan migrate` and lastly `php artisan voyager:install --with-dummy`

**Comment by fletch3555** [comment] 2017-10-09 15:19
Looks like you don't have `id` listed as the $primaryKey, so it's trying to update its value.  The DB then complains because the id field has a UNIQUE index.  I'm not certain this is actually a Voyager issue, but we'll need much more information (DB schema, BREAD configuration, steps to reproduce, etc) before we can help.

**Comment by ArtemMolotov** [comment] 2018-01-23 16:42
Same problem (`email` field has a UNIQUE index). Can we use validation, show errors on a add/edit page?

**Comment by emptynick** [comment] 2018-03-10 14:02
This was likely fixed in #2690

**Closed as completed** 2018-03-10 14:36 UTC
Labels: possible bug
