### ISSUE TITLE
Unable to create "" folder error when uploading non-image files using Media manager with S3 storage

### ISSUE THREAD

**Issue by 50bbx** [thedevdojo/voyager#2904] opened 2018-03-27 14:59 UTC
- Laravel Version: 5.5.39
- Voyager Version: 1.0.16
- PHP Version: 7.2.3
- Database Driver & Version: MySQL 5.7

### Description:
Using S3 driver I'm unable to upload anything different from images

### Steps To Reproduce:
Use S3 as storage
```php
<?php

return [
    //...everything else here...

    'storage' => [
        'disk' => 's3',
    ],
```

Try to upload a .txt, a .pdf. It will say "Unable to create "" folder". The issue is in the `upload` function in the `VoyagerMediaController` class. In particular why is the image uploaded like this:

```php
$file = $request->file->store($request->upload_path, $this->filesystem); //line 190
```

while all other files are uploaded like this?

```php
$file = $request->file->move($realPath, $request->file->getClientOriginalName()); // 200
```

changing line 200 with the content of line 190 fixes the issue for S3, but I don't know for other filesystems.

**Comment by emptynick** [comment] 2018-03-27 15:08
See https://github.com/the-control-group/voyager/pull/2524

**Comment by emptynick** [comment] 2018-04-01 18:11
Closing as this is a duplicate of #2356

**Closed as completed by emptynick** 2018-04-01 18:11 UTC
Labels: duplicate
