### ISSUE TITLE
Settings image upload problem

### ISSUE THREAD

**Issue by darana07** [thedevdojo/voyager#3251] opened 2018-05-30 17:24 UTC
- Laravel Version: 5.6.*
- Voyager Version: 1.1
- PHP Version: 7.1.3
- Database Driver & Version:

### Description:
In Settings option in admin panel, images are deleting every time i add a new setting or change image. So when i need to change an specific image, i need to upload all settings images again.

**Comment by emptynick** [comment] 2018-05-30 17:26
Please search before opening a issue.
Duplicate of #3158, #3059, #2934 and #3224
Fix in #3060 (merged just an hour ago)

**Closed as completed by emptynick** 2018-05-30 17:26 UTC
Labels: duplicate
