### ISSUE TITLE
Audio files upload via media manager

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#2283] opened 2017-11-26 15:54 UTC
- Laravel Version: 5.4
- Voyager Version: 1.0
- PHP Version: 7.0
- Database Driver & Version: mysql

### Description:
How to enable audio files upload via media manager?

**Comment by emptynick** [comment] 2018-12-27 23:22
The problem is that Laravel (or PHP?) sometimes is not able to get the correct extension because there's no mimetype. It then stores it as a binary-file.

**Comment by emptynick** [comment] 2019-01-08 09:22
Closing as #3860 was merged (into 1.x, to be released in a future 1.2 release)

**Closed as completed by emptynick** 2019-01-08 09:22 UTC
Labels: type:bug
