### ISSUE TITLE
Database Bread Option Field not updating to Null 

### ISSUE THREAD

**Issue by DrudgeRajen** [thedevdojo/voyager#2916] opened 2018-03-30 08:26 UTC
- Laravel Version: 5.5.*
- Voyager Version: 1.0.16
- PHP Version:7.0.22
- Database Driver & Version:14.14

### Description:
While updating database BREAD, previously saved option value cannot be saved as null.

### Steps To Reproduce:
1) Add a table 
2) Create Bread 
3) Add value in option for one field.
4) Edit and remove the previous option value (i.e. please keep option filed  empty)
The value of an option doesn't save as null.It saves the previous value.

**Comment by emptynick** [comment] 2018-03-30 12:41
This is a duplicate of https://github.com/the-control-group/voyager/issues/1402 and it will be fixed once https://github.com/the-control-group/voyager/pull/2377 is merged

**Closed as completed by emptynick** 2018-03-30 12:41 UTC
Labels: duplicate
