### ISSUE TITLE
Laravel 5.7.* Support

### ISSUE THREAD

**Issue by spooksie** [thedevdojo/voyager#3542] opened 2018-09-13 23:56 UTC
It would be great for a 5.7.* version of Laravel Voyager. I know its time consuming to make sure everything is working for this new build. 

I'm loving Voyager! building a big project from it.

**Comment by fletch3555** [comment] 2018-09-14 00:19
5.7 support has already been discussed, and will be implemented soon.  We're taking care of a few prerequisites first.

Closing as duplicate of #3519

**Closed as completed by fletch3555** 2018-09-14 00:19 UTC
Labels: duplicate
