### ISSUE TITLE
Richt text without value breaks clientside validation

### ISSUE THREAD

**Issue by bbrala** [thedevdojo/voyager#2965] opened 2018-04-13 09:17 UTC
- Laravel Version: 5.5
- Voyager Version: 1.0.17
- PHP Version: 7.0
- Database Driver & Version: MySQL 5.6

### Description:
When i add a richtext field to a multilanguage bread, and i try to submit the form i get the follwing javascript error:

```
An invalid form control with name='value' is not focusable.
```

I dove into it a bit and it seems it tried to show a client-side validation error on the textarea. Since Tiny is loaded the textarea has `display:none` so it tried to focus an hidden field.

### Steps To Reproduce:
1. Enable multilang
1. Create a bread with a textfield (varchar column) and a richText (text column).
1. Try to submit the from.
1. The error should come up.

**Comment by emptynick** [comment] 2018-04-13 09:22
There are two issues with the exact same problem and solutions are provided there.
Please search before opening a new issue.
Duplicate of https://github.com/the-control-group/voyager/issues/2894 and https://github.com/the-control-group/voyager/issues/2578

**Closed as completed by emptynick** 2018-04-13 09:22 UTC
Labels: duplicate

**Comment by bbrala** [comment] 2018-04-13 09:54
Hmm, sorry i didnt find those issues when searching. Thanks.
