### ISSUE TITLE
Relationship in view read and browse doesn't work

### ISSUE THREAD

**Issue by Webpicasso** [thedevdojo/voyager#707] opened 2017-02-10 13:03 UTC
- Laravel Version:  v5.3.30
- Voyager Version: v0.10.13
- PHP Version: PHP 5.6.8 (cli)
- Database Driver & Version: MySQL 5.6.24

### Description:
Set up a relationship  in BREAD works perfect in edit form but in the browse view and read view you get only the value from the current table.  

### Steps To Reproduce:
I have a table budgets (id,description, ..., services_id) and a table services (id, name)

The relation in the Budget Model:
public function servicesid() {
    return $this->belongsTo(Service::class);
}

I have created a BREAD on the budget table with following JSON on field services_id:
{
    "relationship": {
        "key": "id",
        "label": "name"
    }
}

If I call budgets browse or read (budgets/ or budgets/1), I get only the value budgets.services_id in the column services_id instead of the services.name value from table services.
If I call edit ( budgets/1/edit) I have a dropdown for field service_id with the services.name entries.

I have checked both views and I think that is not supported yet!

**Comment by marktopper** [comment] 2017-02-10 13:07
Yea, the problem is that the `browse` and `read` bread does not support the `relationship.label` option yet.
Is indeed a bug.

**Comment by SkyL0ver** [comment] 2017-02-11 19:20
i have same problem too..

**Comment by sidis405** [comment] 2017-02-12 11:52
#715 Currently working on this.

**Comment by marktopper** [comment] 2017-02-19 07:55
Should have been fixed now

**Closed as completed by marktopper** 2017-02-19 07:55 UTC
Labels: type:bug, help wanted
