### ISSUE TITLE
Installation problem "require.test-hook is invalid, it should have a vendor name"

### ISSUE THREAD

**Issue by chrisoprea** [thedevdojo/voyager#5266] opened 2021-03-19 06:08 UTC
## Version information

 - Laravel: v8.33.1
 - Voyager: v1.x.dev
 - PHP: 7.4.5
 - Database: MySQL 5.7

## Description
```
require.test-hook is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]
(([_.]?|-{0,2})[a-z0-9]+)*$".
```

## Steps To Reproduce
`php artisan hook:install test-hook`

## Screenshots
![image](https://user-images.githubusercontent.com/78136650/111738441-0f63df80-888a-11eb-9b72-f76992e2221e.png)

**Comment by emptynick** [comment] 2021-03-19 08:27
Please search before opening issues,
Duplicate of https://github.com/the-control-group/voyager/issues/5138

**Closed as completed by emptynick** 2021-03-19 08:27 UTC
Labels: duplicate
