### ISSUE TITLE
[BUG] Table with two file columns, Bread fails to upload second file

### ISSUE THREAD

**Issue by gomezed** [thedevdojo/voyager#3984] opened 2019-03-05 01:28 UTC
## Version information

 - Laravel: v5.7.*
 - Voyager: v1.1
 - PHP: 7.2
 - Database: MySQL 5.4

## Description
Having a table with 2 columns of type varchar(256) to upload 2 different files, fails when using insert new record form, there is no error displayed but the second file is never uploaded and the stored value in the table is an empty json

## Steps To Reproduce
1. Create a simple table and add 2 varchar fields
2. Create BREAD for the table
3. Set input as File for both columns
4. Insert a new record
5. pick two files and save
6. check table info, one file gets correctly uploaded the other one doesn't upload and the stored value in the table is an empty json

## Expected behavior
Both files should get uploaded and the info in the table should be complete.

## Additional context
I don't need the multiple files option since I am creating an API that should retrieve each file as specific properties of the model

**Comment by gomezed** [comment] 2019-03-08 13:55
Happens only on localhost, probably for php artisan serve limitations?

**Comment by adrhem** [comment] 2019-06-03 15:58
Happened to me on production server too.

**Comment by emptynick** [comment] 2019-07-28 21:05
Duplicate of https://github.com/the-control-group/voyager/issues/3002

**Closed as completed by emptynick** 2019-07-28 21:05 UTC
Labels: duplicate
