### ISSUE TITLE
[BUG] profile dropdown menu doesn't work on RTL mode

### ISSUE THREAD

**Issue by theafaid** [thedevdojo/voyager#3865] opened 2019-01-02 20:38 UTC
When I change multilingual['rtl'] = true .. the profile dropdown menu doesn't open how ever class (.open)
added to it.

**Comment by emptynick** [comment] 2019-01-02 20:51
Please search before opening new issues and use the issue-template.
Closing as a duplicate of https://github.com/the-control-group/voyager/issues/3084 which was fixed in https://github.com/the-control-group/voyager/pull/3754 and merged into 1.x

**Closed as completed by emptynick** 2019-01-02 20:51 UTC
Labels: duplicate
