### ISSUE TITLE
BelongsTo ServerSide Search

### ISSUE THREAD

**Issue by guillermovergara88** [thedevdojo/voyager#3595] opened 2018-10-02 03:47 UTC
## Version information

 - Laravel: v5.4
 - Voyager: v1.1.3
 - PHP: 7.1
 - Database: MySQL 5.6.4

## Description
Can't search BelongTo items on Browse view in Server-Side Search

## Steps To Reproduce
1. Go to BREAD
2. Create a new BelongsTo relationship.
3. Select Server-Side pagination
4. Go to the model Browse View
5. Try to search content based on the Related table.

## Expected behavior
What is needed here, is to customize the seach-key dropdown filter, so it is possible to search based on the related model data.

## Screenshots
![ss](https://user-images.githubusercontent.com/28458358/46328248-a403f580-c5dc-11e8-9edd-33065f28c63d.jpg)

**Comment by fletch3555** [comment] 2018-10-02 16:42
Are you claiming you can search for the relationship field when server-side pagination is _disabled_?

**Comment by emptynick** [comment] 2018-10-02 16:56
Probably. Because Datatables is responsible for searching then.

**Comment by guillermovergara88** [comment] 2018-10-02 18:02
The main problem is that I cannot search for related BelongsTo items in the datatable when it is ServerSide.

**Comment by eroberto17** [comment] 2019-01-09 16:05
i have the same problem

**Comment by jegardiner** [comment] 2019-05-01 18:03
I would also like to be able to search on fields from relationships.

**Comment by dalsn** [comment] 2019-08-07 10:27
Has anyone found a way to do this? Loading all the table entries for large tables without server side pagination just so I can use datatables takes an awfully long time.

**Comment by SayDevz** [comment] 2019-10-17 15:12
any update on this ? server side search using relationship field ?

**Comment by ikramulmustafa** [comment] 2019-10-21 10:11
@emptynick  any update ?
but if i want to search date base on customer name in ORDERs
but in order table i store id of customer
and i am making relation in model then why its not searching with name

**Comment by ikramulmustafa** [comment] 2019-10-21 10:14
@emptynick  like he is saying in #4216

**Comment by kolesar** [comment] 2019-10-21 19:22
I made an ugly code, just to see if it works. Please, help me to improve it to be under the Voyager standard.

in the Class:
https://github.com/the-control-group/voyager/blob/1.3/src/Http/Controllers/VoyagerBaseController.php#L91

I added the following code:
```
$relationFiled = $this->findRelationField($dataType, $search->key);
if(is_array($relationFiled)) {
    $query->whereHas($relationFiled[0], function(Builder $query) use ($relationFiled, $search_filter, $search_value) {
        $query->where($relationFiled[1], $search_filter, $search_value);
    });
} else {
    $query->where($relationFiled, $search_filter, $search_value);
}
```

Method `findRelationField` looks like:
```
protected function findRelationField(DataType $dataType, string $searchKey)
{
    foreach ($dataType->browseRows as $key => $row) {
        if ($row->type === 'relationship' &&
            $row->details->type === 'belongsTo' &&
            $row->details->column === $searchKey
        ) {
            return [$row->details->table, $row->details->label];
        }
    }

    return $searchKey;
}
```

With this code is possible to search by relatives in the Voyager browser model.

Of course, this requires to have methods in the Models, like:
```
public function countries()
{
     return $this->belongsTo('App\Country', 'country_id', 'id');
}
```

**Comment by ikramulmustafa** [comment] 2019-10-22 05:29
@Kolesar  bro can you explain how this function will perform and what will it do?

**Comment by kolesar** [comment] 2019-10-22 05:42
Hi @Spartaa ,

Thanks for the quick reply.

Atm, on the Voyager Admin browser we have the server and client-side searching. Client-side works with JS and it works fine, but server-side searching does not work properly. We have to search by relation ID instead of by relation show field (what we select in BREAD).

For example:
Our Model table show is user model with relation field countries. If we set all parameters in the BelongsTo in BREAD for this modal, we will see in user modal table instead country_id, country_name. BUT! If we want to use searching by server-side it will not work as a user expect. Users can select Country and filter Contain for example but MUST enter country_id in the search field, not Country Name.

With this code, the end-user can search by country_name without any problem. I'm not sure that this code following the Voyager standard and that is the reason why I ask you to help me to improve this code to be under the Voyager standard. And need, unit tests and so on :)

**Comment by ikramulmustafa** [comment] 2019-10-22 05:50
@emptynick  Can you check this code is under the Voyager standard. And need, unit tests and so on :)

**Comment by ikramulmustafa** [comment] 2019-10-22 05:51
@Kolesar I am going to try this in my module then I will let you know and we can see how can we improve it more.

**Comment by ikramulmustafa** [comment] 2019-10-22 06:00
this code will be added after Line 91 @Kolesar  where they are saying about remove relation feild in a browse?

**Comment by kolesar** [comment] 2019-10-22 06:03
> this code will be added after Line 91 @Kolesar where they are saying about remove relation feild in a browse?

Line 91 will be replaces with this code, exactly:
```
$relationFiled = $this->findRelationField($dataType, $search->key);
if(is_array($relationFiled)) {
    $query->whereHas($relationFiled[0], function(Builder $query) use ($relationFiled, $search_filter, $search_value) {
        $query->where($relationFiled[1], $search_filter, $search_value);
    });
} else {
    $query->where($relationFiled, $search_filter, $search_value);
}
```

**Comment by Spartaa** [comment] 2019-10-22 06:11
Argument 1 passed to App\Http\Controllers\Wallet\WalletController::App\Http\Controllers\Wallet\{closure}() must be an instance of App\Http\Controllers\Wallet\Builder, instance of Illuminate\Database\Eloquent\Builder given, called in E:\Quaid Ventures\qareeb_captain\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php on line 962

@Kolesar 

Quaid Ventures\qareeb_captain\app\Http\Controllers\Wallet\WalletController.php:116

                    $query->whereHas($relationFiled[0], function(Builder $query) use ($relationFiled, $search_filter, $search_value) {

**Comment by ikramulmustafa** [comment] 2019-10-22 06:19
Instead  Builder $query use only $query it will work fine @Kolesar 
remove Builder

**Comment by kolesar** [comment] 2019-10-22 20:07
> Instead Builder $query use only $query it will work fine @Kolesar
> remove Builder

No! You use the wrong class. You have to use `use Illuminate\Database\Eloquent\Builder;` ;)

**Comment by ikramulmustafa** [comment] 2019-10-23 05:11
> > Instead Builder $query use only $query it will work fine @Kolesar
> > remove Builder
> 
> No! You use the wrong class. You have to use `use Illuminate\Database\Eloquent\Builder;` ;)

I removed Builder it start working fine thats why i thought may be that causing

**Comment by emptynick** [comment] 2019-10-23 13:17
Unfortunately we don't rely on relationship-methods. So we can't use the code as is.
Instead, we'd need to do some left-joins in the search-query.

**Comment by kolesar** [comment] 2019-10-23 14:54
@emptynick I saw in the MR so many requests for many different improvements. One or two of them are related to this topic and they implement it with the `leftJoin`, but you are not accepting their MR.

Can you check it, please?

If you need more developer hands on this, just tell us and we will give some effort :)

**Comment by ikramulmustafa** [comment] 2019-10-23 14:59
> @emptynick I saw in the MR so many requests for many different improvements. One or two of them are related to this topic and they implement it with the `leftJoin`, but you are not accepting their MR.
> 
> Can you check it, please?
> 
> If you need more developer hands on this, just tell us and we will give some effort :)

I agree with @Kolesar there is   many requests for many different improvements and request are abandoned or pending

**Comment by emptynick** [comment] 2019-10-23 16:16
> I agree with @Kolesar there is many requests for many different improvements and request are abandoned or pending

This is an open source project. Open source projects rely on users to create PRs **and** check PRs for quality and functionality.
We don't get paid for this. Don't forget that.

**Comment by ikramulmustafa** [comment] 2019-10-23 16:24
we know that u dont get paid
 then why u r rejecting public requests then?

**Comment by ikramulmustafa** [comment] 2019-10-23 16:25
we also want to make it more perfect

**Comment by emptynick** [comment] 2019-10-23 16:38
I didn't reject anything?

**Comment by fletch3555** [comment] 2019-10-23 17:03
Guys, can we move the discussion to slack?

**Comment by ikramulmustafa** [comment] 2019-10-24 05:15
Yes Sure

> Guys, can we move the discussion to slack?

**Comment by rsecor** [comment] 2019-12-16 00:47
Is there any update on having associated data being searchable?

**Comment by ajduff14** [comment] 2021-01-07 15:57
Hi All,

Was also experiencing this problem, I overrode VoyagerBaseController & added the following in place of lines 92-96 v1.42.

```
// CHANGED - Start
if ($search->value != '' && $search->key && $search->filter) {
    $search_filter = ($search->filter == 'equals') ? '=' : 'LIKE';
    $search_value = ($search->filter == 'equals') ? $search->value : '%'.$search->value.'%';

    $isRelation = false;
    $relationshipIds = [];

    foreach ($dataType->browseRows as $key => $row) {
        if ($row->type === 'relationship' &&
            $row->details->type === 'belongsTo' &&
            $row->details->column === $search->key
        ) {

            $relationshipIds = DB::table($row->details->table)
                ->select($row->details->key, $row->details->label)
                ->where($row->details->label, $search_filter, $search_value)
                ->pluck($row->details->key)
                ->toArray();

            $isRelation = true;
        }
    }

    if($isRelation) {
        $query->whereIn($search->key, $relationshipIds);
    } else {
        $query->where($search->key, $search_filter, $search_value);
    }
}
// CHANGED - End
```

The above relies on a BelongsTO Relationship BREAD field for displaying the label of the relationship instead of an id.

Should work for any belongsTo relationship as it takes the labels & keys needed defined in the BREAD.

Hope this may be of some use.

**Comment by MrCrayon** [comment] 2021-01-08 04:17
@ajduff14 that looks quite similar on what I'm doing in #5185.
I'm using a global scope because I tried to do it all in one query but since that didn't work I should probably drop it, thanks for the idea!

If you can have a look at my PR there is also the fix for ordering, more people can test it more likely is going to be merged.

**Closed as completed** 2021-01-28 12:25 UTC

**Comment by namcusamlc** [comment] 2021-06-28 10:26
> @ajduff14 that looks quite similar on what I'm doing in #5185.
> I'm using a global scope because I tried to do it all in one query but since that didn't work I should probably drop it, thanks for the idea!
> 
> If you can have a look at my PR there is also the fix for ordering, more people can test it more likely is going to be merged.

Hi Crayon,
The error appears again and seems like it is caused by others' updates
I just check on the current code and seems like your modification (in file VoyagerBaseController) had some updates from other developers.

Hope you can get some help around there.

**Comment by kauetc** [comment] 2021-08-09 21:01
Hi @ajduff14,

It worked great for me thanks for the solution. 

I was getting the error of unknown column at the database, something like SQLSTATE[42S22]: Column not found: 1054 Unknown column 'inspections.inspection_belongsto_lote_relationship' in 'where clause' (SQL: select count(*) as aggregate from `inspections` where `inspections`.`inspection_belongsto_lote_relationship` LIKE %210212%).

**Comment by jegardiner** [comment] 2021-08-10 09:00
Hi @kauetc,

I'm not sure if your comment was saying that you are still getting the "column not found" error, or if that was the error the above code fixed.

If it's the former, you may be interested in issue #5412 .

**Comment by kauetc** [comment] 2021-08-10 14:41
Hi @jegardiner 

Sorry, I wasn't clear with my answer, the code above fixed the error. I posted the error for future readers that may have the same issue.
