### ISSUE TITLE
[BUG] File DataType overwrites already uploaded files

### ISSUE THREAD

**Issue by gkmk** [thedevdojo/voyager#4087] opened 2019-04-16 09:08 UTC
## Version information
 - Laravel: v5.8
 - Voyager: v1.2
 - PHP: 7.2
 - Database: MySQL 5.7

## Description
When editing model that already has file uploaded it overwrites the file with `[]`

## Steps To Reproduce
1. Go to `Edit` upload file
2. After update go to `Edit` on the same model. The model should have the file uploaded
3. Edit any field on the same model and update
4. Open `View` or `Edit` the uploaded file will not exist and will be replaced with `[]`

## Expected behavior
Must not overwrite already uploaded files

## Additional context
I have created patch for this problem on my fork but the tests fail as they expect database entry `[]`
The problem is in `TCG\Voyager\Http\Controllers\ContentTypes\File`
```
if (!$this->request->hasFile($this->row->field)) {
      return json_encode([]);
}
```

**Comment by emptynick** [comment] 2019-04-16 09:14
Please search before opening new issues.
Closing as a duplicate of https://github.com/the-control-group/voyager/issues/4020

**Closed as completed by emptynick** 2019-04-16 09:14 UTC
Labels: duplicate
